
[functions.generate-report]
enabled = true
verify_jwt = false
import_map = "./functions/generate-report/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-report/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-report/*.html" ]

[functions.ai-report-generate]
enabled = true
verify_jwt = true
import_map = "./functions/ai-report-generate/deno.json"
entrypoint = "./functions/ai-report-generate/index.ts"

[functions.ai-socratic-tutor]
enabled = true
verify_jwt = true
entrypoint = "./functions/ai-socratic-tutor/index.ts"

[functions.consent-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/consent-webhook/deno.json"
entrypoint = "./functions/consent-webhook/index.ts"


[auth]
additional_redirect_urls = []
password_requirements = "lower_upper_letters_digits_symbols"
site_url = "https://warp-labs.vercel.app/"

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 600

[auth.email.template.confirm_signup]
subject = "Your WARP verification code"
content_path = "./supabase/templates/confirm_signup.html"

[auth.email.smtp]
enabled = true
host = "smtp.gmail.com"
port = 587
user = "govibe689@gmail.com"
admin_email = "govibe689@gmail.com"
sender_name = "WARP Academy"

[auth.rate_limit]
email_sent = 30

[auth.external.google]
client_id = "239394742292-5j2m6eu5na4rurqmv9ftko433cqh5rvt.apps.googleusercontent.com"
enabled = true

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[db.pooler]
default_pool_size = 15
max_client_conn = 200

[storage.analytics]
enabled = true
max_namespaces = 10

[storage.image_transformation]
enabled = true
