import type { ScenarioRecord } from './types';

export function getBand3_4Scenarios(): ScenarioRecord[] {
  return [
    // ═════════════════════════════════════════════════════════════════════════
    // CLASS 3 (Grade 3 · Developmental Band 3-4) — 30 Unique Questions
    // ═════════════════════════════════════════════════════════════════════════
    // 1. Scientific Inquiry (6 items)
    {
      scenario_code: 'C03-SCI-01',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'A student puts an ice cube on a plate in the warm sun and another ice cube on a plate inside a refrigerator. After 10 minutes, the ice cube in the sun has completely melted into a puddle, while the ice in the refrigerator has barely changed. What is the cause of this difference?',
      options: [
        { text: 'Thermal energy from the sun transferred heat to the ice, causing it to change state from solid to liquid faster.', correct: true },
        { text: 'The refrigerator creates new cold ice to replace what melted.', correct: false },
        { text: 'Sunlight absorbs water from the air and adds it to the plate.', correct: false },
        { text: 'Ice only melts when it is touched by moving air.', correct: false },
      ],
      learning_objective: 'States of matter and heat energy transfer causing phase changes.',
      hint: 'Think about where the temperature is higher and heat is flowing into the ice.',
      irt_a: 1.1,
      irt_b: -1.8,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary 3 Science / US NGSS 2-PS1-4',
    },
    {
      scenario_code: 'C03-SCI-02',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'A student tests which objects are attracted to a bar magnet. The magnet attracts an iron nail and a steel paperclip, but does not attract a copper penny, a plastic ruler, or an aluminum soda can. What conclusion can be drawn from this test?',
      options: [
        { text: 'Only certain metals, such as iron and steel, exhibit magnetic attraction.', correct: true },
        { text: 'All shiny metal objects are strongly attracted to magnets.', correct: false },
        { text: 'The magnet was not strong enough to pick up the lighter objects.', correct: false },
        { text: 'Only objects shaped like thin rods can be attracted to magnets.', correct: false },
      ],
      learning_objective: 'Magnetic properties of materials and distinguishing ferromagnetic from non-magnetic metals.',
      hint: 'Notice that copper and aluminum are metals, yet they did not stick to the magnet.',
      irt_a: 1.2,
      irt_b: -1.5,
      irt_c: 0.25,
      international_benchmark: 'Cambridge Primary Science Stage 3',
    },
    {
      scenario_code: 'C03-SCI-03',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'At 8:00 AM, a vertical pole casts a long shadow pointing west. At 12:00 noon, its shadow is very short and points north. At 4:00 PM, the shadow is long again and points east. What causes this continuous change in the shadow?',
      options: [
        { text: 'Earth rotates on its axis, causing the sun to appear to move across the sky from east to west.', correct: true },
        { text: 'The sun physically grows larger and hotter during the middle of the day.', correct: false },
        { text: 'The pole bends as the temperature changes throughout the day.', correct: false },
        { text: 'Clouds push the sunlight in different directions as the wind blows.', correct: false },
      ],
      learning_objective: 'Sun position and shadow geometry caused by Earth rotation.',
      hint: 'Shadows always fall in the direction opposite to where the light source is located.',
      irt_a: 1.3,
      irt_b: -1.1,
      irt_c: 0.25,
      international_benchmark: 'TIMSS Grade 4 Science / UK Key Stage 2',
    },
    {
      scenario_code: 'C03-SCI-04',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'A student places a dry sponge in a bowl with 100 mL of blue water. When the sponge is lifted out, only 30 mL of water remains in the bowl. The mass of the sponge increased by exactly 70 grams. What scientific principle does this demonstrate?',
      options: [
        { text: 'Conservation of mass: the 70 mL of absorbed water was taken up by the porous sponge.', correct: true },
        { text: 'Water disappeared because the sponge destroyed liquid matter.', correct: false },
        { text: 'The blue dye evaporated instantly into the surrounding air.', correct: false },
        { text: 'The sponge grew heavier because water created new sponge fibers.', correct: false },
      ],
      learning_objective: 'Porosity, absorption, and mass conservation in physical mixtures.',
      hint: 'Remember that 1 mL of water has a mass of approximately 1 gram.',
      irt_a: 1.35,
      irt_b: -0.8,
      irt_c: 0.25,
      international_benchmark: 'US NGSS 5-PS1-2 / Singapore Primary 3',
    },
    {
      scenario_code: 'C03-SCI-05',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'A student drops three identical rubber balls from 1 meter height onto three surfaces: thick carpet, polished wood, and soft sand. The ball bounces 10 cm on carpet, 65 cm on wood, and 2 cm on sand. Why does the polished wood produce the highest bounce?',
      options: [
        { text: 'The rigid wood deforms very little, returning most of the ball’s kinetic energy during the collision rather than absorbing it.', correct: true },
        { text: 'Wood possesses a natural magnetic charge that pushes rubber upward.', correct: false },
        { text: 'Soft sand adds gravity to the ball, preventing it from rising.', correct: false },
        { text: 'The carpet creates a vacuum that holds the ball down.', correct: false },
      ],
      learning_objective: 'Elastic collisions, energy dissipation, and surface rigidity.',
      hint: 'Think about where the energy goes when an object hits a soft, shifting surface versus a hard one.',
      irt_a: 1.5,
      irt_b: -0.4,
      irt_c: 0.25,
      international_benchmark: 'SASMO Primary Science / Primary Olympiad',
    },
    {
      scenario_code: 'C03-SCI-06',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'Two identical sealed glass jars contain water. Jar 1 is filled with cold ice water (4°C); Jar 2 is filled with warm water (40°C). After 5 minutes in a warm room, tiny water droplets form on the OUTSIDE of Jar 1, but the outside of Jar 2 stays completely dry. Where did the droplets on Jar 1 come from?',
      options: [
        { text: 'Invisible water vapor in the surrounding air cooled and condensed into liquid when touching the cold glass.', correct: true },
        { text: 'Water leaked through tiny microscopic holes in the glass of Jar 1.', correct: false },
        { text: 'The cold glass produced water molecules from its own silica atoms.', correct: false },
        { text: 'The ice inside Jar 1 expanded so much that it pushed water outward.', correct: false },
      ],
      learning_objective: 'Atmospheric humidity, dew point, and condensation phase transition.',
      hint: 'The jar is completely sealed, so the water must come from the air around it.',
      irt_a: 1.6,
      irt_b: 0.0,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary Science Olympiad',
    },

    // 2. Computational Thinking (6 items)
    {
      scenario_code: 'C03-CT-01',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'A robotic toy car starts at square (1, 1) on a grid facing North. It executes these instructions: [MOVE FORWARD 2, TURN RIGHT 90°, MOVE FORWARD 3]. At what grid position does the car stop?',
      options: [
        { text: 'Square (4, 3)', correct: true },
        { text: 'Square (2, 3)', correct: false },
        { text: 'Square (3, 4)', correct: false },
        { text: 'Square (1, 5)', correct: false },
      ],
      learning_objective: 'Grid coordinates, directional heading, and sequential instruction execution.',
      hint: 'Moving North increases the vertical coordinate; turning right makes it face East, increasing the horizontal coordinate.',
      irt_a: 1.1,
      irt_b: -1.7,
      irt_c: 0.25,
      international_benchmark: 'Bebras Computational Thinking Primary / Scratch Junior',
    },
    {
      scenario_code: 'C03-CT-02',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'Look at this repeating pattern of shapes: [Circle, Triangle, Square, Circle, Triangle, Square, Circle, Triangle, ...]. What shape will appear at the 15th position in this sequence?',
      options: [
        { text: 'Square, because 15 is a multiple of 3 and Square is the 3rd shape in the repeating cycle.', correct: true },
        { text: 'Circle, because odd numbers always get circles.', correct: false },
        { text: 'Triangle, because it is in the middle of the pattern.', correct: false },
        { text: 'Star, because new shapes enter after position 10.', correct: false },
      ],
      learning_objective: 'Pattern recognition, modular repeating periods, and discrete arithmetic.',
      hint: 'Divide the position number by the length of the repeating group (3 shapes).',
      irt_a: 1.2,
      irt_b: -1.4,
      irt_c: 0.25,
      international_benchmark: 'European Bebras Challenge Class 3',
    },
    {
      scenario_code: 'C03-CT-03',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'A computer rule sorts fruit into baskets: "IF color is RED AND shape is ROUND, put in Basket 1; ELSE put in Basket 2." Where will a green round lime and a red long chili pepper be placed?',
      options: [
        { text: 'Both the lime and the chili will go to Basket 2 because neither satisfies both conditions at once.', correct: true },
        { text: 'The lime goes to Basket 1 and the chili to Basket 2.', correct: false },
        { text: 'Both go to Basket 1 because each has at least one matching property.', correct: false },
        { text: 'The computer stops and reports an error.', correct: false },
      ],
      learning_objective: 'Boolean logical conjunction (AND) and conditional branch execution.',
      hint: 'The word AND means both conditions must be true at the same time.',
      irt_a: 1.35,
      irt_b: -0.9,
      irt_c: 0.25,
      international_benchmark: 'Oxford University Computing Challenge (OUCC) Junior',
    },
    {
      scenario_code: 'C03-CT-04',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'A baker has a loop program: [SET count = 0; REPEAT 4 TIMES: {ADD 3 cookies, SET count = count + 3}]. At the end of the loop, what is the final value of count?',
      options: [
        { text: '12 cookies', correct: true },
        { text: '7 cookies', correct: false },
        { text: '9 cookies', correct: false },
        { text: '4 cookies', correct: false },
      ],
      learning_objective: 'Loop iteration, variable accumulation, and state tracing.',
      hint: 'The loop runs 4 times, adding 3 each time: 3 + 3 + 3 + 3.',
      irt_a: 1.4,
      irt_b: -0.6,
      irt_c: 0.25,
      international_benchmark: 'Code.org Course B / CSTA K-2 Algorithms',
    },
    {
      scenario_code: 'C03-CT-05',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'A squirrel needs to cross a 4x4 stone pond. It can only hop RIGHT or UP. If stone (2, 2) is broken and cannot be stepped on, how many safe paths can the squirrel take from bottom-left (1, 1) to top-right (4, 4)?',
      options: [
        { text: '14 safe paths (total paths = 20; paths through (2, 2) = 2 × 3 = 6; 20 - 6 = 14).', correct: true },
        { text: '20 safe paths', correct: false },
        { text: '10 safe paths', correct: false },
        { text: '16 safe paths', correct: false },
      ],
      learning_objective: 'Grid path enumeration with topological obstacles and combinatorial subtraction.',
      hint: 'Count the total ways to navigate a 3-step by 3-step grid, then subtract the paths that pass through the broken stone.',
      irt_a: 1.6,
      irt_b: -0.1,
      irt_c: 0.25,
      international_benchmark: 'Australian Informatics Competition (AIC) Primary',
    },
    {
      scenario_code: 'C03-CT-06',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'Five children stand in line with heights: [120 cm, 135 cm, 110 cm, 140 cm, 125 cm]. An algorithm swaps adjacent neighbors that are in the wrong order until the line is sorted from shortest to tallest. What is the MINIMUM number of swaps needed?',
      options: [
        { text: '4 swaps (inversions count: (135,110), (120,110) doesn\'t invert, (135,125), (140,125) etc.)', correct: true },
        { text: '2 swaps', correct: false },
        { text: '7 swaps', correct: false },
        { text: '5 swaps', correct: false },
      ],
      learning_objective: 'Inversion counting and elementary bubble-sort swap metrics.',
      hint: 'Count how many pairs of children have the taller child standing ahead of the shorter child.',
      irt_a: 1.65,
      irt_b: 0.2,
      irt_c: 0.25,
      international_benchmark: 'Bebras Castor Benjamin Olympiad',
    },

    // 3. Engineering Design (6 items)
    {
      scenario_code: 'C03-ED-01',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'Two children want to play on a playground seesaw. Child A weighs 30 kg and Child B weighs 15 kg. When Child A sits at the far end, Child B cannot push their side down. Where should Child A sit to balance the seesaw?',
      options: [
        { text: 'Move closer to the center pivot (fulcrum), decreasing their turning force (torque).', correct: true },
        { text: 'Move further backward off the edge of the seat.', correct: false },
        { text: 'Wear heavier boots.', correct: false },
        { text: 'Stand up and jump continuously on the seat.', correct: false },
      ],
      learning_objective: 'First-class levers, fulcrum positioning, and rotational equilibrium.',
      hint: 'To balance a lighter person, a heavier person needs to sit closer to the middle.',
      irt_a: 1.15,
      irt_b: -1.7,
      irt_c: 0.25,
      international_benchmark: 'US NGSS K-2-ETS1 / Singapore Primary 3',
    },
    {
      scenario_code: 'C03-ED-02',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'A student builds a tall tower out of wooden blocks, but whenever someone bumps the table, the tower falls over immediately. Which modification will make the tower most stable?',
      options: [
        { text: 'Widen the bottom base and place the heaviest blocks at the bottom to lower the center of gravity.', correct: true },
        { text: 'Make the tower narrower and twice as tall.', correct: false },
        { text: 'Put the heaviest blocks at the very top.', correct: false },
        { text: 'Paint the blocks with glossy paint.', correct: false },
      ],
      learning_objective: 'Structural stability, base-to-height ratio, and center of mass.',
      hint: 'A pyramid is much harder to tip over than a tall, thin stick.',
      irt_a: 1.25,
      irt_b: -1.4,
      irt_c: 0.25,
      international_benchmark: 'Cambridge Primary Design & Technology',
    },
    {
      scenario_code: 'C03-ED-03',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'An engineer designs a ramp for rolling heavy boxes onto a truck bed that is 1 meter high. Ramp A is 2 meters long; Ramp B is 4 meters long. How does using Ramp B compare to Ramp A?',
      options: [
        { text: 'Ramp B requires half as much pushing force, but the box must be pushed twice as far.', correct: true },
        { text: 'Ramp B requires twice as much pushing force because it is longer.', correct: false },
        { text: 'Both ramps require the exact same pushing force and distance.', correct: false },
        { text: 'Ramp B makes the box lighter on the scale.', correct: false },
      ],
      learning_objective: 'Inclined plane mechanical advantage and force-distance trade-off.',
      hint: 'A gentler slope is easier to push up, but you have to walk further.',
      irt_a: 1.4,
      irt_b: -0.8,
      irt_c: 0.25,
      international_benchmark: 'Project Lead The Way (PLTW) Elementary',
    },
    {
      scenario_code: 'C03-ED-04',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'A team designs a handheld flashlight. They have a battery, a bulb, and insulated copper wires. When they connect wire from battery (+) to the bulb, the bulb does not light. What missing engineering requirement explains this?',
      options: [
        { text: 'An electric circuit must be a complete closed loop returning to the battery (-) terminal for current to flow.', correct: true },
        { text: 'The bulb needs to be warmed up with a lighter first.', correct: false },
        { text: 'Electricity can only travel through glass tubes, not copper wires.', correct: false },
        { text: 'Batteries only produce power when placed upside down.', correct: false },
      ],
      learning_objective: 'Closed electrical circuit continuity and conductor pathway requirements.',
      hint: 'Electricity must have a complete path to leave the battery and return to it.',
      irt_a: 1.45,
      irt_b: -0.5,
      irt_c: 0.25,
      international_benchmark: 'UK Key Stage 2 Science & Design',
    },
    {
      scenario_code: 'C03-ED-05',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'To cross a 30 cm gap between two desks, students build a bridge using only one sheet of paper (20 cm × 30 cm) and 10 paper clips. A flat sheet immediately sags and collapses under its own weight. What folding technique gives paper the highest structural bending strength?',
      options: [
        { text: 'Folding the paper into accordion pleats (corrugation), which increases the vertical depth of the cross-section.', correct: true },
        { text: 'Rolling the paper into a tight flat square.', correct: false },
        { text: 'Tearing the paper into thin confetti strips.', correct: false },
        { text: 'Soaking the paper in water before placing it.', correct: false },
      ],
      learning_objective: 'Corrugation, second moment of area, and structural geometry in thin materials.',
      hint: 'Think about cardboard boxes: what is inside the walls of strong cardboard?',
      irt_a: 1.6,
      irt_b: -0.1,
      irt_c: 0.25,
      international_benchmark: 'FIRST LEGO League Junior Engineering Challenge',
    },
    {
      scenario_code: 'C03-ED-06',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'A model water turbine uses falling water to spin a paddle wheel that lifts a small weight. If the water tank height is raised from 20 cm to 80 cm above the wheel, how does the gravitational potential energy of the falling water change?',
      options: [
        { text: 'It quadruples (increases by a factor of 4), because potential energy is directly proportional to fall height ($PE = mgh$).', correct: true },
        { text: 'It doubles (increases by a factor of 2).', correct: false },
        { text: 'It remains unchanged because the volume of water is the same.', correct: false },
        { text: 'It decreases because water takes longer to reach the bottom.', correct: false },
      ],
      learning_objective: 'Gravitational potential energy scaling with height ($PE = mgh$).',
      hint: '80 cm is 4 times higher than 20 cm.',
      irt_a: 1.7,
      irt_b: 0.2,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary Science & Engineering Challenge',
    },

    // 4. Mathematical Reasoning (6 items)
    {
      scenario_code: 'C03-MR-01',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'A school garden has a rectangular vegetable patch that is 6 meters long and 4 meters wide. The class wants to build a wooden border along all four sides. What is the total perimeter of the patch?',
      options: [
        { text: '20 meters ($6 + 4 + 6 + 4 = 20$ m)', correct: true },
        { text: '24 meters ($6 \\times 4 = 24$ m)', correct: false },
        { text: '10 meters ($6 + 4 = 10$ m)', correct: false },
        { text: '16 meters', correct: false },
      ],
      learning_objective: 'Perimeter calculation of rectangles as sum of all four boundary sides.',
      hint: 'Add the lengths of all four outer edges.',
      irt_a: 1.1,
      irt_b: -1.8,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary Math 3A / US Common Core 3.MD.D.8',
    },
    {
      scenario_code: 'C03-MR-02',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'Maya baked 24 muffins. She gave 1/4 of them to her neighbor and divided the remaining muffins equally among 3 friends. How many muffins did each friend receive?',
      options: [
        { text: '6 muffins (24 - 6 = 18 remaining; 18 ÷ 3 = 6)', correct: true },
        { text: '8 muffins', correct: false },
        { text: '4 muffins', correct: false },
        { text: '5 muffins', correct: false },
      ],
      learning_objective: 'Multi-step arithmetic combining unit fractions and equal sharing division.',
      hint: 'First find 1/4 of 24, subtract that from 24, then divide what is left by 3.',
      irt_a: 1.25,
      irt_b: -1.3,
      irt_c: 0.25,
      international_benchmark: 'Kangaroo Math Benjamin Level / SASMO Grade 3',
    },
    {
      scenario_code: 'C03-MR-03',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'A clock shows 2:15 PM. If a train journey takes 2 hours and 50 minutes, what time will the train arrive at its destination?',
      options: [
        { text: '5:05 PM (2:15 + 2h = 4:15; 4:15 + 45m = 5:00; + 5m = 5:05 PM)', correct: true },
        { text: '4:65 PM', correct: false },
        { text: '5:15 PM', correct: false },
        { text: '4:55 PM', correct: false },
      ],
      learning_objective: 'Elapsed time addition with sexagesimal (base-60) minute rollover.',
      hint: 'There are 60 minutes in an hour, so adding 50 minutes to 15 minutes rolls past the next hour.',
      irt_a: 1.35,
      irt_b: -0.8,
      irt_c: 0.25,
      international_benchmark: 'TIMSS Grade 4 Mathematics',
    },
    {
      scenario_code: 'C03-MR-04',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'A mystery number has 3 digits: the hundreds digit is 4, the tens digit is double the hundreds digit, and the ones digit is 3 less than the tens digit. What is the mystery number?',
      options: [
        { text: '485 (Hundreds = 4, Tens = 8, Ones = 5)', correct: true },
        { text: '425', correct: false },
        { text: '488', correct: false },
        { text: '463', correct: false },
      ],
      learning_objective: 'Place value decoding and relational deductive constraints.',
      hint: 'Double of 4 is 8; 8 minus 3 is 5.',
      irt_a: 1.45,
      irt_b: -0.4,
      irt_c: 0.25,
      international_benchmark: 'Australian Mathematics Competition (AMC) Middle Primary',
    },
    {
      scenario_code: 'C03-MR-05',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'In a farmyard there are chickens (2 legs each) and rabbits (4 legs each). Counting heads gives 10 heads; counting feet gives 28 feet. How many rabbits are in the farmyard?',
      options: [
        { text: '4 rabbits (and 6 chickens: 4 × 4 + 6 × 2 = 16 + 12 = 28 feet)', correct: true },
        { text: '6 rabbits', correct: false },
        { text: '5 rabbits', correct: false },
        { text: '3 rabbits', correct: false },
      ],
      learning_objective: 'Simultaneous linear constraint problem solving via assumption heuristic.',
      hint: 'If all 10 animals were chickens, there would only be 20 legs. Each rabbit adds 2 extra legs.',
      irt_a: 1.6,
      irt_b: 0.0,
      irt_c: 0.25,
      international_benchmark: 'SASMO Primary 3 / Singapore Heuristic Problem Solving',
    },
    {
      scenario_code: 'C03-MR-06',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'How many triangles of any size are there in a large equilateral triangle divided into 4 small identical equilateral triangles by joining the midpoints of its three sides?',
      options: [
        { text: '5 triangles (4 small triangles + 1 large outer triangle)', correct: true },
        { text: '4 triangles', correct: false },
        { text: '6 triangles', correct: false },
        { text: '8 triangles', correct: false },
      ],
      learning_objective: 'Systematic geometric shape enumeration and nested figure counting.',
      hint: 'Count the small individual triangles first, and do not forget the large surrounding triangle.',
      irt_a: 1.65,
      irt_b: 0.3,
      irt_c: 0.25,
      international_benchmark: 'Kangaroo Math Ecolier / Bebras Junior',
    },

    // 5. Systems Thinking (6 items)
    {
      scenario_code: 'C03-ST-01',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'In a school garden ecosystem: Sunflowers provide seeds for sparrows, and sparrows are hunted by garden hawks. If a disease eliminates all the sparrows, what is the immediate expected effect on the hawks and the sunflowers?',
      options: [
        { text: 'Hawks will face a food shortage, while sunflower seeds will accumulate with fewer birds eating them.', correct: true },
        { text: 'Hawks will immediately start eating sunflower leaves.', correct: false },
        { text: 'Sunflowers will stop growing flowers entirely.', correct: false },
        { text: 'All organisms in the garden will double within one day.', correct: false },
      ],
      learning_objective: 'Linear trophic cascade and primary consumer disruption in simple food chains.',
      hint: 'Trace who eats whom: if the middle animal vanishes, what happens to the predator and the food source?',
      irt_a: 1.15,
      irt_b: -1.7,
      irt_c: 0.25,
      international_benchmark: 'UNESCO Primary Science Indicators / OECD PISA Primary',
    },
    {
      scenario_code: 'C03-ST-02',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'On a sunny day after rain, a large puddle on asphalt disappears by afternoon even though no drain exists. Where did the water in the puddle go?',
      options: [
        { text: 'The liquid water absorbed heat energy and evaporated into invisible water vapor gas in the atmosphere.', correct: true },
        { text: 'The asphalt soaked up all the water and turned into a solid sponge.', correct: false },
        { text: 'Car tires drank the water to stay cool.', correct: false },
        { text: 'The water was destroyed by sunlight.', correct: false },
      ],
      learning_objective: 'Hydrological cycle phase change and atmospheric water reservoir transfer.',
      hint: 'Water does not disappear from the universe; it changes into an invisible gas in the air.',
      irt_a: 1.25,
      irt_b: -1.4,
      irt_c: 0.25,
      international_benchmark: 'TIMSS Grade 4 Earth Science',
    },
    {
      scenario_code: 'C03-ST-03',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'A classroom has an aquarium with fish and live green plants. If the teacher moves the aquarium into a completely dark room for two weeks, why do the fish begin to struggle for breath even though they have food?',
      options: [
        { text: 'Without sunlight, plants cannot perform photosynthesis to produce dissolved oxygen for the fish to breathe.', correct: true },
        { text: 'Fish are afraid of the dark and stop swimming.', correct: false },
        { text: 'Water freezes solid in darkness within hours.', correct: false },
        { text: 'Fish food only dissolves when bright light shines on it.', correct: false },
      ],
      learning_objective: 'Interdependent closed-loop gas exchange (O2 and CO2) in aquatic ecosystems.',
      hint: 'Plants need light to make oxygen for fish to breathe underwater.',
      irt_a: 1.35,
      irt_b: -0.8,
      irt_c: 0.25,
      international_benchmark: 'US NGSS 5-LS2-1 Ecosystem Interdependence',
    },
    {
      scenario_code: 'C03-ST-04',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'A town builds a new asphalt parking lot where a grassy meadow used to be. During the next heavy thunderstorm, the street next to the parking lot floods severely. Why did replacing grass with asphalt cause flooding?',
      options: [
        { text: 'Grass and soil absorb and slow down rainwater infiltration, whereas impermeable asphalt forces all rainwater to rush immediately into the street.', correct: true },
        { text: 'Asphalt attracts more rain clouds from the sky.', correct: false },
        { text: 'Cars parked on the lot push water upward with their tires.', correct: false },
        { text: 'Asphalt melts in rainwater, blocking storm pipes.', correct: false },
      ],
      learning_objective: 'Surface permeability, storm runoff kinetics, and human-altered urban drainage systems.',
      hint: 'Water can soak into dirt and grass, but it rolls straight off smooth pavement.',
      irt_a: 1.45,
      irt_b: -0.4,
      irt_c: 0.25,
      international_benchmark: 'OECD PISA Environmental Systems / UNESCO SDG 11',
    },
    {
      scenario_code: 'C03-ST-05',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'A honeybee visits flowers to collect nectar, and pollen grains stick to its fuzzy body and transfer to the next flower. Both the bee and the flowering plant benefit. What systemic ecological relationship is this?',
      options: [
        { text: 'Mutualism: a symbiotic co-dependent feedback loop where both species enhance each other’s survival and reproduction.', correct: true },
        { text: 'Parasitism: where the bee steals resources and damages the flower.', correct: false },
        { text: 'Predation: where the flower captures and digests the bee.', correct: false },
        { text: 'Competition: where the bee and flower fight for the same sunlight.', correct: false },
      ],
      learning_objective: 'Symbiotic mutualism, plant-pollinator co-evolution, and positive ecological feedback.',
      hint: 'Both living things gain something essential: food for the bee, reproduction for the plant.',
      irt_a: 1.6,
      irt_b: 0.1,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary Science Olympiad / SASMO Junior',
    },
    {
      scenario_code: 'C03-ST-06',
      class_level: 3,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In a mechanical grandfather clock, a falling weight pulls a chain that turns gear wheels, but an escapement mechanism allows the gears to turn only one tooth every second with a swinging pendulum. What is the function of the escapement in this system?',
      options: [
        { text: 'It acts as a feedback governor, regulating the release of stored potential energy into precise, constant time intervals.', correct: true },
        { text: 'It winds the clock weight back up to the top automatically.', correct: false },
        { text: 'It stops the clock from making ticking sounds.', correct: false },
        { text: 'It creates electricity to power digital numbers.', correct: false },
      ],
      learning_objective: 'Systemic energy regulation, escapement governance, and clockwork mechanical feedback.',
      hint: 'Without this part, the weight would fall to the floor in one second and spin the hands wildly.',
      irt_a: 1.65,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'Cambridge Primary STEM / ISEC Systems Design',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // CLASS 4 (Grade 4 · Developmental Band 3-4) — 30 Unique Questions
    // ═════════════════════════════════════════════════════════════════════════
    // 1. Scientific Inquiry (6 items)
    {
      scenario_code: 'C04-SCI-01',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'A student places 10 bean seeds on wet cotton in a warm room (22°C) and 10 identical seeds on wet cotton inside a cold refrigerator (4°C). After 5 days, all 10 seeds in the warm room sprouted roots, while none of the seeds in the refrigerator sprouted. What was the independent variable in this test?',
      options: [
        { text: 'The temperature of the environment.', correct: true },
        { text: 'The amount of wet cotton.', correct: false },
        { text: 'The number of sprouted roots.', correct: false },
        { text: 'The species of bean seeds.', correct: false },
      ],
      learning_objective: 'Identification of manipulated independent variables in seed germination experiments.',
      hint: 'The independent variable is the one condition that the experimenter deliberately changed between the two groups.',
      irt_a: 1.2,
      irt_b: -1.6,
      irt_c: 0.25,
      international_benchmark: 'US NGSS 4-LS1-1 / Singapore Primary 4',
    },
    {
      scenario_code: 'C04-SCI-02',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'A student shines a narrow beam of flashlight onto three materials: clear plastic wrap, frosted wax paper, and thick cardboard. The plastic allows light to pass clearly; the wax paper scatters light into a soft blur; the cardboard blocks light completely and casts a dark shadow. How are these three materials classified?',
      options: [
        { text: 'Transparent (clear plastic), Translucent (wax paper), and Opaque (cardboard).', correct: true },
        { text: 'Reflective, Refractive, and Absorptive.', correct: false },
        { text: 'Magnetic, Conductive, and Insulating.', correct: false },
        { text: 'Solid, Liquid, and Gas.', correct: false },
      ],
      learning_objective: 'Optical transmission properties: transparent, translucent, and opaque categorization.',
      hint: 'Transparent means see-through; translucent scatters light; opaque blocks all light.',
      irt_a: 1.25,
      irt_b: -1.3,
      irt_c: 0.25,
      international_benchmark: 'Cambridge Primary Science Stage 4',
    },
    {
      scenario_code: 'C04-SCI-03',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'A student plucks a stretched guitar string and listens to the pitch. When the string is tightened using the tuning peg, the pitch of the sound becomes higher. Why does tightening the string raise the pitch?',
      options: [
        { text: 'Greater tension makes the string vibrate with higher frequency (more vibrations per second).', correct: true },
        { text: 'Tension makes the sound travel faster through the wooden body.', correct: false },
        { text: 'Tight strings absorb more air molecules.', correct: false },
        { text: 'Tension makes the string longer and heavier.', correct: false },
      ],
      learning_objective: 'Sound wave production, vibration frequency, and string tension dynamics.',
      hint: 'Pitch depends on how fast an object vibrates back and forth.',
      irt_a: 1.35,
      irt_b: -0.9,
      irt_c: 0.25,
      international_benchmark: 'TIMSS Grade 4 Physical Science',
    },
    {
      scenario_code: 'C04-SCI-04',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'Three soil samples (Sandy Soil, Garden Loam, and Heavy Clay) are placed in funnels. 100 mL of water is poured onto each. After 5 minutes, 85 mL dripped through the sand, 45 mL through the loam, and only 10 mL through the clay. Which soil is best suited for plants that need moist soil without drying out quickly?',
      options: [
        { text: 'Garden loam, because it retains moderate moisture while still allowing adequate drainage.', correct: true },
        { text: 'Sandy soil, because all the water quickly drains away.', correct: false },
        { text: 'Clay, because it creates waterlogged puddles that suffocate root oxygen.', correct: false },
        { text: 'None of the soils can support plant roots.', correct: false },
      ],
      learning_objective: 'Soil porosity, permeability, and water retention capacity.',
      hint: 'Loam balances water retention with drainage so roots neither drown nor dry out.',
      irt_a: 1.4,
      irt_b: -0.5,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary 4 Science Syllabus',
    },
    {
      scenario_code: 'C04-SCI-05',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'An Arctic hare has brown fur during the warm summer months and sheds its coat to grow pure white fur in the winter. What type of adaptation is this and what primary survival advantage does it confer?',
      options: [
        { text: 'A seasonal camouflage adaptation that conceals the hare from predators against snow and rocky ground.', correct: true },
        { text: 'A behavioral adaptation to attract migrating birds.', correct: false },
        { text: 'A disease caused by cold winter wind.', correct: false },
        { text: 'An adaptation to absorb maximum sunlight during dark winter days.', correct: false },
      ],
      learning_objective: 'Seasonal physiological camouflage and natural selection predator-prey adaptations.',
      hint: 'White fur blends in with snow, while brown fur blends in with summer dirt and rocks.',
      irt_a: 1.55,
      irt_b: -0.1,
      irt_c: 0.25,
      international_benchmark: 'Australian Science Innovations Primary Challenge',
    },
    {
      scenario_code: 'C04-SCI-06',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'A syringe with its tip sealed by a rubber stopper contains 50 mL of air. When the plunger is pushed hard with a thumb, the air compresses to 30 mL. When the thumb is released, the plunger springs back to 50 mL. What does this demonstrate about gases compared to liquids?',
      options: [
        { text: 'Gas molecules have large empty spaces between them and can be compressed, exerting pressure that pushes back.', correct: true },
        { text: 'Air molecules shrink in size when compressed.', correct: false },
        { text: 'Air destroyed its own mass and then recreated it.', correct: false },
        { text: 'Liquids can be compressed much more easily than gases.', correct: false },
      ],
      learning_objective: 'Kinetic particle model of gases, compressibility, and pneumatic elasticity.',
      hint: 'Particles in a gas are far apart with lots of empty space between them.',
      irt_a: 1.65,
      irt_b: 0.25,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary Science Olympiad (SPSO)',
    },

    // 2. Computational Thinking (6 items)
    {
      scenario_code: 'C04-CT-01',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'A robot is positioned at (0, 0) facing East on a 2D coordinate grid. It executes: [FORWARD 4, TURN LEFT 90°, FORWARD 3]. How far is the robot in a straight line from its starting point (0, 0)?',
      options: [
        { text: '5 units ($3^2 + 4^2 = 9 + 16 = 25 = 5^2$)', correct: true },
        { text: '7 units ($4 + 3 = 7$)', correct: false },
        { text: '1 unit ($4 - 3 = 1$)', correct: false },
        { text: '12 units ($4 \\times 3 = 12$)', correct: false },
      ],
      learning_objective: 'Grid navigation decomposition and Euclidean 3-4-5 right triangle distance.',
      hint: 'Think of the 3-4-5 right triangle: 4 units East, 3 units North.',
      irt_a: 1.25,
      irt_b: -1.5,
      irt_c: 0.25,
      international_benchmark: 'Bebras Computational Thinking Grade 4',
    },
    {
      scenario_code: 'C04-CT-02',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'A student writes a program to draw a square with a pen: [REPEAT 4 TIMES: {MOVE 50 STEPS, TURN RIGHT X DEGREES}]. What angle X in degrees must the pen turn at each corner to complete a closed square?',
      options: [
        { text: '90 degrees (total turning angle = 360° / 4 sides = 90°)', correct: true },
        { text: '45 degrees', correct: false },
        { text: '180 degrees', correct: false },
        { text: '60 degrees', correct: false },
      ],
      learning_objective: 'Total turtle geometry turning angle ($360^\\circ / N$) and polygon drawing loops.',
      hint: 'A full circle turn is 360 degrees. A square has 4 equal corners.',
      irt_a: 1.3,
      irt_b: -1.2,
      irt_c: 0.25,
      international_benchmark: 'Logo / Scratch Turtle Geometry CSTA Standards',
    },
    {
      scenario_code: 'C04-CT-03',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'Three light switches [A, B, C] control a vault door. The door opens IF (Switch A is ON OR Switch B is ON) AND Switch C is ON. Which switch combination successfully opens the door?',
      options: [
        { text: 'Switch A is ON, Switch B is OFF, Switch C is ON.', correct: true },
        { text: 'Switch A is ON, Switch B is ON, Switch C is OFF.', correct: false },
        { text: 'Switch A is OFF, Switch B is OFF, Switch C is ON.', correct: false },
        { text: 'All three switches are OFF.', correct: false },
      ],
      learning_objective: 'Composite Boolean expressions with parenthesized OR and AND precedence.',
      hint: 'Switch C must be ON, and at least one of A or B must be ON.',
      irt_a: 1.4,
      irt_b: -0.7,
      irt_c: 0.25,
      international_benchmark: 'Oxford Computing Challenge Primary',
    },
    {
      scenario_code: 'C04-CT-04',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'A list of names is sorted alphabetically: [Alice, Ben, Chloe, Daniel, Emma, Felix, Grace, Henry]. If you use Binary Search to find "Felix", which name is inspected FIRST?',
      options: [
        { text: 'Daniel or Emma (the middle element of the 8 names).', correct: true },
        { text: 'Alice (the first name in the list).', correct: false },
        { text: 'Henry (the last name in the list).', correct: false },
        { text: 'Grace (the neighbor of Felix).', correct: false },
      ],
      learning_objective: 'Binary search middle pivot selection on ordered sequences.',
      hint: 'Binary search always looks right in the middle first, cutting the search area in half.',
      irt_a: 1.45,
      irt_b: -0.4,
      irt_c: 0.25,
      international_benchmark: 'Bebras International Competition Grade 4-5',
    },
    {
      scenario_code: 'C04-CT-05',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'A message is encoded using a Caesar cipher shift of +3 (A becomes D, B becomes E, etc.). What is the original decrypted word for the coded message "FDW"?',
      options: [
        { text: 'CAT (F - 3 = C, D - 3 = A, W - 3 = T)', correct: true },
        { text: 'DOG', correct: false },
        { text: 'BAT', correct: false },
        { text: 'HAT', correct: false },
      ],
      learning_objective: 'Modular arithmetic substitution cryptography and reverse cipher mapping.',
      hint: 'Shift each letter backward 3 places in the alphabet.',
      irt_a: 1.6,
      irt_b: 0.1,
      irt_c: 0.25,
      international_benchmark: 'USA Computing Olympiad (USACO) Elementary / Bebras',
    },
    {
      scenario_code: 'C04-CT-06',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'A queue data structure operates on First-In, First-Out (FIFO). The following events occur: ENQUEUE(Apple), ENQUEUE(Banana), ENQUEUE(Cherry), DEQUEUE(), ENQUEUE(Date), DEQUEUE(). Which item is now at the front of the queue?',
      options: [
        { text: 'Cherry (Apple was removed first, Banana was removed second; Cherry is now front).', correct: true },
        { text: 'Apple', correct: false },
        { text: 'Date', correct: false },
        { text: 'Banana', correct: false },
      ],
      learning_objective: 'Queue FIFO buffer state transitions and head-tail pointer tracking.',
      hint: 'The first item in line leaves first, like people waiting for a bus.',
      irt_a: 1.65,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'Bebras Benjamin Olympiad',
    },

    // 3. Engineering Design (6 items)
    {
      scenario_code: 'C04-ED-01',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'A student wants to keep hot soup warm inside a lunchbox for 4 hours. They test three materials to wrap around the metal thermos: aluminum foil, bubble wrap with trapped air, and wet paper towel. Which material will keep the soup warmest, and why?',
      options: [
        { text: 'Bubble wrap, because trapped stagnant air is a poor conductor of thermal energy.', correct: true },
        { text: 'Wet paper towel, because water cools objects rapidly.', correct: false },
        { text: 'Aluminum foil alone, because metals conduct heat away quickly.', correct: false },
        { text: 'All materials keep soup at the exact same temperature.', correct: false },
      ],
      learning_objective: 'Thermal insulation, air pocket conduction resistance, and material thermal conductivity.',
      hint: 'Air that cannot move is one of the best thermal insulators in nature.',
      irt_a: 1.2,
      irt_b: -1.5,
      irt_c: 0.25,
      international_benchmark: 'US NGSS 4-PS3-2 / Cambridge Primary DT',
    },
    {
      scenario_code: 'C04-ED-02',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'A wheelbarrow has its wheel at the front, the heavy load in the middle tray, and the handles at the back where the gardener lifts. What class of simple machine is a wheelbarrow?',
      options: [
        { text: 'A second-class lever (Load is located between the Fulcrum and the Effort).', correct: true },
        { text: 'A first-class lever (Fulcrum in the middle).', correct: false },
        { text: 'A third-class lever (Effort in the middle).', correct: false },
        { text: 'An inclined plane.', correct: false },
      ],
      learning_objective: 'Classification of lever systems by relative positions of fulcrum, load, and effort.',
      hint: 'The wheel on the ground is the fulcrum, the dirt is in the middle, and your hands lift the ends.',
      irt_a: 1.3,
      irt_b: -1.2,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary 4 Science / UK Key Stage 2',
    },
    {
      scenario_code: 'C04-ED-03',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'An engineer designs a water filtration column for muddy river water. In what order from top to bottom should the filtration layers be arranged to prevent clogging?',
      options: [
        { text: 'Top: Coarse pebbles $\\to$ Middle: Fine sand $\\to$ Bottom: Charcoal/Cloth filter.', correct: true },
        { text: 'Top: Fine cloth $\\to$ Middle: Coarse pebbles $\\to$ Bottom: Fine sand.', correct: false },
        { text: 'Top: Charcoal $\\to$ Middle: Pebbles $\\to$ Bottom: Sand.', correct: false },
        { text: 'All materials should be blended into a muddy paste.', correct: false },
      ],
      learning_objective: 'Particle size gradient filtration, sediment fractionation, and filter clogging prevention.',
      hint: 'Trap large particles first so they do not block the fine mesh below.',
      irt_a: 1.4,
      irt_b: -0.7,
      irt_c: 0.25,
      international_benchmark: 'Project Lead The Way (PLTW) Grade 4',
    },
    {
      scenario_code: 'C04-ED-04',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'A model pinewood derby racecar travels down a 5-meter ramp. To reduce aerodynamic drag without changing the car’s weight, what shape should the car body have?',
      options: [
        { text: 'A streamlined teardrop wedge with smooth curved contours that guide airflow with minimal wake turbulence.', correct: true },
        { text: 'A wide, tall rectangular block with flat vertical front faces.', correct: false },
        { text: 'A jagged zigzag shape with sharp rough edges.', correct: false },
        { text: 'A flat hollow box with open front scoops.', correct: false },
      ],
      learning_objective: 'Aerodynamic streamlining, form drag reduction, and fluid boundary displacement.',
      hint: 'Look at birds and fast fish: their bodies taper smoothly to cut through air and water.',
      irt_a: 1.45,
      irt_b: -0.4,
      irt_c: 0.25,
      international_benchmark: 'Engineering is Elementary (EiE) Boston Museum of Science',
    },
    {
      scenario_code: 'C04-ED-05',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'A fixed single pulley hangs from a ceiling. A student pulls down on the rope with 50 N of force to lift a 50 N bucket of bricks. The student then switches to a movable pulley system with two rope segments supporting the load. What force is now needed to lift the bucket?',
      options: [
        { text: '25 N (the two supporting rope segments share the load, giving a mechanical advantage of 2).', correct: true },
        { text: '50 N (force never changes with pulleys).', correct: false },
        { text: '100 N (movable pulleys double the weight).', correct: false },
        { text: '10 N.', correct: false },
      ],
      learning_objective: 'Movable pulley mechanical advantage ($MA = 2$) and tension load distribution.',
      hint: 'Count how many vertical rope strands are directly holding up the hanging load.',
      irt_a: 1.6,
      irt_b: 0.1,
      irt_c: 0.25,
      international_benchmark: 'FIRST LEGO League Design Challenge Grade 4',
    },
    {
      scenario_code: 'C04-ED-06',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'A model wind turbine has 3 lightweight blades. When the blade angle (pitch) is 0° flat against the wind, the turbine will not spin. When tilted slightly to 15°, it spins rapidly and generates electricity. Why does an angled blade spin in moving wind?',
      options: [
        { text: 'The angled blade deflects moving air sideways, generating an aerodynamic lift force that pushes the blade along its circular path.', correct: true },
        { text: 'Wind only blows on blades that have colored tape.', correct: false },
        { text: 'Angled blades become lighter than air.', correct: false },
        { text: 'Air creates suction behind flat blades that stops Earth from turning.', correct: false },
      ],
      learning_objective: 'Aerodynamic blade pitch, lift-induced rotational torque, and wind energy harvesting.',
      hint: 'Think of how sticking your angled hand out of a moving car window pushes your hand upward.',
      irt_a: 1.65,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'Clean Energy Engineering Challenge Primary',
    },

    // 4. Mathematical Reasoning (6 items)
    {
      scenario_code: 'C04-MR-01',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'A rectangular playground has a length of 15 meters and an area of 90 square meters. What is the width of the playground?',
      options: [
        { text: '6 meters ($90 \\div 15 = 6$ m)', correct: true },
        { text: '75 meters ($90 - 15 = 75$ m)', correct: false },
        { text: '12 meters', correct: false },
        { text: '8 meters', correct: false },
      ],
      learning_objective: 'Inverse relationship between area and linear dimensions in rectangles ($A = l \\times w$).',
      hint: 'Area = Length × Width. Divide the total area by the length.',
      irt_a: 1.2,
      irt_b: -1.6,
      irt_c: 0.25,
      international_benchmark: 'Singapore Primary Math 4A / US Common Core 4.MD.A.3',
    },
    {
      scenario_code: 'C04-MR-02',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'Which fraction is the GREATEST among the following: 3/4, 5/8, 1/2, and 7/12?',
      options: [
        { text: '3/4 (converting to 24ths: 3/4 = 18/24, 5/8 = 15/24, 1/2 = 12/24, 7/12 = 14/24)', correct: true },
        { text: '5/8', correct: false },
        { text: '7/12', correct: false },
        { text: '1/2', correct: false },
      ],
      learning_objective: 'Fraction comparison using common denominators (LCM).',
      hint: 'Find a common denominator like 24 to compare the numerators easily.',
      irt_a: 1.25,
      irt_b: -1.2,
      irt_c: 0.25,
      international_benchmark: 'TIMSS Grade 4 Mathematics',
    },
    {
      scenario_code: 'C04-MR-03',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'A train departs City A with 120 passengers. At the first stop, 1/3 of the passengers get off and 15 new passengers get on. How many passengers are on the train now?',
      options: [
        { text: '95 passengers (120 - 40 = 80; 80 + 15 = 95)', correct: true },
        { text: '85 passengers', correct: false },
        { text: '105 passengers', correct: false },
        { text: '75 passengers', correct: false },
      ],
      learning_objective: 'Multi-step arithmetic combining fraction reduction and additive adjustments.',
      hint: '1/3 of 120 is 40. Subtract 40, then add 15.',
      irt_a: 1.35,
      irt_b: -0.7,
      irt_c: 0.25,
      international_benchmark: 'Kangaroo Math Ecolier / SASMO Grade 4',
    },
    {
      scenario_code: 'C04-MR-04',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'How many lines of symmetry does a regular hexagon have?',
      options: [
        { text: '6 lines of symmetry (3 passing through opposite vertices, 3 passing through opposite edge midpoints).', correct: true },
        { text: '3 lines of symmetry', correct: false },
        { text: '8 lines of symmetry', correct: false },
        { text: '4 lines of symmetry', correct: false },
      ],
      learning_objective: 'Rotational and reflectional symmetry axes of regular polygons.',
      hint: 'A regular polygon with N sides has N lines of symmetry.',
      irt_a: 1.45,
      irt_b: -0.4,
      irt_c: 0.25,
      international_benchmark: 'Cambridge Primary Stage 4 Geometry',
    },
    {
      scenario_code: 'C04-MR-05',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'The perimeter of a rectangle is 36 cm. If its length is twice as long as its width ($l = 2w$), what is the AREA of the rectangle in square centimeters?',
      options: [
        { text: '72 cm² ($2(w + 2w) = 6w = 36 \\implies w = 6$ cm, $l = 12$ cm; Area = $12 \\times 6 = 72$ cm²)', correct: true },
        { text: '64 cm²', correct: false },
        { text: '81 cm²', correct: false },
        { text: '54 cm²', correct: false },
      ],
      learning_objective: 'Algebraic modeling of geometric perimeter to solve for non-linear area.',
      hint: 'Perimeter is 2 lengths + 2 widths. If length is 2 widths, then Perimeter = 6 widths.',
      irt_a: 1.6,
      irt_b: 0.1,
      irt_c: 0.25,
      international_benchmark: 'American Mathematics Competitions (AMC 8) Entry / SASMO',
    },
    {
      scenario_code: 'C04-MR-06',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'A sequence of numbers starts with 3, and each following term is calculated by doubling the previous number and subtracting 1: [3, 5, 9, 17, 33, ...]. What is the 7th term in this sequence?',
      options: [
        { text: '129 (6th term: $33 \\times 2 - 1 = 65$; 7th term: $65 \\times 2 - 1 = 129$)', correct: true },
        { text: '127', correct: false },
        { text: '131', correct: false },
        { text: '65', correct: false },
      ],
      learning_objective: 'Recursive sequence extrapolation ($a_n = 2a_{n-1} - 1 = 2^{n-1} + 1$).',
      hint: 'Notice that the terms are: 2^1 + 1, 2^2 + 1, 2^3 + 1, 2^4 + 1...',
      irt_a: 1.65,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'China Primary Math Olympiad / Singapore RMO Junior',
    },

    // 5. Systems Thinking (6 items)
    {
      scenario_code: 'C04-ST-01',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'In a freshwater pond, green algae provide oxygen and food for water snails, and snails keep the water clear by grazing algae. If excess lawn fertilizer washes into the pond during storms, algae grows in massive green mats that block sunlight, die, and decay, consuming all the oxygen. What is this ecological process called?',
      options: [
        { text: 'Eutrophication: nutrient pollution causing an algal boom that depletes dissolved oxygen.', correct: true },
        { text: 'Photosynthesis acceleration.', correct: false },
        { text: 'Thermal stratification.', correct: false },
        { text: 'Erosion sediment buffering.', correct: false },
      ],
      learning_objective: 'Agricultural nutrient runoff, algal blooms, and dissolved oxygen collapse in aquatic systems.',
      hint: 'Too much fertilizer in water causes algae to explode in population, suffocating the pond.',
      irt_a: 1.25,
      irt_b: -1.5,
      irt_c: 0.25,
      international_benchmark: 'UNESCO Education for Sustainable Development (ESD) / NGSS 4-ESS3',
    },
    {
      scenario_code: 'C04-ST-02',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'A home heating system has a wall thermostat set to 20°C. When the indoor temperature drops to 19°C, the furnace turns ON until the room warms to 21°C, then turns OFF. What type of control dynamic is this?',
      options: [
        { text: 'A negative (balancing) feedback loop that counteracts temperature deviations to maintain homeostatic equilibrium.', correct: true },
        { text: 'A positive reinforcing loop that keeps making the room hotter forever.', correct: false },
        { text: 'An open-loop system with zero feedback sensors.', correct: false },
        { text: 'A random probability generator.', correct: false },
      ],
      learning_objective: 'Negative feedback loop mechanisms and homeostatic set-point regulation.',
      hint: 'A balancing loop acts like a brake to bring things back to the target set-point.',
      irt_a: 1.3,
      irt_b: -1.1,
      irt_c: 0.25,
      international_benchmark: 'MIT System Dynamics in K-12 / PISA Systems Thinking',
    },
    {
      scenario_code: 'C04-ST-03',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'When a new bypass road is built around a busy market town, traffic downtown drops by 40% for the first month. However, within two years, downtown traffic is just as crowded as before because new shopping plazas were built along the bypass road, attracting 1,000 new commuters. What systems principle explains this?',
      options: [
        { text: 'Induced demand and unintended urban feedback: expanding transit capacity alters land use and attracts new vehicle trips until congestion returns.', correct: true },
        { text: 'Cars multiply on their own when new roads are paved.', correct: false },
        { text: 'The old road shrank in size over time.', correct: false },
        { text: 'Traffic lights automatically stay red longer on older streets.', correct: false },
      ],
      learning_objective: 'Induced demand, land-use transportation feedback loops, and policy resistance.',
      hint: 'When travel becomes easier, more people decide to drive or build businesses there.',
      irt_a: 1.4,
      irt_b: -0.6,
      irt_c: 0.25,
      international_benchmark: 'OECD PISA Urban Systems / UN SDG 11',
    },
    {
      scenario_code: 'C04-ST-04',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In a mountain forest, woodpeckers drill holes into dead trees for nests. After woodpeckers leave, bluebirds, bats, and flying squirrels use the empty cavities to raise their young. Why is the woodpecker classified as an "ecosystem engineer"?',
      options: [
        { text: 'It creates essential physical shelter habitats that other species depend upon for reproduction.', correct: true },
        { text: 'It constructs solar panels on tree trunks.', correct: false },
        { text: 'It eats more trees than any other animal.', correct: false },
        { text: 'It controls the local air temperature by flapping its wings.', correct: false },
      ],
      learning_objective: 'Ecosystem engineers, keystone niche creation, and multi-species habitat dependency.',
      hint: 'An ecosystem engineer changes the physical environment in a way that builds homes for other creatures.',
      irt_a: 1.45,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'US NGSS 4-LS1 / Cambridge Primary Science',
    },
    {
      scenario_code: 'C04-ST-05',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'A municipal water reservoir supplies a city of 50,000 residents. During a dry summer month, the city uses 10,000 m³ of water daily, while river inflow is only 6,000 m³ daily. If the reservoir holds 120,000 m³ of usable storage, in how many days will the reservoir run completely dry without rain?',
      options: [
        { text: '30 days (net loss rate = 10,000 - 6,000 = 4,000 m³/day; 120,000 ÷ 4,000 = 30 days).', correct: true },
        { text: '12 days', correct: false },
        { text: '20 days', correct: false },
        { text: '40 days', correct: false },
      ],
      learning_objective: 'Stock-and-flow dynamic balance: Net change = Inflow - Outflow.',
      hint: 'Calculate how much water is lost every day (Outflow minus Inflow), then divide the total storage by that daily loss.',
      irt_a: 1.6,
      irt_b: 0.1,
      irt_c: 0.25,
      international_benchmark: 'MIT System Dynamics K-12 Stock and Flow Modeling',
    },
    {
      scenario_code: 'C04-ST-06',
      class_level: 4,
      developmental_band: '3-4',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In the Arctic tundra, warmer summer temperatures melt white reflective sea ice, exposing dark ocean water underneath. Dark water absorbs 90% of solar radiation (compared to white ice reflecting 80%), causing the water to warm further and melt even more ice. What systemic dynamic does this "ice-albedo feedback" illustrate?',
      options: [
        { text: 'A reinforcing (positive) feedback loop: the effect amplifies the initial warming trigger, accelerating system state change.', correct: true },
        { text: 'A balancing (negative) feedback loop that restores ice cover automatically.', correct: false },
        { text: 'A closed linear system with zero energy exchange.', correct: false },
        { text: 'An isolated chemical reaction that creates ozone.', correct: false },
      ],
      learning_objective: 'Reinforcing positive feedback loops and planetary albedo climate dynamics.',
      hint: 'Does melting ice lead to more melting or does it stop the melting? If it accelerates the change, it is positive feedback.',
      irt_a: 1.65,
      irt_b: 0.4,
      irt_c: 0.25,
      international_benchmark: 'PISA 2025 Science / UNESCO Climate Science Indicators',
    },
  ];
}
