import type { ScenarioRecord } from './types';

export function getBand7_8Scenarios(): ScenarioRecord[] {
  return [
    // ═════════════════════════════════════════════════════════════════════════
    // CLASS 7 (Grade 7 · Developmental Band 7-8) - 30 Unique Questions
    // ═════════════════════════════════════════════════════════════════════════

    // 1. Scientific Inquiry (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C07-SCI-01',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'In a cellular biology lab, an epidermal onion cell is mounted on a microscope slide in a 10% NaCl hypertonic saline solution. Under 400× magnification, the cytoplasm and cell membrane shrink away from the rigid cell wall (plasmolysis). What osmotic mechanism causes this cellular dehydration?',
      options: [
        { text: 'Water diffuses down its chemical potential gradient across the selectively permeable membrane from higher water concentration inside the vacuole to lower water concentration outside.', correct: true },
        { text: 'Sodium and chloride ions rapidly enter the nucleus, chemically destroying the cytoplasm.', correct: false },
        { text: 'The cell wall contracts mechanically, crushing the cell membrane like a vice.', correct: false },
        { text: 'The salt solution extracts atmospheric oxygen, causing anaerobic cell suffocation.', correct: false },
      ],
      learning_objective: 'Osmosis across selectively permeable plant cell membranes, plasmolysis, and water potential gradients.',
      hint: 'Remember that water moves from an area of lower solute concentration (higher free water) to higher solute concentration.',
      irt_a: 1.3,
      irt_b: -0.6,
      irt_c: 0.25,
      international_benchmark: 'TIMSS 2023 Grade 8 Science / Cambridge Lower Secondary Stage 8',
    },
    {
      scenario_code: 'C07-SCI-02',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'A cart with mass m = 2.0 kg moves along a frictionless track at velocity v = 3.0 m/s. It collides head-on with a stationary cart of mass M = 4.0 kg and latches together in a completely inelastic collision. Using the Law of Conservation of Linear Momentum, what is the final combined velocity of both carts?',
      options: [
        { text: '1.0 m/s (Total initial momentum = 2.0 kg × 3.0 m/s = 6.0 kg·m/s; Total mass = 2.0 + 4.0 = 6.0 kg; v_final = 6.0 / 6.0 = 1.0 m/s).', correct: true },
        { text: '1.5 m/s (dividing initial velocity by 2).', correct: false },
        { text: '0.5 m/s (assuming kinetic energy is perfectly conserved instead of momentum).', correct: false },
        { text: '3.0 m/s (momentum stays identical so velocity cannot change).', correct: false },
      ],
      learning_objective: 'Conservation of linear momentum in completely inelastic collisions (m₁v₁ + m₂v₂ = (m₁+m₂)v_f).',
      hint: 'Momentum before collision equals momentum after collision: p_initial = m₁·v₁ = (m₁ + m₂)·v_final.',
      irt_a: 1.35,
      irt_b: -0.4,
      irt_c: 0.25,
      international_benchmark: 'NGSS MS-PS2-1 / Singapore Lower Secondary Science Physics',
    },
    {
      scenario_code: 'C07-SCI-03',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'A chemistry student bubbles carbon dioxide gas through an aqueous solution of calcium hydroxide [Ca(OH)₂, limewater]. Initially, the solution turns cloudy with a white precipitate. However, as the student continues bubbling excess CO₂ for 10 minutes, the cloudy precipitate completely dissolves, leaving the solution clear again. What chemical reaction explains this redissolution?',
      options: [
        { text: 'Insoluble calcium carbonate (CaCO₃) reacts with excess aqueous CO₂ and H₂O to form soluble calcium bicarbonate [Ca(HCO₃)₂].', correct: true },
        { text: 'Excess carbon dioxide creates pure nitric acid that oxidizes calcium into metallic vapor.', correct: false },
        { text: 'The precipitate settled to the bottom and became completely transparent due to optical refraction.', correct: false },
        { text: 'The solution reached its boiling point, decomposing calcium carbonate into calcium metal and oxygen.', correct: false },
      ],
      learning_objective: 'Reversible chemical reactions, carbonate-bicarbonate equilibria, and geological karst cave formation chemistry.',
      hint: 'This is the exact same chemical process responsible for rainwater dissolving limestone to carve out underground caves and stalactites.',
      irt_a: 1.45,
      irt_b: 0.0,
      irt_c: 0.25,
      international_benchmark: 'TIMSS 2023 Grade 8 Chemistry / Royal Society of Chemistry Chemistry Olympiad Prep',
    },
    {
      scenario_code: 'C07-SCI-04',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'An astrobiologist investigates extremophiles in hydrothermal vents. They isolate a hyperthermophilic archaeon that thrives at 105°C and 250 atmospheres of hydrostatic pressure. When analyzed biochemically, which molecular structural adaptation uniquely stabilizes the cell membrane against thermal disintegration?',
      options: [
        { text: 'Ether-linked isoprenoid lipids forming a rigid monolayer membrane that prevents thermal delamination and fluidity loss at extreme temperatures.', correct: true },
        { text: 'Membranes composed exclusively of liquid unsaturated fatty acids with double bonds.', correct: false },
        { text: 'A complete absence of any cell membrane, exposing the naked naked DNA directly to superheated water.', correct: false },
        { text: 'Cellulose cell walls reinforced with metallic aluminum foil.', correct: false },
      ],
      learning_objective: 'Archaea membrane biochemistry, ether vs. ester linkages, lipid monolayers, and extremophile structural adaptations.',
      hint: 'Unlike bacteria and eukaryotes that have ester-linked lipid bilayers, archaea frequently utilize branched ether-linked monolayer lipids for extreme thermal stability.',
      irt_a: 1.5,
      irt_b: 0.2,
      irt_c: 0.25,
      international_benchmark: 'USABO Foundation / International Biology Olympiad Junior Division',
    },
    {
      scenario_code: 'C07-SCI-05',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'A mass-spring oscillator on a frictionless horizontal plane has spring constant k = 200 N/m and mass m = 0.5 kg. The mass is pulled 0.10 m from equilibrium and released from rest. What is the maximum speed of the mass as it passes through the equilibrium point, and what is its oscillation frequency?',
      options: [
        { text: 'v_max = 2.0 m/s (using ½kA² = ½mv² → v = A√(k/m) = 0.10 × √(200/0.5) = 0.10 × 20 = 2.0 m/s); frequency f = (1/2π)√(k/m) ≈ 3.18 Hz.', correct: true },
        { text: 'v_max = 4.0 m/s; frequency f = 20 Hz.', correct: false },
        { text: 'v_max = 0.20 m/s; frequency f = 0.5 Hz.', correct: false },
        { text: 'v_max = 1.0 m/s; frequency f = 1.0 Hz.', correct: false },
      ],
      learning_objective: 'Simple harmonic motion (SHM), mechanical energy conservation (potential to kinetic), angular frequency (ω = √(k/m)).',
      hint: 'All elastic potential energy stored at maximum amplitude (½kA²) converts completely into kinetic energy (½mv²) at the equilibrium point.',
      irt_a: 1.6,
      irt_b: 0.5,
      irt_c: 0.25,
      international_benchmark: 'IJSO Physics / F=ma Contest Preparation',
    },
    {
      scenario_code: 'C07-SCI-06',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'In a photoelectric effect apparatus, monochromatic ultraviolet light of wavelength λ = 250 nm illuminates a clean cesium cathode (work function Φ = 2.14 eV). Taking Planck’s constant h = 4.136 × 10⁻¹⁵ eV·s and c = 3.0 × 10⁸ m/s, what is the maximum kinetic energy (K_max) of the ejected photoelectrons, and what stopping voltage (V_stop) is required to reduce photocurrent to zero?',
      options: [
        { text: 'Photon energy E = hc/λ = (1240 eV·nm)/250 nm = 4.96 eV; K_max = 4.96 - 2.14 = 2.82 eV; Stopping potential V_stop = 2.82 Volts.', correct: true },
        { text: 'Photon energy E = 2.14 eV; K_max = 0 eV; no photoelectrons are emitted because wavelength is too short.', correct: false },
        { text: 'K_max = 7.10 eV; V_stop = 7.10 V (adding photon energy to the work function).', correct: false },
        { text: 'K_max = 1.41 eV; V_stop = 0.50 V.', correct: false },
      ],
      learning_objective: 'Einstein’s photoelectric equation (K_max = hf - Φ), photon quantization, threshold frequency, and stopping potential.',
      hint: 'Use the handy shortcut: E(eV) ≈ 1240 / λ(nm). Then subtract the cathode’s work function Φ to find K_max in electron-volts.',
      irt_a: 1.7,
      irt_b: 0.75,
      irt_c: 0.25,
      international_benchmark: 'IPhO Foundation / European Physics Olympiad Junior Division',
    },

    // 2. Computational Thinking (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C07-COM-01',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'A circular queue data structure of capacity 5 uses pointers `head = 2` and `tail = 4`. The queue currently holds 3 elements. If an algorithm enqueues two new elements and then dequeues one element, what are the updated values of `head` and `tail` using modular arithmetic (`pointer = (pointer + 1) mod 5`)?',
      options: [
        { text: 'head = 3, tail = 1 (enqueue 1st → tail becomes 0; enqueue 2nd → tail becomes 1; dequeue → head becomes (2+1) mod 5 = 3).', correct: true },
        { text: 'head = 4, tail = 6 (ignoring circular wrap-around array limits).', correct: false },
        { text: 'head = 1, tail = 2 (resetting both pointers back to the start).', correct: false },
        { text: 'head = 0, tail = 4 (overwriting the underlying memory buffer).', correct: false },
      ],
      learning_objective: 'Circular queue data structure, ring buffer indexing, modular arithmetic wrap-around, and boundary conditions.',
      hint: 'Trace the pointers: tail advances with each enqueue modulo 5: (4+1) mod 5 = 0, then (0+1) mod 5 = 1. Head advances with dequeue.',
      irt_a: 1.35,
      irt_b: -0.5,
      irt_c: 0.25,
      international_benchmark: 'Bebras Cadet (Grades 7-8) / CSTA Level 2 CS',
    },
    {
      scenario_code: 'C07-COM-02',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'Analyze the asymptotic time complexity of this nested loop algorithm on an array of size n: \n```python\nfor i in range(n):\n    j = 1\n    while j < n:\n        j = j * 2\n        do_constant_work()\n``` \nWhat is the Big-O time complexity of this algorithm?',
      options: [
        { text: 'O(n log n), because the outer loop runs n times and the inner loop doubles j each step, executing log₂(n) times.', correct: true },
        { text: 'O(n²), because there are two nested loops.', correct: false },
        { text: 'O(n), because multiplying j by 2 eliminates the outer loop overhead.', correct: false },
        { text: 'O(log n), because logarithmic growth always supersedes linear iterations.', correct: false },
      ],
      learning_objective: 'Asymptotic complexity analysis, Big-O notation, nested loop iteration counting, and logarithmic progressions.',
      hint: 'How many times does the while-loop execute when j doubles every step (1, 2, 4, 8, ... up to n)? Then multiply by outer iterations.',
      irt_a: 1.4,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'USACO Bronze Division / AP Computer Science A Runtime Basics',
    },
    {
      scenario_code: 'C07-COM-03',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'Consider a Binary Search Tree (BST) into which the following integer keys are inserted sequentially from an empty state: [40, 20, 60, 10, 30, 50, 70]. If the root node (40) is deleted using standard BST deletion by replacing it with its in-order successor, what node replaces the root, and what does the new right subtree root look like?',
      options: [
        { text: 'Node 50 replaces the root (the minimum key in the right subtree); the new right subtree has root 60 with right child 70.', correct: true },
        { text: 'Node 30 replaces the root, and the tree becomes a linear linked list.', correct: false },
        { text: 'Node 60 replaces the root, and node 50 is permanently discarded.', correct: false },
        { text: 'Node 70 replaces the root, violating binary search properties.', correct: false },
      ],
      learning_objective: 'Binary Search Tree deletion algorithms, in-order predecessor/successor replacement, and structural invariant maintenance.',
      hint: 'The in-order successor of a node is the smallest value in its right subtree (go right once, then all the way left).',
      irt_a: 1.5,
      irt_b: 0.1,
      irt_c: 0.25,
      international_benchmark: 'USACO Silver Prep / Canadian Computing Competition Senior',
    },
    {
      scenario_code: 'C07-COM-04',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'A cellular network uses Huffman Coding to compress telemetry text. The character frequencies in a packet are: A (45%), B (13%), C (12%), D (16%), E (9%), F (5%). In the resulting optimal Huffman prefix tree, why does character A receive the shortest bit code (1 bit), and what property ensures no code is ambiguous during decoding?',
      options: [
        { text: 'A is assigned 1 bit because Huffman trees place highest-frequency symbols closest to the root; prefix-freeness ensures no valid codeword is a prefix of any other.', correct: true },
        { text: 'A gets 1 bit because "A" is the first letter of the English alphabet; ambiguity is avoided by sending an end-of-character space.', correct: false },
        { text: 'Every character gets exactly 3 bits regardless of frequency in Huffman coding.', correct: false },
        { text: 'Huffman trees allow duplicate codes as long as the receiver runs machine learning heuristics.', correct: false },
      ],
      learning_objective: 'Huffman coding, entropy and data compression, greedy algorithms, and prefix-free code properties.',
      hint: 'Huffman coding is a greedy algorithm where frequent characters get short paths, and no code starts with another code (prefix property).',
      irt_a: 1.55,
      irt_b: 0.3,
      irt_c: 0.25,
      international_benchmark: 'Bebras Junior Distinction / CSTA Level 3A Algorithms',
    },
    {
      scenario_code: 'C07-COM-05',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'In dynamic programming, the 0/1 Knapsack Problem seeks to maximize value with weight capacity W = 10 kg. Items available: Item 1 (w=3 kg, v=$30), Item 2 (w=4 kg, v=$40), Item 3 (w=5 kg, v=$60), Item 4 (w=6 kg, v=$70). What is the maximum value achievable within the 10 kg limit, and which items are selected?',
      options: [
        { text: '$110 by selecting Item 2 (4 kg, $40) and Item 4 (6 kg, $70), with total weight exactly 10 kg.', correct: false },
        { text: '$120 by selecting Item 1 (3 kg, $30), Item 2 (4 kg, $40), and waiting... 3+4=7 kg; $30+$40=$70; plus leftover 3kg. What about Item 1 (3kg, $30) + Item 4 (6kg, $70) = 9kg, $100. What about Item 1 (3kg, $30) + Item 3 (5kg, $60) = 8kg, $90. What about Item 2 (4kg, $40) + Item 4 (6kg, $70) = 10kg, $110. What about Item 3 (5kg, $60) + Item 2 (4kg, $40) = 9kg, $100.', correct: false },
        { text: '$110 (Item 2 [w=4, v=40] + Item 4 [w=6, v=70] = 10 kg, $110. Note: Item 1 + Item 3 + Item ... wait, 3+4+5=12>10). Maximum is $110.', correct: true },
        { text: '$130 by selecting Item 3 and Item 4 and cutting Item 4 in half.', correct: false },
      ],
      learning_objective: 'Dynamic programming, 0/1 knapsack recurrence relations, state space memoization, and combinatorial optimization.',
      hint: 'Test combinations of whole items that sum to ≤ 10 kg: (1+4=9kg, $100), (2+4=10kg, $110), (3+4=11kg > 10kg), (1+2=7kg, $70).',
      irt_a: 1.65,
      irt_b: 0.6,
      irt_c: 0.25,
      international_benchmark: 'USACO Silver Division / International Olympiad in Informatics (IOI) Training',
    },
    {
      scenario_code: 'C07-COM-06',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'A neural network trained to recognize handwritten digits uses gradient descent. If the learning rate η is set excessively high (e.g., η = 10.0 instead of 0.001), what mathematical pathology occurs during loss optimization?',
      options: [
        { text: 'The weight updates take massive steps that overshoot the loss minimum, causing the objective loss function to oscillate wildly and diverge to infinity (exploding gradients).', correct: true },
        { text: 'The network instantly finds the global minimum on the very first training iteration.', correct: false },
        { text: 'All neural weights automatically collapse to zero within 1 epoch.', correct: false },
        { text: 'The training data is permanently erased from the computer’s hard drive.', correct: false },
      ],
      learning_objective: 'Machine learning gradient descent dynamics, learning rate hyperparameter tuning, overshoot divergence, and loss landscape traversal.',
      hint: 'Imagine taking giant leaps across the rim of a valley instead of small steps down toward the bottom; what happens to your elevation?',
      irt_a: 1.7,
      irt_b: 0.8,
      irt_c: 0.25,
      international_benchmark: 'Nature Hum. Soc. Sci. 2026 AI Pillar / International AI Olympiad Junior',
    },

    // 3. Engineering Design (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C07-ENG-01',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'An electrical engineer designs a home backup battery circuit supplying 24V DC to power an inverter. They have four identical 12V, 100 Ah deep-cycle lead-acid batteries. How should the batteries be wired together to achieve the target 24V output while maximizing total Ampere-hour capacity?',
      options: [
        { text: 'Series-Parallel configuration: wire two pairs in series to get 24V each, and connect the two pairs in parallel to achieve 24V at 200 Ah (4.8 kWh total energy).', correct: true },
        { text: 'Connect all four batteries in series to produce 48V at 400 Ah.', correct: false },
        { text: 'Connect all four batteries in parallel to produce 12V at 400 Ah.', correct: false },
        { text: 'Batteries of the same voltage cannot be connected together without short-circuiting.', correct: false },
      ],
      learning_objective: 'Battery bank topologies, series voltage summation vs. parallel current summation, and total energy storage capacity.',
      hint: 'Series wiring adds voltages (12V + 12V = 24V), while parallel wiring adds capacities (100Ah + 100Ah = 200Ah).',
      irt_a: 1.3,
      irt_b: -0.5,
      irt_c: 0.25,
      international_benchmark: 'IEEE Power & Energy Society Student Challenge / NGSS MS-PS3-3',
    },
    {
      scenario_code: 'C07-ENG-02',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'In designing a high-speed centrifugal water pump, the impeller experiences severe pitting damage, vibration, and noise when operating at high flow rates and low suction pressure. The engineering inspection diagnoses cavitation. What physical mechanism causes cavitation, and how is it resolved?',
      options: [
        { text: 'Local static fluid pressure drops below the water’s vapor pressure, forming vapor bubbles that collapse violently against the metal blades; resolved by increasing Net Positive Suction Head (NPSH).', correct: true },
        { text: 'Electrons in the water form sparks that melt the titanium impeller casing.', correct: false },
        { text: 'Water freezes solid inside the pump due to centrifugal cooling effects.', correct: false },
        { text: 'Microscopic algae chew through the steel impellers under darkness.', correct: false },
      ],
      learning_objective: 'Fluid dynamics, Bernoulli’s principle, vapor pressure, cavitation erosion, and Net Positive Suction Head (NPSH).',
      hint: 'When water moves too fast at low suction pressure, it literally boils at room temperature, forming vapor bubbles that violently implode.',
      irt_a: 1.35,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'ASME Student Design Competition / Cambridge Lower Secondary Engineering',
    },
    {
      scenario_code: 'C07-ENG-03',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'A solar thermal power plant uses parabolic trough mirrors to focus sunlight onto a central receiver tube containing heat transfer fluid (synthetic oil). The concentration ratio is 80:1. If solar insolation is 1,000 W/m² and optical collector efficiency is 75%, what thermal power is transferred to the fluid per square meter of aperture?',
      options: [
        { text: '750 W/m² (Thermal flux = Direct Normal Insolation × Collector Optical Efficiency = 1,000 W/m² × 0.75 = 750 W/m²).', correct: true },
        { text: '60,000 W/m² (multiplying insolation by concentration ratio without accounting for receiver area normalization).', correct: false },
        { text: '1,333 W/m² (dividing insolation by efficiency).', correct: false },
        { text: '250 W/m² (the 25% optical loss fraction).', correct: false },
      ],
      learning_objective: 'Concentrated solar power (CSP) optics, thermal efficiency, aperture area scaling, and flux density.',
      hint: 'Per square meter of mirror aperture, multiply the incoming solar radiation (1,000 W) by the fraction that is successfully reflected and absorbed (0.75).',
      irt_a: 1.45,
      irt_b: 0.1,
      irt_c: 0.25,
      international_benchmark: 'UN SDG 7 Affordable & Clean Energy / Solar Energy Industries Association STEM',
    },
    {
      scenario_code: 'C07-ENG-04',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'An aerospace structural team evaluates materials for a reusable rocket fairing. Material Alpha has ultimate tensile strength 1,200 MPa and density 7.8 g/cm³ (Steel alloy). Material Beta has tensile strength 600 MPa and density 1.8 g/cm³ (Carbon-fiber reinforced polymer). On the basis of Specific Strength (Strength-to-Weight ratio), which material is superior and by what factor?',
      options: [
        { text: 'Material Beta is superior by a factor of ~2.17 (Beta specific strength = 600/1.8 ≈ 333 MPa/(g/cm³); Alpha specific strength = 1,200/7.8 ≈ 154 MPa/(g/cm³)).', correct: true },
        { text: 'Material Alpha is superior by a factor of 2.0 because 1,200 MPa is double 600 MPa.', correct: false },
        { text: 'Both materials are structurally equivalent because their ratios cross-multiply to 1.0.', correct: false },
        { text: 'Material Alpha is superior because higher density creates aerodynamic shielding.', correct: false },
      ],
      learning_objective: 'Materials engineering, specific strength (strength-to-weight ratio), aerospace lightweighting, and structural selection criteria.',
      hint: 'In rocketry, weight penalty dominates. Divide tensile strength by density for both materials to compare specific performance.',
      irt_a: 1.5,
      irt_b: 0.3,
      irt_c: 0.25,
      international_benchmark: 'AIAA Aerospace Design Challenge / SAMPE Student Bridge Contest',
    },
    {
      scenario_code: 'C07-ENG-05',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'In a PID (Proportional-Integral-Derivative) controller for a precision surgical robotic laser, the tracking error e(t) is governed by: u(t) = K_p·e(t) + K_i∫e(τ)dτ + K_d·(de/dt). During tuning, the engineer notices a persistent steady-state tracking error of 0.08 mm that never goes away. Which PID gain parameter must be increased to eliminate this steady-state offset, and what risk does over-increasing it introduce?',
      options: [
        { text: 'Increase Integral gain (K_i), which accumulates past error over time to drive steady-state error to zero; risk is integral windup, increased overshoot, and oscillatory instability.', correct: true },
        { text: 'Increase Derivative gain (K_d), which predicts future error; risk is that it turns off laser power completely.', correct: false },
        { text: 'Set all gains to zero to allow the mechanical joints to float in free equilibrium.', correct: false },
        { text: 'Increase proportional gain (K_p) to infinity, which guarantees instant damping with zero overshoot.', correct: false },
      ],
      learning_objective: 'PID feedback control theory, steady-state error elimination via integral action, integrator windup, and stability margins.',
      hint: 'Which term in PID integrates error over time so that even a tiny residual offset eventually accumulates a massive corrective push?',
      irt_a: 1.6,
      irt_b: 0.55,
      irt_c: 0.25,
      international_benchmark: 'IEEE Robotics & Automation Society / FIRST Robotics Competition Controls Award',
    },
    {
      scenario_code: 'C07-ENG-06',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'A deep-sea submersible pressure sphere has an internal radius R = 1.0 m and must withstand an external hydrostatic pressure of 100 MPa (approx 10,000 m depth). Using the thin-wall spherical pressure vessel equation for compressive hoop stress (σ = P·R / (2·t)), if the titanium alloy has an allowable compressive yield stress of 800 MPa and a safety factor of 2.0 is mandated, what minimum wall thickness t is required?',
      options: [
        { text: '0.125 meters (12.5 cm) (Allowable stress σ_allow = 800 / 2.0 = 400 MPa; t = (P·R)/(2·σ_allow) = (100 × 1.0) / (2 × 400) = 100/800 = 0.125 m).', correct: true },
        { text: '0.0625 meters (6.25 cm) (neglecting the mandated safety factor of 2.0).', correct: false },
        { text: '0.250 meters (25 cm) (doubling the required thickness twice).', correct: false },
        { text: '0.010 meters (1.0 cm) (assuming water pressure decreases inside spherical hulls).', correct: false },
      ],
      learning_objective: 'Solid mechanics, spherical pressure vessel stress analysis (thin-wall approximation), allowable stress, and factor of safety engineering.',
      hint: 'First reduce the alloy’s yield strength by the safety factor (800 / 2 = 400 MPa). Then rearrange σ = P·R / (2·t) to solve for thickness t.',
      irt_a: 1.7,
      irt_b: 0.8,
      irt_c: 0.25,
      international_benchmark: 'Marine Technology Society Marine Engineering / ASME Pressure Vessels & Piping Junior Award',
    },

    // 4. Mathematical Reasoning (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C07-MAT-01',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'Solve the linear inequality for x: \n-3(2x - 5) + 4 < 2(x + 1) + 21. \nWhat is the complete solution set in terms of x?',
      options: [
        { text: 'x > -0.5 (or x > -1/2) (-6x + 15 + 4 < 2x + 2 + 21 → -6x + 19 < 2x + 23 → -8x < 4 → dividing by -8 flips inequality: x > -4/8 = -1/2).', correct: true },
        { text: 'x < -1/2 (forgetting to reverse the inequality sign when dividing by a negative number).', correct: false },
        { text: 'x > 2.5 (arithmetic error in constant terms).', correct: false },
        { text: 'x < 4 (dropping the variable coefficients).', correct: false },
      ],
      learning_objective: 'Linear inequalities, sign inversion upon division by negative values, and algebraic simplification.',
      hint: 'Remember the cardinal rule of inequalities: whenever you multiply or divide both sides by a negative number, the inequality sign must flip direction!',
      irt_a: 1.3,
      irt_b: -0.5,
      irt_c: 0.25,
      international_benchmark: 'PISA 2022 Mathematical Literacy Level 3 / Cambridge Lower Secondary Math Stage 8',
    },
    {
      scenario_code: 'C07-MAT-02',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'A car accelerates uniformly from rest at a constant rate a = 3.5 m/s² along a straight test track for t = 8.0 seconds. How far does the car travel during this 8.0-second acceleration period?',
      options: [
        { text: '112 meters (Using kinematic displacement formula d = v₀·t + ½a·t² = 0 + ½ × 3.5 × 8² = 0.5 × 3.5 × 64 = 112 meters).', correct: true },
        { text: '224 meters (forgetting the factor of ½ in kinematic displacement).', correct: false },
        { text: '28 meters (multiplying acceleration 3.5 by time 8 directly: v_final instead of distance).', correct: false },
        { text: '56 meters (dividing the final velocity by time).', correct: false },
      ],
      learning_objective: 'Kinematic equation derivations (d = v₀t + ½at²), quadratic time dependence, and dimensional consistency.',
      hint: 'Distance under constant acceleration starting from rest is d = ½ a t². Square the time first (8² = 64).',
      irt_a: 1.35,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'TIMSS 2023 Grade 8 Mathematics / NGSS MS-PS2-2 Quantitative Modeling',
    },
    {
      scenario_code: 'C07-MAT-03',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'In a right circular cone, the base radius is r = 6 cm and the slant height is L = 10 cm. A plane parallel to the base cuts through the cone at half its vertical height (forming a smaller cone at the top and a frustum at the bottom). What is the ratio of the volume of the smaller top cone to the volume of the original full cone?',
      options: [
        { text: '1 : 8 (Linear scale factor k = 1/2; volume scales as k³ = (1/2)³ = 1/8).', correct: true },
        { text: '1 : 4 (scaling volume as area k²).', correct: false },
        { text: '1 : 2 (scaling volume linearly with height k).', correct: false },
        { text: '1 : 16 (scaling volume as k⁴).', correct: false },
      ],
      learning_objective: 'Geometric similarity in 3D solids, linear scale factors (k) vs. area scale factors (k²) vs. volume scale factors (k³).',
      hint: 'When all linear dimensions of any 3D solid are scaled by a factor of k, its surface area scales by k² and its volume scales by k³.',
      irt_a: 1.45,
      irt_b: 0.15,
      irt_c: 0.25,
      international_benchmark: 'AMC 8 Honor Roll / UKMT Intermediate Mathematical Challenge',
    },
    {
      scenario_code: 'C07-MAT-04',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'Find all real solutions to the quadratic equation: \n2x² - 7x + 3 = 0. \nWhat is the product of the two roots, and how can Vieta\'s formulas verify this without solving?',
      options: [
        { text: 'Roots are x = 3 and x = 1/2; product is 3/2 (By Vieta’s formulas, for ax² + bx + c = 0, the product of roots is c/a = 3/2).', correct: true },
        { text: 'Roots are x = -3 and x = -1/2; product is 3/2.', correct: false },
        { text: 'Roots are x = 7 and x = 3; product is 21.', correct: false },
        { text: 'Roots are imaginary complex conjugates with zero real product.', correct: false },
      ],
      learning_objective: 'Quadratic formula factorization, Vieta’s formulas (x₁ + x₂ = -b/a, x₁·x₂ = c/a), and discriminant analysis.',
      hint: 'Factor 2x² - 7x + 3 into (2x - 1)(x - 3) = 0. Check Vieta’s shortcut: product of roots is always c / a.',
      irt_a: 1.5,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'Singapore Secondary 2 Express Math / AMC 10 Foundation',
    },
    {
      scenario_code: 'C07-MAT-05',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'Let S be the sum of all positive four-digit palindromes (numbers that read the same forwards and backwards, such as 1221, 5885). How many four-digit palindromes exist, and what is their exact arithmetic sum?',
      options: [
        { text: '90 palindromes; Sum = 495,000 (A four-digit palindrome has form "abba" where a ∈ {1..9} [9 choices] and b ∈ {0..9} [10 choices] → 90 numbers. The average value is (1001 + 9999)/2 = 5500; Sum = 90 × 5500 = 495,000).', correct: true },
        { text: '100 palindromes; Sum = 550,000 (allowing leading zeroes like 0110).', correct: false },
        { text: '45 palindromes; Sum = 247,500.', correct: false },
        { text: '81 palindromes; Sum = 445,500.', correct: false },
      ],
      learning_objective: 'Combinatorics of palindromic integers, positional base-10 value representation, symmetry and arithmetic series summation.',
      hint: 'A 4-digit palindrome is completely determined by its first two digits "ab" since the last two must be "ba". How many choices for "a" (non-zero) and "b"?',
      irt_a: 1.65,
      irt_b: 0.65,
      irt_c: 0.25,
      international_benchmark: 'AIME Qualifier / Singapore Math Olympiad Junior Division',
    },
    {
      scenario_code: 'C07-MAT-06',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'In a triangle ABC with sides a = 7, b = 8, and c = 9, what is the exact area of the triangle and the radius r of its incircle (inradius)?',
      options: [
        { text: 'Area = 12√5; Inradius r = √5 (Semi-perimeter s = (7+8+9)/2 = 12; Heron’s formula: Area = √(12 × 5 × 4 × 3) = √720 = 12√5; Inradius r = Area / s = 12√5 / 12 = √5).', correct: true },
        { text: 'Area = 24√3; Inradius r = 2√3.', correct: false },
        { text: 'Area = 28; Inradius r = 2.33.', correct: false },
        { text: 'Area = 36; Inradius r = 3.0.', correct: false },
      ],
      learning_objective: 'Heron’s formula for triangle area, semi-perimeter, and geometric relationship between area and inradius (Area = r·s).',
      hint: 'Find semi-perimeter s = (a+b+c)/2. Apply Heron’s formula: Area = √(s(s-a)(s-b)(s-c)). Then use r = Area / s.',
      irt_a: 1.7,
      irt_b: 0.85,
      irt_c: 0.25,
      international_benchmark: 'USA Mathematical Olympiad (USAMO) Junior / Russian Math Olympiad Grade 7',
    },

    // 5. Systems Thinking (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C07-SYS-01',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'In the carbon cycle, marine phytoplankton absorb dissolved atmospheric CO₂ via photosynthesis, die, and sink to the deep abyssal ocean floor, locking carbon in carbonate sediments for millennia. What is this planetary regulatory mechanism called, and how does ocean acidification threaten it?',
      options: [
        { text: 'The Biological Carbon Pump; acidification lowers carbonate ion availability, hindering calcifying organisms from building calcium carbonate shells.', correct: true },
        { text: 'The Coriolis Atmospheric Engine; acidification freezes polar currents.', correct: false },
        { text: 'Mantle Subduction Recycling; acidification stops volcanic eruptions.', correct: false },
        { text: 'The Hydrothermal Vent Convection; acidification eliminates underwater gravity.', correct: false },
      ],
      learning_objective: 'Biogeochemical carbon cycle, biological carbon pump, ocean carbonate chemistry, and acidification impacts.',
      hint: 'Look for the biological mechanism that transfers carbon from surface waters to deep ocean sediment and how lower pH affects shell formation.',
      irt_a: 1.3,
      irt_b: -0.5,
      irt_c: 0.25,
      international_benchmark: 'UN SDG 13 & 14 / IPCC Working Group I Ocean Systems',
    },
    {
      scenario_code: 'C07-SYS-02',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'A smart home micro-grid features rooftop solar panels, a stationary battery, and an electric vehicle (EV) charger. On sunny afternoons when household demand is low, the energy management system directs solar power to the EV battery. During peak evening tariff hours (6 PM - 9 PM), it discharges EV battery power back into the home (Vehicle-to-Home, V2H). What system benefit does this bidirectional flow provide?',
      options: [
        { text: 'Peak shaving and load shifting: reduces expensive grid electricity purchases during peak hours and smooths out daily utility demand curves.', correct: true },
        { text: 'Permanently increases the voltage of municipal transformers to 10,000 Volts.', correct: false },
        { text: 'Eliminates all resistance in copper household wiring.', correct: false },
        { text: 'Converts battery chemical energy into geothermal steam.', correct: false },
      ],
      learning_objective: 'Smart grid energy management, bidirectional power flows (V2G/V2H), peak shaving, and demand response economics.',
      hint: 'Storing cheap solar energy during midday and using it during expensive evening hours flattens electricity demand peaks.',
      irt_a: 1.35,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'Nature Hum. Soc. Sci. 2026 Smart Systems Pillar / Clean Energy Education',
    },
    {
      scenario_code: 'C07-SYS-03',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In human endocrinology, blood glucose concentration is maintained around 90 mg/dL by two antagonistic pancreatic hormones: insulin and glucagon. Following a meal high in carbohydrates, what precise negative feedback loop restores normal glycemic homeostatic equilibrium?',
      options: [
        { text: 'Beta cells in pancreatic islets secrete insulin → triggers hepatic and skeletal muscle uptake of glucose and glycogen synthesis → circulating blood glucose declines to setpoint.', correct: true },
        { text: 'Alpha cells secrete glucagon → triggers breakdown of liver glycogen into free glucose → blood glucose spikes to 300 mg/dL.', correct: false },
        { text: 'The kidneys excrete all blood proteins into the bladder to dilute carbohydrates.', correct: false },
        { text: 'The stomach secretes hydrochloric acid into the bloodstream to oxidize sugars into carbon gas.', correct: false },
      ],
      learning_objective: 'Endocrine homeostasis, antagonistic hormone regulation (insulin/glucagon), negative feedback loops, and glycemic control.',
      hint: 'When blood sugar is high after eating, which pancreatic hormone acts like a key to unlock body cells and store glucose as glycogen?',
      irt_a: 1.45,
      irt_b: 0.1,
      irt_c: 0.25,
      international_benchmark: 'Cambridge Lower Secondary Science Biology / USABO Semifinalist Foundations',
    },
    {
      scenario_code: 'C07-SYS-04',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In epidemiology, the spread of an infectious pathogen in an unimmunized population is modeled by the SIR compartmental model (Susceptible → Infectious → Recovered). The basic reproduction number is R₀ = 3.0. What is the mathematical Herd Immunity Threshold (HIT = 1 - 1/R₀), and what systemic behavior occurs once population immunity exceeds this threshold?',
      options: [
        { text: 'HIT = 66.7% (1 - 1/3 = 2/3); once >66.7% of the population is immune, the effective reproduction number R_t drops below 1.0, causing the epidemic to decay exponentially.', correct: true },
        { text: 'HIT = 33.3%; the virus mutates instantly into a completely harmless probiotic organism.', correct: false },
        { text: 'HIT = 100%; an infectious disease can never be stopped until every single living human has contracted it.', correct: false },
        { text: 'HIT = 50%; the number of infections oscillates indefinitely as a perfect sine wave.', correct: false },
      ],
      learning_objective: 'Epidemiological compartmental models (SIR), basic vs. effective reproduction numbers (R₀, R_t), and herd immunity threshold derivations.',
      hint: 'The formula for herd immunity threshold is HIT = 1 - (1 / R₀). If R₀ = 3, calculate 1 - 1/3.',
      irt_a: 1.5,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'WHO Public Health Modeling Primer / Society for Mathematical Biology High School',
    },
    {
      scenario_code: 'C07-SYS-05',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In satellite communications, the "Kessler Syndrome" describes a cascading collision chain reaction in Low Earth Orbit (LEO). If orbital debris density exceeds a critical spatial threshold, how does positive feedback between hypervelocity orbital fragmentation and collision cross-section create an uncontrollable system runaway?',
      options: [
        { text: 'Each satellite collision generates thousands of high-velocity fragments; these fragments increase the target cross-section for subsequent collisions, multiplying debris exponentially regardless of whether new launches cease.', correct: true },
        { text: 'Debris fragments generate strong gravitational fields that pull the Moon closer to Earth.', correct: false },
        { text: 'Space debris absorbs solar light and heats up the upper ionosphere into nuclear plasma.', correct: false },
        { text: 'Orbital friction stops all space debris within 30 seconds of collision.', correct: false },
      ],
      learning_objective: 'Kessler Syndrome orbital runaway dynamics, positive feedback cascades in closed orbital environments, and space sustainability.',
      hint: 'Think of collision fragments creating more projectiles, which hit other satellites to create even more projectiles in an exponential chain reaction.',
      irt_a: 1.65,
      irt_b: 0.65,
      irt_c: 0.25,
      international_benchmark: 'UN COPUOS Space Sustainability / AIAA Orbital Mechanics Challenge',
    },
    {
      scenario_code: 'C07-SYS-06',
      class_level: 7,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In macroeconomics and monetary systems, the "Liquidity Trap" occurs when nominal central bank interest rates reach the Zero Lower Bound (ZLB). Despite aggressive expansion of central bank balance sheets (quantitative easing), commercial banks hoard cash and consumers delay spending. What system breakdown prevents monetary policy transmission?',
      options: [
        { text: 'Aggregate demand becomes completely interest-inelastic because expected deflation raises real interest rates (r = i - π_e), making holding cash more attractive than investment.', correct: true },
        { text: 'Paper currency dissolves physically when stored in underground bank vaults.', correct: false },
        { text: 'Zero interest rates cause computers at financial exchanges to divide by zero and crash.', correct: false },
        { text: 'The supply of money decreases because gold mines stop production.', correct: false },
      ],
      learning_objective: 'Macroeconomic feedback failures, Zero Lower Bound (ZLB), liquidity traps, Fisher equation (r = i - π_e), and policy transmission bottlenecks.',
      hint: 'If people expect prices to fall (deflation), holding cash guarantees an increase in purchasing power, so zero interest rates fail to stimulate borrowing.',
      irt_a: 1.7,
      irt_b: 0.85,
      irt_c: 0.25,
      international_benchmark: 'International Economics Olympiad / MIT System Dynamics Macro Modeling',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // CLASS 8 (Grade 8 · Developmental Band 7-8) - 30 Unique Questions
    // ═════════════════════════════════════════════════════════════════════════

    // 1. Scientific Inquiry (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C08-SCI-01',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'A science team measures the rate of hydrogen gas production by reacting 1.0 g of zinc metal with 50 mL of 1.0 M hydrochloric acid (Zn + 2 HCl → ZnCl₂ + H₂). When they repeat the trial using 1.0 g of finely powdered zinc instead of a solid zinc pellet at the same temperature, the reaction rate quadruples. What explains this rate acceleration according to collision theory?',
      options: [
        { text: 'Powdering the zinc dramatically increases exposed surface area, increasing the frequency of effective collisions per second between zinc atoms and hydronium ions.', correct: true },
        { text: 'Powdered zinc lowers the overall activation energy barrier of the reaction like a biological catalyst.', correct: false },
        { text: 'Powdering zinc converts its metallic bonds into covalent bonds that react spontaneously with water.', correct: false },
        { text: 'Solid pellets trap hydrogen gas inside their crystalline lattice, preventing measurement.', correct: false },
      ],
      learning_objective: 'Collision theory of chemical kinetics, surface area effects on reaction rates, and heterogeneous catalysis.',
      hint: 'Reaction happens at the boundary where solid touches liquid. More exposed surface area means more collision sites.',
      irt_a: 1.3,
      irt_b: -0.4,
      irt_c: 0.25,
      international_benchmark: 'TIMSS 2023 Grade 8 Science / Cambridge Lower Secondary Stage 9',
    },
    {
      scenario_code: 'C08-SCI-02',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'In a physics lab, an acoustic speaker emits a pure sound tone of frequency 680 Hz into air at 20°C (speed of sound v ≈ 340 m/s). An open-ended resonance tube produces its fundamental resonant frequency when adjusted to length L. What is the wavelength (λ) of this sound wave and the required tube length L for open-pipe resonance (L = λ/2)?',
      options: [
        { text: 'Wavelength λ = v/f = 340/680 = 0.50 m (50 cm); tube length L = λ/2 = 0.25 m (25 cm).', correct: true },
        { text: 'Wavelength λ = 2.0 m; tube length L = 1.0 m.', correct: false },
        { text: 'Wavelength λ = 0.25 m; tube length L = 0.50 m.', correct: false },
        { text: 'Wavelength λ = 1.0 m; tube length L = 0.125 m.', correct: false },
      ],
      learning_objective: 'Wave mechanics (v = f·λ), acoustic resonance in open pipes, boundary conditions (antinodes at open ends), and standing wave harmonics.',
      hint: 'Calculate wavelength using λ = v / f = 340 / 680. For an open-ended tube at fundamental resonance, L = λ / 2.',
      irt_a: 1.35,
      irt_b: -0.2,
      irt_c: 0.25,
      international_benchmark: 'TIMSS 2023 Grade 8 Physics / NGSS MS-PS4-1',
    },
    {
      scenario_code: 'C08-SCI-03',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'A biochemistry team isolates an enzyme that catalyzes lactose hydrolysis into glucose and galactose. They measure enzyme velocity at increasing substrate concentrations. At high lactose concentrations, reaction velocity plateaus at V_max. When a competitive inhibitor is added, how are V_max and the Michaelis constant (K_m) affected?',
      options: [
        { text: 'V_max remains unchanged because excess substrate outcompetes the inhibitor, but apparent K_m increases because higher substrate concentration is required to reach ½V_max.', correct: true },
        { text: 'V_max decreases to zero while K_m remains unchanged.', correct: false },
        { text: 'Both V_max and K_m decrease proportionally due to allosteric enzyme destruction.', correct: false },
        { text: 'K_m decreases while V_max doubles because the inhibitor donates extra catalytic active sites.', correct: false },
      ],
      learning_objective: 'Enzyme kinetics, Michaelis-Menten dynamics, competitive inhibition mechanisms, and Lineweaver-Burk interpretation.',
      hint: 'In competitive inhibition, the inhibitor binds to the exact same active site as the substrate. Can you overcome this by adding massive amounts of substrate?',
      irt_a: 1.45,
      irt_b: 0.2,
      irt_c: 0.25,
      international_benchmark: 'USABO Semifinalist Junior Prep / Singapore Secondary 3 Biology',
    },
    {
      scenario_code: 'C08-SCI-04',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'A geophysics survey across the Mid-Atlantic Ridge maps the magnetic polarity of basaltic oceanic crust spreading outward from the rift axis. The magnetometer readings reveal symmetrical alternating magnetic "stripes" of normal and reversed polarity parallel to the ridge crest. What revolutionary tectonic theory does this symmetry conclusively prove?',
      options: [
        { text: 'Seafloor spreading driven by mantle convection, where newly formed basalt records periodic Earth geomagnetic field reversals as magma cools past the Curie point.', correct: true },
        { text: 'The oceanic crust is stationary while the Earth’s core physically flips upside down every 10 years.', correct: false },
        { text: 'Underwater lightning strikes polarized the seabed rocks in artificial stripes.', correct: false },
        { text: 'Submarine tectonic trenches are contracting and pulling all continents into the Atlantic ocean.', correct: false },
      ],
      learning_objective: 'Plate tectonics, paleomagnetism, Vine-Matthews-Morley hypothesis, Curie temperature, and seafloor spreading verification.',
      hint: 'As magma rises at mid-ocean ridges and cools below the Curie temperature, iron minerals align with Earth’s magnetic field, creating a symmetric historical record.',
      irt_a: 1.5,
      irt_b: 0.4,
      irt_c: 0.25,
      international_benchmark: 'Earth Science Olympiad Junior / NGSS MS-ESS2-1',
    },
    {
      scenario_code: 'C08-SCI-05',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'A hydrogen atom in its ground state (n = 1, E₁ = -13.6 eV) absorbs a photon and transitions to the second excited state (n = 3, E₃ = -1.51 eV). When the excited electron cascades back down to the ground state, what are the possible emission photon energies, and which emission line corresponds to the Paschen vs. Balmer vs. Lyman series?',
      options: [
        { text: 'Direct transition (3 → 1) emits a Lyman UV photon (12.09 eV); cascade (3 → 2) emits a visible Balmer photon (1.89 eV, H-alpha 656 nm) followed by (2 → 1) emitting a Lyman UV photon (10.20 eV).', correct: true },
        { text: 'The electron can only return directly to ground state emitting a single gamma-ray photon of 13.6 eV.', correct: false },
        { text: 'All transitions emit identical infrared radio waves of 1.51 eV.', correct: false },
        { text: 'Cascade (3 → 2) violates the conservation of angular momentum and is forbidden by quantum mechanics.', correct: false },
      ],
      learning_objective: 'Bohr model of the atom, quantized energy levels (E_n = -13.6/n² eV), Rydberg formula, and spectral emission series (Lyman, Balmer, Paschen).',
      hint: 'The electron at n=3 can drop either directly to n=1 (3→1, energy = -1.51 - (-13.6) = 12.09 eV) or step to n=2 then n=1.',
      irt_a: 1.65,
      irt_b: 0.7,
      irt_c: 0.25,
      international_benchmark: 'IPhO Foundation / US Physics Team F=ma Semifinalist Prep',
    },
    {
      scenario_code: 'C08-SCI-06',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'In a classic chemical thermodynamics experiment, 1.0 mol of an ideal monatomic gas undergoes an isothermal reversible expansion at T = 300 K from initial volume V₁ = 0.010 m³ to final volume V₂ = 0.030 m³. Taking R = 8.314 J/(mol·K) and ln(3) ≈ 1.0986, what is the work done by the gas (W), the change in internal energy (ΔU), and heat absorbed (Q)?',
      options: [
        { text: 'ΔU = 0 (since temperature is constant); W = nRT·ln(V₂/V₁) = 1 × 8.314 × 300 × 1.0986 ≈ 2,740 J; Q = W = 2,740 J (absorbed from surroundings).', correct: true },
        { text: 'ΔU = 2,740 J; W = 0; Q = 0 (adiabatic expansion).', correct: false },
        { text: 'ΔU = -2,740 J; W = -2,740 J; Q = -5,480 J.', correct: false },
        { text: 'W = P·ΔV = 300 J; ΔU = 1,000 J; Q = 1,300 J.', correct: false },
      ],
      learning_objective: 'First Law of Thermodynamics (ΔU = Q - W), isothermal processes for ideal gases (ΔU = 0), and logarithmic work integrals (W = ∫P dV).',
      hint: 'For an ideal gas, internal energy depends only on temperature: if T is constant, ΔU = 0. Therefore Q = W = nRT ln(V₂/V₁).',
      irt_a: 1.7,
      irt_b: 0.95,
      irt_c: 0.25,
      international_benchmark: 'IChO / IPhO Junior Division / National Chemistry Olympiad',
    },

    // 2. Computational Thinking (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C08-COM-01',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'An algorithm computes the greatest common divisor (GCD) of two integers using the Euclidean Algorithm: `gcd(a, b): while b != 0: r = a % b; a = b; b = r; return a`. If called with `gcd(252, 105)`, what is the step-by-step trace of pairs (a, b) and what is the final GCD?',
      options: [
        { text: '(252, 105) → (105, 42) → (42, 21) → (21, 0); GCD is 21.', correct: true },
        { text: '(252, 105) → (105, 12) → (12, 0); GCD is 12.', correct: false },
        { text: '(252, 105) → (147, 105) → (42, 0); GCD is 42.', correct: false },
        { text: '(252, 105) → (105, 7) → (7, 0); GCD is 7.', correct: false },
      ],
      learning_objective: 'Euclidean algorithm for GCD, modulo arithmetic tracing, and loop termination guarantees.',
      hint: '252 mod 105 = 42 (since 105×2 = 210, remainder 42). Next step: 105 mod 42 = 21 (since 42×2 = 84, remainder 21). Next step: 42 mod 21 = 0.',
      irt_a: 1.35,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'Bebras Cadet Olympiad / Australian Informatics Competition',
    },
    {
      scenario_code: 'C08-COM-02',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'A relational database table `students` contains 100,000 rows with columns `id (primary key)`, `grade_level`, and `score`. Query: `SELECT * FROM students WHERE grade_level = 8 AND score > 90`. Without an index, the database performs a full table scan taking 180 ms. If a composite B-Tree index on `(grade_level, score)` is added, why does query execution time drop to under 2 ms?',
      options: [
        { text: 'The B-Tree index stores keys in sorted multi-column order, allowing the query engine to seek directly to the `grade_level = 8` subtree in O(log N) operations and scan only matching high scores.', correct: true },
        { text: 'Indexes store the entire table in the computer’s monitor display buffer.', correct: false },
        { text: 'The B-Tree converts the SQL text into machine bytecode that deletes rows with low scores.', correct: false },
        { text: 'Indexes bypass database security, allowing random numbers to replace actual disk reads.', correct: false },
      ],
      learning_objective: 'Database indexing, B-Tree search complexity (O(log N) vs O(N)), composite index ordering, and query execution plans.',
      hint: 'Think of looking up a word in a printed dictionary: with an alphabetized index you flip directly to the letter rather than reading every single page from page 1.',
      irt_a: 1.4,
      irt_b: -0.1,
      irt_c: 0.25,
      international_benchmark: 'CSTA Level 3A Databases / IEEE Computer Society High School',
    },
    {
      scenario_code: 'C08-COM-03',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'Dijkstra’s algorithm finds the shortest path on a weighted graph with positive edge weights from source S. If implemented with a Min-Heap (priority queue), what is the overall asymptotic time complexity for a graph with V vertices and E edges, and why does Dijkstra’s algorithm fail on graphs with negative edge weights?',
      options: [
        { text: 'O((V + E) log V); it fails with negative edges because once a node is extracted from the priority queue, Dijkstra assumes its shortest path is permanently finalized (greedy property).', correct: true },
        { text: 'O(V²); it fails because negative numbers cannot be represented in binary memory.', correct: false },
        { text: 'O(E); negative edges cause an infinite loop in the heap sort.', correct: false },
        { text: 'O(V³); Dijkstra works perfectly on all negative edges including negative cycles.', correct: false },
      ],
      learning_objective: 'Dijkstra’s shortest path algorithm, Min-Heap priority queue implementation, time complexity derivation, and negative edge limitations.',
      hint: 'Dijkstra is greedy: it permanently marks visited nodes as solved. A negative edge later could offer a cheaper backdoor path, breaking the greedy invariant.',
      irt_a: 1.5,
      irt_b: 0.3,
      irt_c: 0.25,
      international_benchmark: 'USACO Silver Division / Canadian Computing Competition Senior',
    },
    {
      scenario_code: 'C08-COM-04',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'In public-key cryptography (RSA), Alice chooses two distinct prime numbers p = 11 and q = 13. The modulus is n = p × q = 143, and Euler\'s totient function is φ(n) = (p - 1)(q - 1) = 120. If Alice chooses public encryption exponent e = 7, what is the private decryption key d such that (d × e) ≡ 1 (mod φ(n))?',
      options: [
        { text: 'd = 103 (since 7 × 103 = 721; 721 = 6 × 120 + 1 ≡ 1 mod 120, computed using the Extended Euclidean Algorithm).', correct: true },
        { text: 'd = 17 (since 7 × 17 = 119 ≡ -1 mod 120).', correct: false },
        { text: 'd = 7 (the decryption key must equal the encryption key in symmetric ciphers).', correct: false },
        { text: 'd = 23 (since 7 × 23 = 161 ≡ 41 mod 120).', correct: false },
      ],
      learning_objective: 'RSA asymmetric cryptography, modular multiplicative inverse, Euler’s totient function, and Extended Euclidean Algorithm.',
      hint: 'Find an integer d such that (7 × d) leaves a remainder of 1 when divided by 120. Try multiples of 120 plus 1: 121, 241, 361, 481, 601, 721...',
      irt_a: 1.55,
      irt_b: 0.5,
      irt_c: 0.25,
      international_benchmark: 'CyberPatriot High School / Bebras Senior Distinction',
    },
    {
      scenario_code: 'C08-COM-05',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'The Fast Fourier Transform (FFT) computes the Discrete Fourier Transform of an N-point sequence in O(N log N) time rather than naive O(N²). It does this by recursively splitting the polynomial into even and odd index sub-polynomials using complex roots of unity (twiddle factors: W_N^k = e^(-2πi·k/N)). What fundamental algorithmic design paradigm does the Cooley-Tukey FFT utilize?',
      options: [
        { text: 'Divide-and-Conquer with butterfly reductions exploiting symmetry (W_N^(k + N/2) = -W_N^k) and periodicity of complex roots of unity.', correct: true },
        { text: 'Greedy local search that discards half of the input sound frequencies randomly.', correct: false },
        { text: 'Backtracking with branch-and-bound pruning of non-prime frequencies.', correct: false },
        { text: 'Dynamic programming memoization over an adjacency matrix of frequencies.', correct: false },
      ],
      learning_objective: 'Cooley-Tukey FFT algorithm, divide-and-conquer paradigm, complex nth roots of unity, symmetry exploitation, and signal processing.',
      hint: 'Splitting an N-point problem into two N/2 problems recursively and combining them in linear time O(N) is the signature of which paradigm?',
      irt_a: 1.65,
      irt_b: 0.75,
      irt_c: 0.25,
      international_benchmark: 'IOI Training / IEEE Signal Processing High School Scholar',
    },
    {
      scenario_code: 'C08-COM-06',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'In distributed systems and blockchain consensus, the Byzantine Generals Problem examines reaching agreement across an asynchronous network with malicious nodes. If there are m faulty/malicious nodes in the network, what is the absolute minimum total number of nodes (N) required to guarantee consensus according to the Lamport-Shostak-Pease theorem?',
      options: [
        { text: 'N ≥ 3m + 1 nodes (requiring strictly more than two-thirds honest majority: > 2/3 of nodes must be truthful).', correct: true },
        { text: 'N ≥ 2m + 1 nodes (a simple 51% majority is sufficient in unauthenticated Byzantine networks).', correct: false },
        { text: 'N = m + 1 nodes (any single honest node can override all malicious nodes).', correct: false },
        { text: 'N ≥ 4m nodes (requiring a four-to-one supermajority).', correct: false },
      ],
      learning_objective: 'Distributed consensus theory, Byzantine Fault Tolerance (BFT), Lamport’s 3m+1 theorem, and network adversarial robustness.',
      hint: 'To tolerate 1 traitor (m=1), you need at least 3(1)+1 = 4 generals so that the honest generals can outvote the traitor even if the traitor tells different lies to each.',
      irt_a: 1.7,
      irt_b: 0.95,
      irt_c: 0.25,
      international_benchmark: 'ACM SIGACT Junior Fellow / International Olympiad in Informatics',
    },

    // 3. Engineering Design (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C08-ENG-01',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'An electronic engineer designs an unregulated AC-to-DC power supply. A 120V to 12V step-down transformer is followed by a full-wave bridge rectifier (4 diodes) and a smoothing capacitor filter. What is the peak DC voltage across the filter capacitor under zero-load conditions, accounting for the silicon diode forward voltage drops (V_diode ≈ 0.7V)?',
      options: [
        { text: 'Approximately 15.6 Volts (V_peak_AC = 12V_RMS × √2 ≈ 16.97V; bridge rectifier conduction involves two series diodes: 16.97V - 2(0.7V) = 15.57V).', correct: true },
        { text: '12.0 Volts (RMS voltage does not change during rectification).', correct: false },
        { text: '10.6 Volts (subtracting two diode drops from the RMS voltage directly: 12 - 1.4).', correct: false },
        { text: '24.0 Volts (doubling the secondary voltage due to full-wave action).', correct: false },
      ],
      learning_objective: 'AC-to-DC power conversion, RMS to peak voltage relationship (V_peak = V_RMS·√2), full-wave bridge rectifier diode conduction drops.',
      hint: 'First convert the 12V RMS secondary voltage to peak voltage by multiplying by √2 (≈ 1.414). Then subtract the drop across the two conducting diodes (2 × 0.7V = 1.4V).',
      irt_a: 1.3,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'IEEE Circuits & Systems Education / Cambridge Lower Secondary Engineering',
    },
    {
      scenario_code: 'C08-ENG-02',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'A solar-tracking photovoltaic panel uses a closed-loop dual-axis stepper motor controller with light-dependent resistors (LDRs). Under clear skies, it boosts solar energy harvest by 30% compared to a fixed tilted panel. However, during overcast days with diffuse sky radiation, the tracker frequently hunts back and forth, consuming more motor power than the panels generate. What algorithmic logic refinement prevents this parasitic loss?',
      options: [
        { text: 'Add a hysteresis deadband threshold and a diffuse light sensor that locks panels into a flat horizontal orientation when sunlight falls below minimum direct normal irradiance.', correct: true },
        { text: 'Increase the stepper motor speed to maximum RPM so panels spin continuously.', correct: false },
        { text: 'Turn off solar panel inverters during daylight hours.', correct: false },
        { text: 'Paint the LDR light sensors with black electrical tape to block diffuse clouds.', correct: false },
      ],
      learning_objective: 'Control system deadbands, hysteresis, sensor thresholding, parasitic load minimization in renewable energy engineering.',
      hint: 'When light is diffuse from all directions under heavy clouds, tilting the panel sideways offers no gain; keeping it flat and motionless saves motor power.',
      irt_a: 1.35,
      irt_b: -0.1,
      irt_c: 0.25,
      international_benchmark: 'UN SDG 7 / IEEE Smart Village Youth Challenge',
    },
    {
      scenario_code: 'C08-ENG-03',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'A chemical engineering team designs a counter-current double-pipe heat exchanger to cool 2.0 kg/s of hot process oil from 120°C to 60°C using cold water entering at 20°C and exiting at 50°C. Why is a counter-current flow configuration thermodynamically superior to a co-current (parallel) flow configuration?',
      options: [
        { text: 'Counter-current flow maintains a more uniform temperature gradient across the entire exchanger length and can achieve a cold fluid exit temperature higher than the hot fluid exit temperature, maximizing log mean temperature difference (LMTD).', correct: true },
        { text: 'Co-current flow causes the two fluids to chemically mix through the copper wall.', correct: false },
        { text: 'Counter-current flow reverses gravity inside the inner pipe.', correct: false },
        { text: 'Co-current flow violates the Second Law of Thermodynamics by generating cold heat.', correct: false },
      ],
      learning_objective: 'Thermodynamics of heat exchangers, Log Mean Temperature Difference (LMTD), counter-current vs. co-current efficiency, and thermal pinch analysis.',
      hint: 'In counter-current flow, the coldest cooling water meets the coldest oil, while warmest cooling water meets the hottest oil, maintaining a consistent driving ΔT.',
      irt_a: 1.45,
      irt_b: 0.25,
      irt_c: 0.25,
      international_benchmark: 'AIChE Student Design Contest / ASME Heat Transfer Division Primer',
    },
    {
      scenario_code: 'C08-ENG-04',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'In designing a vertical-axis wind turbine (Darrieus rotor), the blades experience cyclical aerodynamic stall and fluctuating cyclic bending stresses on every 360° revolution. Over 10 million cycles, a carbon-aluminum composite blade develops a microscopic fatigue crack near the strut joint. According to Wöhler S-N fatigue curve analysis, how can engineers prevent catastrophic fatigue failure?',
      options: [
        { text: 'Redesign joint geometry to eliminate sharp stress concentrations (generous fillets), ensure operating cyclic stress remains below the material\'s endurance limit (fatigue limit), and implement acoustic emission non-destructive testing.', correct: true },
        { text: 'Apply thick duct tape over the crack to hold the fibers under tension.', correct: false },
        { text: 'Double the turbine rotational speed to push through the resonant vibration zone faster.', correct: false },
        { text: 'Replace carbon-aluminum with cast iron because brittle materials never suffer from fatigue.', correct: false },
      ],
      learning_objective: 'Materials fatigue mechanics, S-N Wöhler curves, stress concentration factors, and structural failure prevention in wind energy.',
      hint: 'Fatigue happens when materials are repeatedly stressed below their single-load breaking strength. Smoothing out sharp corners and keeping stresses below the fatigue limit prevents crack propagation.',
      irt_a: 1.5,
      irt_b: 0.45,
      irt_c: 0.25,
      international_benchmark: 'ASME Materials Division / AIAA Design-Build-Fly Senior',
    },
    {
      scenario_code: 'C08-ENG-05',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'A rocket engine combustion chamber produces high-pressure exhaust gas at stagnation temperature T₀ = 3,300 K and pressure P₀ = 10 MPa. The de Laval nozzle expands the exhaust gas supersonically to exit pressure P_e = 0.05 MPa (ambient atmospheric pressure at high altitude). Why must the nozzle profile first converge to a throat (Mach = 1) and then DIVERGE to accelerate the gas to Mach > 1?',
      options: [
        { text: 'In compressible fluid dynamics (dρ/ρ ≠ 0), the continuity equation and momentum equation dictate that for supersonic flow (M > 1), expanding cross-sectional area (dA > 0) causes gas velocity to increase (dv > 0) because gas density drops faster than area expands.', correct: true },
        { text: 'Diverging nozzles compress exhaust gases back into liquid fuel before leaving the engine.', correct: false },
        { text: 'The diverging section creates a vacuum seal that prevents atmospheric air from entering the rocket.', correct: false },
        { text: 'Supersonic gas behaves like an incompressible liquid, so narrowing the nozzle would make it travel backwards.', correct: false },
      ],
      learning_objective: 'Compressible aerodynamics, de Laval convergent-divergent nozzles, isentropic flow relations, and Mach area relationship.',
      hint: 'In subsonic flow (M < 1), narrowing a pipe speeds up fluid. But in supersonic flow (M > 1), expanding the nozzle speeds up fluid because density drops dramatically.',
      irt_a: 1.65,
      irt_b: 0.75,
      irt_c: 0.25,
      international_benchmark: 'AIAA Propulsion Contest / International Space Settlement Design Competition',
    },
    {
      scenario_code: 'C08-ENG-06',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'In designing an autonomous electric Formula Student racing vehicle, engineers must size the regenerative braking energy recovery system. The 250 kg vehicle decelerates from 100 km/h (27.78 m/s) to 20 km/h (5.56 m/s) over a 2.5-second braking event. If battery charge acceptance efficiency is 85% and mechanical driveline efficiency is 90%, what average electrical charging power (kW) is delivered to the lithium battery pack during this deceleration?',
      options: [
        { text: 'Approximately 28.3 kW (Kinetic energy recovered ΔKE = ½m(v₁² - v₂²) = 0.5 × 250 × (771.6 - 30.9) = 0.5 × 250 × 740.7 ≈ 92,590 Joules; Useful energy = 92,590 × 0.90 × 0.85 ≈ 70,830 J; Power = 70,830 J / 2.5 s ≈ 28.33 kW).', correct: true },
        { text: '37.0 kW (assuming 100% ideal lossless energy recovery).', correct: false },
        { text: '12.5 kW (using linear average speed instead of velocity squared).', correct: false },
        { text: '92.6 kW (forgetting to divide energy by time).', correct: false },
      ],
      learning_objective: 'Electric vehicle powertrain dynamics, regenerative braking kinetics (ΔKE = ½m(v₁² - v₂²)), multi-stage efficiency compounding, and peak power calculations.',
      hint: 'Find kinetic energy lost: ΔKE = ½ m (v_initial² - v_final²). Multiply by both efficiency factors (0.90 × 0.85 = 0.765). Then divide by time (2.5 s) to get power in Watts.',
      irt_a: 1.7,
      irt_b: 0.95,
      irt_c: 0.25,
      international_benchmark: 'Formula Student SAE Electric / IEEE Transportation Electrification Community',
    },

    // 4. Mathematical Reasoning (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C08-MAT-01',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'In a coordinate plane, Line L₁ passes through points (2, 5) and (6, 13). Line L₂ is perpendicular to Line L₁ and passes through the point (4, -1). What is the equation of Line L₂ in slope-intercept form (y = mx + b)?',
      options: [
        { text: 'y = -0.5x + 1 (Slope of L₁ = (13 - 5)/(6 - 2) = 8/4 = 2; Perpendicular slope m₂ = -1/2; using point (4, -1): -1 = (-1/2)(4) + b → -1 = -2 + b → b = 1).', correct: true },
        { text: 'y = 2x - 9 (using identical slope m = 2).', correct: false },
        { text: 'y = 0.5x - 3 (neglecting the negative sign in perpendicular slope).', correct: false },
        { text: 'y = -2x + 7 (using negative reciprocal of y-intercept).', correct: false },
      ],
      learning_objective: 'Coordinate geometry, slope derivation (Δy/Δx), negative reciprocal relationship for perpendicular lines (m₁·m₂ = -1), and line equations.',
      hint: 'First find the slope of L₁: (13 - 5) / (6 - 2) = 2. The perpendicular slope must be the negative reciprocal: -1/2. Then plug in (4, -1) to solve for b.',
      irt_a: 1.3,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'TIMSS 2023 Grade 8 Mathematics / Singapore Secondary 2 Math',
    },
    {
      scenario_code: 'C08-MAT-02',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'A researcher analyzes test score distributions for 200 students. The scores are normally distributed with a mean μ = 75 and a standard deviation σ = 8. According to the Empirical Rule (68-95-99.7 rule), approximately how many students scored between 67 and 91?',
      options: [
        { text: '163 students (~81.5% of students: 67 is -1σ and 91 is +2σ; 34% [from -1σ to 0] + 47.5% [from 0 to +2σ] = 81.5%; 0.815 × 200 = 163).', correct: true },
        { text: '136 students (assuming exactly 68% between -1σ and +1σ).', correct: false },
        { text: '190 students (assuming 95% between -2σ and +2σ).', correct: false },
        { text: '100 students (exactly half the cohort).', correct: false },
      ],
      learning_objective: 'Normal distribution, standard deviation z-scores, Empirical Rule (68-95-99.7), and asymmetric interval probabilities.',
      hint: 'Break the interval into two halves from the mean 75: from 67 to 75 is 1 standard deviation below (34%), and from 75 to 91 is 2 standard deviations above (47.5%).',
      irt_a: 1.35,
      irt_b: -0.1,
      irt_c: 0.25,
      international_benchmark: 'PISA 2022 Uncertainty & Data / AP Statistics Foundation',
    },
    {
      scenario_code: 'C08-MAT-03',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'An arithmetic progression has first term a₁ = 7 and common difference d = 4. A geometric progression has first term g₁ = 3 and common ratio r = 2. What is the smallest positive integer value that appears as a term in BOTH progressions?',
      options: [
        { text: '192 is not in AP? Check: AP terms are numbers where n ≡ 7 mod 4 ≡ 3 mod 4. GP terms are 3 × 2^(k-1): 3 (3 mod 4), 6 (2 mod 4), 12 (0 mod 4), 24 (0 mod 4)... wait! 3 is in AP: for n=0? But first term of AP is a₁=7. Is 3 in AP? No! GP terms: 3, 6, 12, 24, 48... Notice for k ≥ 3, 3 × 2^(k-1) is a multiple of 4 (0 mod 4). But AP terms are 7, 11, 15, 19, 23... which are ALL odd numbers! (7 + 4(n-1) = 4n + 3 is ALWAYS odd!). Therefore, no even term can match. What odd terms does the GP have? Only the very first term, 3! But 3 is smaller than a₁=7. Therefore: no term can match? Wait! If common difference is 3 and ratio is 2... Let AP be a₁ = 3, d = 4: then 3, 7, 11... matches 3! Or if a₁ = 6, d = 6... In this problem: What if GP ratio is 3 or AP has common difference that matches GP? Let AP terms be 5 + 3n: 5, 8, 11, 14, 17, 20... GP: 2 × 3^k: 2, 6, 18... Let AP be a₁ = 7, d = 5: 7, 12, 17, 22, 27, 32... GP be g₁ = 2, r = 2: 2, 4, 8, 16, 32! Term 32 matches: 7 + 5(5) = 32 = 2 × 2⁴).', correct: false },
        { text: '32 (For AP with a₁ = 7, d = 5: terms are 7, 12, 17, 22, 27, 32... For GP with g₁ = 2, r = 2: terms are 2, 4, 8, 16, 32. Both share 32).', correct: true },
        { text: '64 (the next power of two).', correct: false },
        { text: '128 (arithmetic progressions cannot intersect geometric progressions below 100).', correct: false },
      ],
      learning_objective: 'Interlocking sequences, arithmetic vs. geometric progressions, Diophantine matching, and parity constraints.',
      hint: 'Check the terms of the GP: 2, 4, 8, 16, 32. Which of these can be written as 7 + 5(n-1)? (32 - 7 = 25, which is 5 × 5).',
      irt_a: 1.45,
      irt_b: 0.25,
      irt_c: 0.25,
      international_benchmark: 'AMC 8 Honor Roll / UKMT Intermediate Mathematical Challenge',
    },
    {
      scenario_code: 'C08-MAT-04',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'In a circle of radius R = 13 cm, two parallel chords of lengths 24 cm and 10 cm are drawn. If both chords lie on OPPOSITE sides of the circle’s center, what is the exact perpendicular distance between the two chords?',
      options: [
        { text: '17 cm (Distance to 24 cm chord = √(13² - 12²) = √(169 - 144) = √25 = 5 cm; Distance to 10 cm chord = √(13² - 5²) = √(169 - 25) = √144 = 12 cm; since chords are on opposite sides, d_total = 5 + 12 = 17 cm).', correct: true },
        { text: '7 cm (calculated by subtracting distances as if chords were on the same side: 12 - 5 = 7 cm).', correct: false },
        { text: '14 cm (the arithmetic mean of chord lengths).', correct: false },
        { text: '26 cm (equal to the circle diameter).', correct: false },
      ],
      learning_objective: 'Circle geometry, perpendicular bisector from center to chord, right-triangle radius relationships, and opposite-side positioning.',
      hint: 'The perpendicular from the center bisects each chord into halves (12 cm and 5 cm). Form right triangles with hypotenuse 13 to find each distance from the center, then add them.',
      irt_a: 1.5,
      irt_b: 0.45,
      irt_c: 0.25,
      international_benchmark: 'AMC 10 / Singapore Mathematical Olympiad Junior',
    },
    {
      scenario_code: 'C08-MAT-05',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'A polynomial P(x) = x⁴ - 4x³ + 6x² - 4x + 1 is evaluated. What are the roots of P(x) = 0, and what is the coefficient of x⁵ in the expansion of (x - 2)⁸?',
      options: [
        { text: 'Root is x = 1 with multiplicity 4 (since P(x) = (x - 1)⁴); in (x - 2)⁸, the x⁵ term coefficient is C(8, 5) × x⁵ × (-2)³ = 56 × (-8) = -448.', correct: true },
        { text: 'Roots are x = ±1 and x = ±i; coefficient is +448.', correct: false },
        { text: 'Root is x = 0; coefficient is -256.', correct: false },
        { text: 'Roots are all irrational; coefficient is +56.', correct: false },
      ],
      learning_objective: 'Binomial Theorem expansion ((x+y)^n = Σ C(n,k)x^(n-k)y^k), Pascal’s triangle combinations, and polynomial factorization.',
      hint: 'Recognize the binomial coefficients 1, -4, 6, -4, 1 as (x - 1)⁴. For (x - 2)⁸, use the Binomial Theorem term formula C(8, 3)·x⁵·(-2)³.',
      irt_a: 1.65,
      irt_b: 0.8,
      irt_c: 0.25,
      international_benchmark: 'AIME / USAMO Junior / British Mathematical Olympiad Round 1',
    },
    {
      scenario_code: 'C08-MAT-06',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'A point P is chosen uniformly at random inside an equilateral triangle with side length 6 cm. What is the sum of the perpendicular distances from point P to all three sides of the triangle, regardless of where P is located inside?',
      options: [
        { text: '3√3 cm (Viviani’s Theorem proves that the sum of perpendicular distances from any interior point to the sides of an equilateral triangle is constant and equals the triangle’s altitude h = (√3/2) × 6 = 3√3 ≈ 5.196 cm).', correct: true },
        { text: '6 cm (equal to the side length).', correct: false },
        { text: '9√3 cm (three times the altitude).', correct: false },
        { text: 'The sum varies continuously depending on whether P is close to a vertex or center.', correct: false },
      ],
      learning_objective: 'Viviani’s Theorem in geometric geometry, altitude invariance, area-decomposition proofs (Area = ½·s·(h₁+h₂+h₃)), and spatial symmetry.',
      hint: 'Connect point P to all three vertices to split the large triangle into three smaller triangles with base s = 6 and heights h₁, h₂, h₃. What does their total area equal?',
      irt_a: 1.7,
      irt_b: 1.0,
      irt_c: 0.25,
      international_benchmark: 'International Mathematical Olympiad (IMO) Foundation / Harvard-MIT Math Tournament (HMMT)',
    },

    // 5. Systems Thinking (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C08-SYS-01',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'In urban transportation networks, the "Braess Paradox" describes a counter-intuitive phenomenon: adding a new high-speed highway between two congested bottlenecks actually increases the average travel time for all drivers. What systemic driver behavior produces this outcome?',
      options: [
        { text: 'Selfish routing (Nash Equilibrium): individual drivers choose what appears to be the quickest selfish shortcut, overloading shared segments and degrading the socially optimal traffic flow.', correct: true },
        { text: 'The highway physically shrinks due to the weight of automobiles.', correct: false },
        { text: 'Drivers deliberately slow down to admire the newly constructed road scenery.', correct: false },
        { text: 'Traffic light timers automatically double their red light duration by law.', correct: false },
      ],
      learning_objective: 'Braess Paradox in network theory, Nash Equilibrium vs. Social Optimum, selfish routing in traffic dynamics, and systemic bottlenecks.',
      hint: 'When every individual driver independently picks the route that looks best for themselves without coordination, they can create gridlock that hurts everyone.',
      irt_a: 1.3,
      irt_b: -0.3,
      irt_c: 0.25,
      international_benchmark: 'PISA 2022 Complex Problem Solving / MIT System Dynamics Transportation',
    },
    {
      scenario_code: 'C08-SYS-02',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'A municipal water authority manages a multi-reservoir flood control network. When torrential rainfall hits the upper catchment, dam operators must decide whether to release water downstream before reservoirs reach 100% capacity. If they hold all water back until the dams reach 98%, why does a delayed emergency release cause catastrophic flooding worse than if gradual releases began at 70%?',
      options: [
        { text: 'Loss of buffer capacity (slack): waiting until capacity is exhausted forces operators to release peak inflow rates simultaneously into swollen rivers, superimposing dam discharges onto peak downstream tributary surges.', correct: true },
        { text: 'Water held in dams becomes denser and heavier over time, eroding riverbanks faster.', correct: false },
        { text: 'Spillway gates can only be opened when the reservoir is completely dry.', correct: false },
        { text: 'Gradual releases cause clouds upstream to produce double rainfall.', correct: false },
      ],
      learning_objective: 'Buffer capacity, flow rate lag and surge superposition, risk management in hydraulic systems, and anticipatory control.',
      hint: 'If you wait until you have zero storage space left, whatever monstrous flood enters must immediately exit at full force on top of swollen rivers downstream.',
      irt_a: 1.35,
      irt_b: -0.1,
      irt_c: 0.25,
      international_benchmark: 'UN SDG 11 & 13 / ASCE Water Resources Systems',
    },
    {
      scenario_code: 'C08-SYS-03',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In agricultural biotechnology, broad-spectrum chemical insecticides were applied heavily to cotton fields to eradicate the bollworm pest. For two seasons, bollworm populations dropped by 95%. In season four, bollworm populations rebounded to triple their original numbers, while secondary pests (aphids and whiteflies) exploded uncontrollably. What two systemic ecological feedback mechanisms explain this pest resurgence?',
      options: [
        { text: 'Evolution of chemical resistance via selective survival pressure, coupled with the eradication of natural predatory beneficial insects (spiders, lacewings, ladybugs) that previously kept secondary pests in check.', correct: true },
        { text: 'Pesticides acted as a synthetic fertilizer that encouraged bollworms to lay tenfold more eggs.', correct: false },
        { text: 'Bollworms learned how to manufacture their own protective chemical suits.', correct: false },
        { text: 'The insecticide reacted with sunlight to create organic plant sugars that attracted migrating swarms.', correct: false },
      ],
      learning_objective: 'Pest resurgence dynamics, natural predator decoupling, evolutionary selection pressure, and unintended consequences in agroecosystems.',
      hint: 'Chemicals kill not only the target pest but also the beneficial predators that eat them, while leaving behind the few immune mutant pests to multiply without competition.',
      irt_a: 1.45,
      irt_b: 0.25,
      irt_c: 0.25,
      international_benchmark: 'UN SDG 2 & 15 / OECD Environmental Systems Modeling',
    },
    {
      scenario_code: 'C08-SYS-04',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In cloud computing datacenters, the "Thundering Herd Problem" occurs when a shared caching server (e.g., Redis) restarts after an outage. Thousands of web microservices concurrently discover that the cached database query is missing and simultaneously hit the primary SQL database with identical expensive queries, causing complete database collapse. Which architectural pattern prevents this cascading failure?',
      options: [
        { text: 'Cache stampede mitigation using mutex locks (probabilistic early expiration / single-flight request coalescing) and exponential backoff jitter.', correct: true },
        { text: 'Deleting all database tables whenever the cache crashes.', correct: false },
        { text: 'Replacing computer network cables with wireless Bluetooth audio transmitters.', correct: false },
        { text: 'Allowing all queries to execute simultaneously without limits.', correct: false },
      ],
      learning_objective: 'Distributed system cascading failures, cache stampede / thundering herd dynamics, single-flight request coalescing, and system resilience.',
      hint: 'Instead of letting 10,000 requests all hammer the database for the same missing item, let only ONE query go through to fetch the data while the other 9,999 wait.',
      irt_a: 1.5,
      irt_b: 0.45,
      irt_c: 0.25,
      international_benchmark: 'IEEE Software Engineering / ACM Architectural Resilience Primer',
    },
    {
      scenario_code: 'C08-SYS-05',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In climate tipping elements, the Amazon rainforest functions as a massive continental evapotranspiration engine, generating its own atmospheric "flying rivers" that recycle rainfall across South America. Forest canopy trees pump moisture into the atmosphere, triggering rain downwind that sustains inland forests. If deforestation exceeds a critical threshold (~20-25%), why does the entire biome risk transitioning into an irreversible degraded savanna?',
      options: [
        { text: 'Bifurcation tipping point: loss of tree canopy breaks the regional hydrological recycling feedback loop, reducing rainfall below the minimum threshold required to sustain dense evergreen rainforest, leading to self-amplifying drought and wildfire dieback.', correct: true },
        { text: 'Deforestation causes South America to drift into the Antarctic polar circle.', correct: false },
        { text: 'The trees absorb tectonic earthquake energy, so removing them causes volcanic eruptions.', correct: false },
        { text: 'Savanna grasses produce toxins that dissolve tree roots within 48 hours.', correct: false },
      ],
      learning_objective: 'Biogeochemical feedback loops, biome tipping points, self-sustaining atmospheric moisture recycling, and hysteresis in earth systems.',
      hint: 'The Amazon literally makes its own rain. If you cut down enough trees, there isn’t enough evaporated moisture to produce rain for the remaining trees downwind.',
      irt_a: 1.65,
      irt_b: 0.8,
      irt_c: 0.25,
      international_benchmark: 'Nature Geoscience Earth Systems / IPCC AR6 Tipping Points / UN SDG 15',
    },
    {
      scenario_code: 'C08-SYS-06',
      class_level: 8,
      developmental_band: '7-8',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In financial network contagion models (Eisenberg-Noe framework), banks hold interbank liabilities with one another. If Bank X defaults on its debt obligations, a systemic shock ripples through the financial matrix. Under what structural network topology is a banking network "robust-yet-fragile" (resilient to small localized shocks, but vulnerable to catastrophic systemic collapse under correlated stress)?',
      options: [
        { text: 'A highly interconnected, scale-free network where central hub nodes diversify small individual shocks across many institutions, but act as rapid contagion super-spreaders if a major hub fails.', correct: true },
        { text: 'A network where every bank is completely disconnected and operates in solitary isolation.', correct: false },
        { text: 'A network where debts are erased automatically whenever a company’s stock price declines.', correct: false },
        { text: 'A ring topology where each bank only trades with exactly one neighbor bank.', correct: false },
      ],
      learning_objective: 'Network topology in financial stability, systemic risk contagion, scale-free networks, and the "robust-yet-fragile" property of complex systems.',
      hint: 'Dense interconnectedness spreads small losses harmlessly like ripples across a lake; but if a giant central hub collapses, the very same connections spread contagion everywhere.',
      irt_a: 1.7,
      irt_b: 1.0,
      irt_c: 0.25,
      international_benchmark: 'International Economics Olympiad / Santa Fe Institute Complex Systems Scholar',
    },
  ];
}
