import type { ScenarioRecord } from './types';

export function getBand9_10Scenarios(): ScenarioRecord[] {
  return [
    // ═════════════════════════════════════════════════════════════════════════
    // CLASS 9 (Grade 9 · Developmental Band 9-10) - 30 Unique Questions
    // ═════════════════════════════════════════════════════════════════════════

    // 1. Scientific Inquiry (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C09-SCI-01',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'A chemistry student performs a titration of 25.0 mL of hydrochloric acid (HCl) of unknown concentration with 0.100 M sodium hydroxide (NaOH) using phenolphthalein indicator. The faint pink equivalence endpoint is reached after adding exactly 31.25 mL of NaOH. What is the molarity of the HCl solution?',
      options: [
        { text: '0.125 M (M_a·V_a = M_b·V_b → M_a × 25.0 mL = 0.100 M × 31.25 mL → M_a = 3.125 / 25.0 = 0.125 M).', correct: true },
        { text: '0.080 M (dividing 25.0 by 31.25 and multiplying by 0.1).', correct: false },
        { text: '0.250 M (assuming HCl donates two hydronium ions per molecule).', correct: false },
        { text: '0.100 M (assuming acid and base concentrations must be identical at endpoint).', correct: false },
      ],
      learning_objective: 'Acid-base stoichiometry, molarity calculations (M₁V₁ = M₂V₂ for monoprotic systems), equivalence point detection, and volumetric analysis.',
      hint: 'In a 1:1 neutralization reaction (HCl + NaOH → NaCl + H₂O), moles of acid equal moles of base added at equivalence: M_acid × V_acid = M_base × V_base.',
      irt_a: 1.35,
      irt_b: 0.25,
      irt_c: 0.25,
      international_benchmark: 'PISA 2022 Science Literacy / Cambridge IGCSE Chemistry',
    },
    {
      scenario_code: 'C09-SCI-02',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'An astronaut on an unknown exoplanet drops a 1.5 kg rock from rest from the top of a 20-meter cliff. A high-speed telemetry camera records that the rock hits the ground exactly 2.0 seconds later. What is the acceleration due to gravity (g_exo) on this exoplanet, and how does it compare to Earth?',
      options: [
        { text: 'g_exo = 10.0 m/s² (Using d = ½gt² → 20 = ½g(2.0)² → 20 = 2g → g = 10.0 m/s², very close to Earth’s 9.81 m/s²).', correct: true },
        { text: 'g_exo = 5.0 m/s² (forgetting the factor of ½: d = gt²).', correct: false },
        { text: 'g_exo = 20.0 m/s² (dividing height directly by time: 20/2 = 10 m/s as velocity, then multiplying by 2).', correct: false },
        { text: 'g_exo = 1.62 m/s² (identical to Earth’s Moon).', correct: false },
      ],
      learning_objective: 'Kinematics in non-terrestrial gravitational fields, free fall equations (d = ½gt²), and observational measurement verification.',
      hint: 'Rearrange d = ½ g t² to solve for gravity: g = 2d / t² = 2(20) / (2)². Does the mass of the rock affect gravitational acceleration?',
      irt_a: 1.4,
      irt_b: 0.45,
      irt_c: 0.25,
      international_benchmark: 'TIMSS Advanced Physics Foundation / Cambridge IGCSE Physics',
    },
    {
      scenario_code: 'C09-SCI-03',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'A molecular genetics lab investigates the Meselson-Stahl experiment. E. coli bacteria grown for many generations in heavy isotope ¹⁵N medium are transferred to light ¹⁴N medium. After exactly ONE round of DNA replication, what density banding pattern is observed in a CsCl equilibrium density gradient centrifuge tube?',
      options: [
        { text: 'A single hybrid intermediate-density band (¹⁴N-¹⁵N), ruling out the conservative model of replication in favor of the semi-conservative model.', correct: true },
        { text: 'Two separate equal bands: one purely heavy (¹⁵N-¹⁵N) and one purely light (¹⁴N-¹⁴N).', correct: false },
        { text: 'A single purely light band (¹⁴N-¹⁴N), proving that old parental DNA strands are completely destroyed during synthesis.', correct: false },
        { text: 'No bands appear because isotopic nitrogen renders bacterial DNA invisible to UV light.', correct: false },
      ],
      learning_objective: 'Meselson-Stahl experiment, semi-conservative DNA replication mechanism, isotope centrifugation, and hypothesis discrimination.',
      hint: 'Semi-conservative replication means each new DNA molecule contains one original conserved strand (¹⁵N) and one newly synthesized strand (¹⁴N).',
      irt_a: 1.5,
      irt_b: 0.75,
      irt_c: 0.25,
      international_benchmark: 'USABO Semifinalist Prep / Singapore-Cambridge GCE O-Level Pure Biology',
    },
    {
      scenario_code: 'C09-SCI-04',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'A copper calorimeter of mass 150 g contains 200 g of water at 25.0°C. Steam at 100.0°C is bubbled into the water until the mixture reaches a final thermal equilibrium temperature of 60.0°C. Specific heat capacities: water = 4,184 J/(kg·K), copper = 385 J/(kg·K); Latent heat of vaporization of water L_v = 2.26 × 10⁶ J/kg. What mass of steam condensed?',
      options: [
        { text: 'Approximately 12.8 grams (Heat gained by water and calorimeter = (0.200 × 4184 × 35) + (0.150 × 385 × 35) = 29,288 + 2,021 = 31,309 J; Heat lost per gram of steam = L_v + c·ΔT = 2.26×10⁶ + (4184 × 40) = 2.427×10⁶ J/kg; m = 31,309 / 2.427×10⁶ ≈ 0.0129 kg = 12.9 g).', correct: true },
        { text: '31.3 grams (neglecting the massive latent heat of vaporization L_v).', correct: false },
        { text: '5.2 grams (accounting only for steam cooling without phase transition).', correct: false },
        { text: '150.0 grams (equal to the mass of the copper vessel).', correct: false },
      ],
      learning_objective: 'Calorimetry with phase transitions, latent heat of condensation (Q = m·L_v), thermal energy conservation, and multi-component equilibrium.',
      hint: 'Steam first releases its latent heat of condensation (m·L_v) as it turns from 100°C steam to 100°C liquid water, then releases sensible heat (m·c·ΔT) as it cools to 60°C.',
      irt_a: 1.55,
      irt_b: 0.95,
      irt_c: 0.25,
      international_benchmark: 'IJSO Physics Theory / US Physics Bowl Division 1',
    },
    {
      scenario_code: 'C09-SCI-05',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'A relativistic particle has rest mass m₀ = 1.67 × 10⁻²⁷ kg (proton) and moves through a synchrotron beamline with total relativistic energy E equal to 3 times its rest mass energy (E = 3 m₀c²). Taking c = 3.0 × 10⁸ m/s, what is the Lorentz factor γ, the particle’s speed v as a fraction of c, and its relativistic momentum p?',
      options: [
        { text: 'γ = 3.0; v = c√(1 - 1/γ²) = c√(1 - 1/9) = c√(8/9) ≈ 0.943 c; momentum p = γ·m₀·v = 3 × m₀ × 0.943c = 2.83 m₀c (or p = √(E² - (m₀c²)²)/c = √8 m₀c ≈ 2.828 m₀c).', correct: true },
        { text: 'γ = 9.0; v = 3.0 c (superluminal motion violating special relativity).', correct: false },
        { text: 'γ = 1.5; v = 0.50 c; momentum p = m₀c.', correct: false },
        { text: 'γ = 1.0; v = 0.999 c; momentum cannot be calculated because mass becomes infinite.', correct: false },
      ],
      learning_objective: 'Einstein’s Special Relativity, relativistic total energy (E = γm₀c²), Lorentz factor (γ = 1/√(1 - v²/c²)), and energy-momentum relation (E² = (pc)² + (m₀c²)²).',
      hint: 'Since E = γ·m₀c² and E = 3 m₀c², γ = 3. Solve 1/√(1 - v²/c²) = 3 for v/c. Then use p = √(E² - (m₀c²)²)/c.',
      irt_a: 1.65,
      irt_b: 1.25,
      irt_c: 0.25,
      international_benchmark: 'IPhO / US Physics Team F=ma Semifinalist / Russian Physics Olympiad',
    },
    {
      scenario_code: 'C09-SCI-06',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'In chemical equilibria, the Haber-Bosch ammonia synthesis is governed by: N₂(g) + 3 H₂(g) ⇌ 2 NH₃(g) with ΔH° = -92.4 kJ/mol (exothermic). At 450°C and 200 atm, the system is at dynamic equilibrium. According to Le Chatelier’s Principle and the van \'t Hoff equation, what simultaneous shifts occur to the equilibrium constant K_eq and the equilibrium yield of NH₃ if the reactor temperature is increased to 550°C at constant pressure?',
      options: [
        { text: 'K_eq decreases because the forward reaction is exothermic (d ln K / dT = ΔH° / RT² < 0); the equilibrium shifts left, reducing the equilibrium yield of NH₃ (though reaction rate increases kinetics).', correct: true },
        { text: 'K_eq increases because heating any chemical reaction always increases the equilibrium constant.', correct: false },
        { text: 'Yield of NH₃ increases to 100% because heat compresses gas molecules into ammonia liquid.', correct: false },
        { text: 'K_eq remains completely constant because temperature only affects solids, not gases.', correct: false },
      ],
      learning_objective: 'Thermodynamics of chemical equilibrium, Le Chatelier’s Principle, van \'t Hoff temperature dependence (d ln K/dT = ΔH°/RT²), and kinetics-thermodynamics industrial compromise.',
      hint: 'For an exothermic reaction (ΔH < 0), heat acts like a product on the right side of the equation. Adding heat drives the equilibrium backwards to the left, decreasing K_eq.',
      irt_a: 1.7,
      irt_b: 1.45,
      irt_c: 0.25,
      international_benchmark: 'International Chemistry Olympiad (IChO) / UK Chemistry Olympiad Round 1',
    },

    // 2. Computational Thinking (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C09-COM-01',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'A software engineer analyzes Quicksort with Lomuto partition scheme on an array of n distinct elements. What is the best-case time complexity, average-case time complexity, and worst-case time complexity when the input array is already sorted in ascending order and the last element is always chosen as pivot?',
      options: [
        { text: 'Best-case O(n log n), Average-case O(n log n), Worst-case O(n²) because choosing an extreme pivot creates maximally unbalanced partitions of size 0 and n-1 at each recursive level.', correct: true },
        { text: 'Best-case O(1), Average-case O(n), Worst-case O(n log n).', correct: false },
        { text: 'Quicksort always runs in O(n log n) regardless of pivot selection or input order.', correct: false },
        { text: 'Worst-case O(2ⁿ) due to infinite recursive function calls.', correct: false },
      ],
      learning_objective: 'Quicksort asymptotic analysis, pivot selection vulnerabilities, recurrence relations (T(n) = T(n-1) + O(n)), and partition degeneration.',
      hint: 'If the array is already sorted [1, 2, 3, 4, 5] and pivot is 5, partition produces [1, 2, 3, 4] and []. What is the sum 1 + 2 + ... + n?',
      irt_a: 1.35,
      irt_b: 0.3,
      irt_c: 0.25,
      international_benchmark: 'USACO Bronze Division / AP Computer Science A Algorithms',
    },
    {
      scenario_code: 'C09-COM-02',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'An operating system uses a semaphore with an initial counter value S = 3 to manage access to a pool of 3 database connections. Processes execute `wait(S)` to acquire a connection and `signal(S)` to release. If 7 processes sequentially call `wait(S)` and 2 processes subsequently call `signal(S)`, what is the final value of S, and how many processes remain blocked in the wait queue?',
      options: [
        { text: 'S = -2; exactly 2 processes remain blocked in the wait queue (Initial: 3; after 7 waits: 3 - 7 = -4 [4 blocked]; after 2 signals: -4 + 2 = -2 [2 remaining blocked]).', correct: true },
        { text: 'S = 0; zero processes are blocked because database connections are virtual.', correct: false },
        { text: 'S = 1; 3 processes are blocked.', correct: false },
        { text: 'The system deadlocks immediately because semaphores cannot hold negative values.', correct: false },
      ],
      learning_objective: 'Operating system concurrency primitives, counting semaphores (Dijkstra), mutual exclusion, and blocked process queue accounting.',
      hint: 'In a counting semaphore: each wait() decrements S by 1. When S is negative, |S| indicates the number of processes waiting in sleep queue. Each signal() increments S by 1.',
      irt_a: 1.4,
      irt_b: 0.5,
      irt_c: 0.25,
      international_benchmark: 'CSTA Level 3B Systems Concurrency / IEEE Computer Society High School',
    },
    {
      scenario_code: 'C09-COM-03',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'A Minimum Spanning Tree (MST) is computed on a connected, undirected weighted graph G with V = 1,000 vertices and E = 20,000 edges using Kruskal’s Algorithm with Disjoint Set Union (DSU) with union by rank and path compression. What is the time complexity of Kruskal’s algorithm, and what is the amortized cost per DSU find operation?',
      options: [
        { text: 'Overall time complexity O(E log E); DSU amortized cost is O(α(V)) per operation, where α is the inverse Ackermann function (effectively ≤ 4 for all realistic graphs).', correct: true },
        { text: 'Overall time complexity O(V²); DSU amortized cost is O(log V).', correct: false },
        { text: 'Overall time complexity O(V + E); DSU requires O(V) per operation.', correct: false },
        { text: 'Overall time complexity O(E²); DSU cannot be used on graphs with more than 100 vertices.', correct: false },
      ],
      learning_objective: 'Kruskal’s algorithm, Disjoint Set Union (DSU), path compression, union by rank, and inverse Ackermann complexity α(n).',
      hint: 'Sorting the edges takes O(E log E). DSU operations with both path compression and union-by-rank take nearly constant time bounded by the inverse Ackermann function.',
      irt_a: 1.5,
      irt_b: 0.85,
      irt_c: 0.25,
      international_benchmark: 'USACO Silver Division / Canadian Computing Competition Senior',
    },
    {
      scenario_code: 'C09-COM-04',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'In machine learning, a decision tree classifier suffers from high variance (severe overfitting on training data, poor generalization on test data). Which ensemble learning technique reduces variance without increasing bias by training multiple decorrelated trees on bootstrap sample subsets and randomly subsetting candidate split features at each node?',
      options: [
        { text: 'Random Forest (Bagging with random feature subspace projection, which reduces ensemble variance by a factor of 1/M when individual tree predictions are uncorrelated).', correct: true },
        { text: 'Single unpruned deep decision tree with zero regularization.', correct: false },
        { text: 'Gradient Boosted Decision Trees with an infinitely high learning rate.', correct: false },
        { text: 'Linear regression without intercept weights.', correct: false },
      ],
      learning_objective: 'Bias-variance tradeoff, ensemble learning theory, bootstrap aggregating (Bagging), and Random Forest decorrelation mechanisms.',
      hint: 'Averaging multiple independent high-variance estimators drastically reduces variance while preserving their low bias. What is this forest of trees called?',
      irt_a: 1.55,
      irt_b: 1.05,
      irt_c: 0.25,
      international_benchmark: 'Nature Hum. Soc. Sci. 2026 AI Pillar / Kaggle Master High School Division',
    },
    {
      scenario_code: 'C09-COM-05',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'In string pattern matching, the Knuth-Morris-Pratt (KMP) algorithm preprocesses a pattern P of length m to compute the failure function (Longest Proper Prefix which is also a Suffix, LPS array) in O(m) time, enabling linear O(n) text search without backtracking. For pattern P = "ABACABA", what is the exact LPS array?',
      options: [
        { text: '[0, 0, 1, 0, 1, 2, 3] (P[0]=\'A\': 0; P[0..1]="AB": 0; P[0..2]="ABA": 1 [\'A\']; P[0..3]="ABAC": 0; P[0..4]="ABACA": 1 [\'A\']; P[0..5]="ABACAB": 2 [\'AB\']; P[0..6]="ABACABA": 3 [\'ABA\']).', correct: true },
        { text: '[0, 1, 2, 3, 4, 5, 6] (assuming every prefix matches).', correct: false },
        { text: '[0, 0, 0, 0, 0, 0, 0] (assuming no prefixes match).', correct: false },
        { text: '[1, 2, 3, 1, 2, 3, 1] (repeating cyclic pattern).', correct: false },
      ],
      learning_objective: 'Knuth-Morris-Pratt (KMP) algorithm, LPS prefix-suffix array construction, deterministic finite automaton simulation, and linear-time string search.',
      hint: 'Look at the whole string "ABACABA": the longest prefix that is also a proper suffix is "ABA", which has length 3. So the last element must be 3.',
      irt_a: 1.65,
      irt_b: 1.35,
      irt_c: 0.25,
      international_benchmark: 'IOI Training / USACO Gold Division',
    },
    {
      scenario_code: 'C09-COM-06',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'In theoretical computer science, the P versus NP problem centers on whether every problem whose solution can be verified in polynomial time can also be solved in polynomial time. If an algorithm discovers a deterministic polynomial-time algorithm (O(n⁴)) for the 3-Satisfiability (3-SAT) problem, what profound mathematical theorem proves that P = NP?',
      options: [
        { text: 'The Cook-Levin Theorem, which establishes that 3-SAT is NP-Complete; since every problem in NP can be polynomial-time Karp-reduced to 3-SAT, solving 3-SAT in polynomial time solves all NP problems in polynomial time.', correct: true },
        { text: 'Turing’s Halting Theorem, proving that computers cannot run loops longer than 3 iterations.', correct: false },
        { text: 'Gödel’s Second Incompleteness Theorem, proving that polynomial algorithms cannot exist in arithmetic.', correct: false },
        { text: 'Shannon’s Source Coding Theorem, proving that NP problems have zero information entropy.', correct: false },
      ],
      learning_objective: 'Computational complexity theory, Cook-Levin Theorem, NP-Completeness, polynomial-time reductions (Karp reductions), and P vs. NP implications.',
      hint: 'The Cook-Levin theorem showed that SAT is NP-Complete. An NP-Complete problem is as hard as ANY problem in the entire NP class.',
      irt_a: 1.7,
      irt_b: 1.55,
      irt_c: 0.25,
      international_benchmark: 'ACM Turing Scholar High School / Clay Mathematics Millennium Problems Education',
    },

    // 3. Engineering Design (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C09-ENG-01',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'An electrical engineer designs an inverting operational amplifier (Op-Amp) circuit using an ideal op-amp. The input resistor is R_in = 10 kΩ and the feedback resistor is R_f = 100 kΩ. The non-inverting (+) terminal is tied to ground. If an input signal V_in = +0.50 V is applied, what is the output voltage V_out, and what fundamental op-amp rule determines the inverting terminal voltage?',
      options: [
        { text: 'V_out = -5.0 V (Gain A_v = -R_f/R_in = -100k/10k = -10; V_out = -10 × 0.50V = -5.0V); virtual ground rule keeps inverting (-) terminal at 0.0V.', correct: true },
        { text: 'V_out = +5.0 V (positive non-inverting amplification).', correct: false },
        { text: 'V_out = -0.05 V (dividing input by gain).', correct: false },
        { text: 'V_out = 0.0 V (the virtual ground grounds out the output completely).', correct: false },
      ],
      learning_objective: 'Operational amplifier circuits, inverting amplifier gain equation (V_out = -(R_f/R_in)V_in), virtual ground concept, and negative feedback operation.',
      hint: 'Inverting amplifier gain is simply -R_feedback / R_input. Multiply this negative gain by the input voltage +0.5V.',
      irt_a: 1.35,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'IEEE Circuits & Systems Society / Cambridge A-Level Electronics Foundation',
    },
    {
      scenario_code: 'C09-ENG-02',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'In structural engineering, a rectangular timber beam of width b = 10 cm and depth d = 30 cm is loaded in vertical bending. The second moment of area (area moment of inertia) about its neutral centroidal axis is given by I = (b·d³)/12. If an inexperienced builder accidentally installs the beam on its flat side (width b = 30 cm, depth d = 10 cm), by what factor is the beam\'s bending stiffness (resistance to deflection) degraded?',
      options: [
        { text: 'Stiffness is reduced by a factor of 9 (I_upright = (10 × 30³)/12 = 22,500 cm⁴; I_flat = (30 × 10³)/12 = 2,500 cm⁴; 22,500 / 2,500 = 9.0; or simply (d_upright / d_flat)² = (30/10)² = 9).', correct: true },
        { text: 'Stiffness is reduced by a factor of 3 (linearly proportional to depth).', correct: false },
        { text: 'Stiffness is identical because total cross-sectional area (300 cm²) is unchanged.', correct: false },
        { text: 'Stiffness increases by a factor of 3 because wider beams catch more floorboards.', correct: false },
      ],
      learning_objective: 'Euler-Bernoulli beam theory, second moment of area (I = bd³/12), bending stress, and structural orientation optimization.',
      hint: 'Notice depth "d" is cubed in the formula: (b·d³)/12. Cubing 30 gives 27,000, whereas cubing 10 gives only 1,000.',
      irt_a: 1.4,
      irt_b: 0.55,
      irt_c: 0.25,
      international_benchmark: 'ASCE Civil Engineering Body of Knowledge / FIRST Tech Challenge Structural Design',
    },
    {
      scenario_code: 'C09-ENG-03',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'A geothermal binary-cycle power plant operates on an Organic Rankine Cycle (ORC) using isobutane as working fluid between boiler temperature T_high = 160°C (433.15 K) and condenser cooling water T_low = 25°C (298.15 K). What is the maximum theoretical Carnot thermal efficiency (η_Carnot) achievable, and why does an actual ORC power plant achieve an operational efficiency of only ~12-14%?',
      options: [
        { text: 'η_Carnot = 1 - (T_low / T_high) = 1 - (298.15 / 433.15) ≈ 31.2%; actual efficiency is lower due to turbine isentropic losses, pump parasitic power, pinch-point heat exchange ΔT losses, and organic fluid superheating limits.', correct: true },
        { text: 'η_Carnot = 84.4% (calculating with Celsius temperatures: 1 - 25/160); actual efficiency drops because geothermal steam is radioactive.', correct: false },
        { text: 'η_Carnot = 100%; Rankine cycles have zero thermodynamic entropy generation.', correct: false },
        { text: 'η_Carnot = 5.0%; geothermal energy is physically incapable of exceeding single-digit efficiencies.', correct: false },
      ],
      learning_objective: 'Carnot efficiency limit (η = 1 - T_C/T_H with absolute temperatures in Kelvin), Second Law of Thermodynamics, and real Rankine cycle irreversibilities.',
      hint: 'Remember thermodynamic efficiency MUST always use absolute temperature in Kelvin (Kelvin = Celsius + 273.15).',
      irt_a: 1.5,
      irt_b: 0.9,
      irt_c: 0.25,
      international_benchmark: 'ASME Student Energy Design Competition / UN SDG 7 Affordable & Clean Energy',
    },
    {
      scenario_code: 'C09-ENG-04',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'In designing an active suspension system for a military autonomous ground vehicle, engineers model the quarter-car suspension using a 2-DOF state-space system: ẋ = Ax + Bu, y = Cx + Du. To verify whether the suspension actuators can drive the vehicle body and wheel states to any arbitrary equilibrium from any initial condition, which mathematical matrix rank condition must be evaluated?',
      options: [
        { text: 'Kalman Controllability Matrix rank condition: the controllability matrix C_o = [B | AB | A²B | ... | Aⁿ⁻¹B] must have full row rank equal to system order n (rank = n).', correct: true },
        { text: 'The determinant of matrix A must equal zero.', correct: false },
        { text: 'The matrix B must be an identity matrix with negative diagonal elements.', correct: false },
        { text: 'The matrix D must be greater than the speed of sound in steel.', correct: false },
      ],
      learning_objective: 'Modern state-space control theory, Kalman controllability criterion, matrix rank, and active vehicle dynamics.',
      hint: 'Kalman proved that a linear system is controllable if and only if the controllability matrix [B, AB, A²B... Aⁿ⁻¹B] has full rank n.',
      irt_a: 1.55,
      irt_b: 1.1,
      irt_c: 0.25,
      international_benchmark: 'IEEE Control Systems Society High School / ASME Dynamic Systems & Control',
    },
    {
      scenario_code: 'C09-ENG-05',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'In an N-channel enhancement-mode MOSFET operating in saturation mode, the drain current is modeled by: I_D = ½ μ_n·C_ox·(W/L)·(V_GS - V_th)²·(1 + λ·V_DS). If the gate-to-source voltage is V_GS = 2.5 V, threshold voltage V_th = 0.7 V, channel length modulation parameter λ ≈ 0, and process transconductance parameter k\' = μ_n·C_ox = 200 μA/V², what channel aspect ratio (W/L) is required to establish a saturation drain current I_D = 3.24 mA?',
      options: [
        { text: 'W/L = 10 (I_D = ½ × (200 × 10⁻⁶ A/V²) × (W/L) × (2.5 - 0.7)²; 3.24 × 10⁻³ = 10⁻⁴ × (W/L) × 1.8²; 3.24 × 10⁻³ = 10⁻⁴ × (W/L) × 3.24; W/L = 3.24×10⁻³ / (3.24×10⁻⁴) = 10).', correct: true },
        { text: 'W/L = 50 (forgetting the factor of ½ in the saturation current formula).', correct: false },
        { text: 'W/L = 1.8 (equal to the overdrive voltage).', correct: false },
        { text: 'W/L = 100 (multiplying by threshold voltage).', correct: false },
      ],
      learning_objective: 'Semiconductor physics, MOSFET square-law saturation equation, overdrive voltage (V_GS - V_th), and channel geometry aspect ratio sizing.',
      hint: 'Overdrive voltage V_ov = V_GS - V_th = 2.5 - 0.7 = 1.8 V. Square it: 1.8² = 3.24. Notice how neatly 3.24 cancels with the target current 3.24 mA!',
      irt_a: 1.65,
      irt_b: 1.4,
      irt_c: 0.25,
      international_benchmark: 'IEEE Solid-State Circuits Society / International Microelectronics Olympiad',
    },
    {
      scenario_code: 'C09-ENG-06',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'A supersonic ramjet combustion chamber operates at Mach 2.8 with an inlet total pressure of 1.2 MPa. Combustion adds heat to the supersonic stream inside a constant-area duct (Rayleigh flow). As heat is added, Mach number decreases toward Mach 1.0. What catastrophic aerodynamic phenomenon occurs if too much fuel is injected and heat addition exceeds the maximum allowable Rayleigh thermal choke limit (q > q_max)?',
      options: [
        { text: 'Thermal choking: the flow chokes at M = 1 at duct exit, forcing a normal shock wave to detach and propagate upstream out of the engine intake ("engine unstart"), causing violent thrust loss, pressure spikes, and vehicle destabilization.', correct: true },
        { text: 'The fuel spontaneously freezes into solid ice diamonds inside the injector nozzles.', correct: false },
        { text: 'The rocket accelerates to the speed of light within 1 microsecond.', correct: false },
        { text: 'The engine switches silently into a frictionless magnetic levitation glider.', correct: false },
      ],
      learning_objective: 'Rayleigh flow with heat addition, thermal choking limits, normal shock expulsion ("engine unstart"), and supersonic air-breathing propulsion.',
      hint: 'Adding heat to a supersonic flow decelerates it toward Mach 1. If you add more heat than the flow can handle at Mach 1, the engine can no longer swallow the air, coughing up a shock wave.',
      irt_a: 1.7,
      irt_b: 1.6,
      irt_c: 0.25,
      international_benchmark: 'AIAA High-Speed Air-Breathing Propulsion / National Aerospace Competition',
    },

    // 4. Mathematical Reasoning (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C09-MAT-01',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'Prove and evaluate the exact trigonometric expression: \nsin(75°) × cos(15°). \nUsing angle addition formulas or product-to-sum identities (sin A cos B = ½[sin(A+B) + sin(A-B)]), what is the exact radical value of this product?',
      options: [
        { text: '(2 + √3) / 4 (Product-to-sum: ½[sin(75°+15°) + sin(75°-15°)] = ½[sin(90°) + sin(60°)] = ½[1 + √3/2] = ½[(2 + √3)/2] = (2 + √3)/4 ≈ 0.933).', correct: true },
        { text: '√3 / 2 (assuming cos 15° = 1).', correct: false },
        { text: '¼ (neglecting the radical term).', correct: false },
        { text: '(√6 + √2) / 4 (the value of sin 75° alone).', correct: false },
      ],
      learning_objective: 'Trigonometric product-to-sum identities (sin A cos B = ½[sin(A+B)+sin(A-B)]), exact values for special angles (60°, 90°), and algebraic radicals.',
      hint: 'Apply the identity: sin(A) cos(B) = ½ [sin(A+B) + sin(A-B)]. A+B = 90° and A-B = 60°.',
      irt_a: 1.35,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'PISA 2022 Mathematics / Cambridge IGCSE Additional Mathematics',
    },
    {
      scenario_code: 'C09-MAT-02',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'A standard deck of 52 playing cards is dealt to form a 5-card poker hand. How many distinct hands contain a "Full House" (3 cards of one rank and 2 cards of another rank, e.g., three Kings and two 7s)?',
      options: [
        { text: '3,744 hands (Choose rank for triple: C(13,1) = 13; choose 3 suits: C(4,3) = 4; choose different rank for pair: C(12,1) = 12; choose 2 suits: C(4,2) = 6; Total = 13 × 4 × 12 × 6 = 3,744).', correct: true },
        { text: '1,248 hands (forgetting to choose the suits for the pair: C(4,2)).', correct: false },
        { text: '5,108 hands (the count of Flush hands).', correct: false },
        { text: '13 × 12 = 156 hands (choosing only the card ranks).', correct: false },
      ],
      learning_objective: 'Combinatorics, combination notation C(n, k), poker probability distributions, and multi-stage counting principles.',
      hint: 'First pick the rank for the 3-of-a-kind (13 choices) and its 3 suits (4 choices). Then pick the rank for the pair (12 choices) and its 2 suits (4×3/2 = 6 choices). Multiply them.',
      irt_a: 1.4,
      irt_b: 0.55,
      irt_c: 0.25,
      international_benchmark: 'AMC 10 / Singapore Mathematical Olympiad Junior',
    },
    {
      scenario_code: 'C09-MAT-03',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'In the complex plane, let z = 1 + i√3. Using Euler’s formula (z = r·e^(iθ)) or De Moivre’s Theorem, what is the exact value of z¹²?',
      options: [
        { text: '4,096 (Modulus r = √(1² + (√3)²) = √4 = 2; Argument θ = arctan(√3/1) = π/3 (60°); z¹² = r¹² e^(i·12·π/3) = 2¹² e^(i·4π) = 4096 × 1 = 4,096).', correct: true },
        { text: '-4,096 i (assuming 4π equals 3π/2).', correct: false },
        { text: '2,048 + 2,048 i√3 (multiplying modulus without applying exponent to angle).', correct: false },
        { text: '1 + 4,096 i (raising real and imaginary parts separately).', correct: false },
      ],
      learning_objective: 'Complex numbers in polar form, modulus-argument representation, De Moivre’s Theorem ((r e^(iθ))^n = r^n e^(inθ)), and trigonometric periodicity.',
      hint: 'Find modulus r = 2 and argument θ = 60° (π/3). When raised to power 12: r¹² = 2¹² = 4096, and the angle becomes 12 × 60° = 720° (which is two full circles, back to 0°).',
      irt_a: 1.5,
      irt_b: 0.9,
      irt_c: 0.25,
      international_benchmark: 'AMC 10/12 / Cambridge International AS & A Level Mathematics',
    },
    {
      scenario_code: 'C09-MAT-04',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'Find the number of integral solutions (x, y, z) to the equation: \nx + y + z = 18 \nsuch that x ≥ 2, y ≥ 3, and z ≥ 1. How does the "Stars and Bars" combinatorial method solve this with constrained lower bounds?',
      options: [
        { text: '91 solutions (Substitute x\' = x - 2 ≥ 0, y\' = y - 3 ≥ 0, z\' = z - 1 ≥ 0; then x\' + y\' + z\' = 18 - 2 - 3 - 1 = 12. By Stars and Bars formula C(n + k - 1, k - 1) = C(12 + 3 - 1, 3 - 1) = C(14, 2) = (14 × 13)/2 = 91).', correct: true },
        { text: '190 solutions (using unconstrained C(18 + 3 - 1, 2) = C(20, 2) = 190).', correct: false },
        { text: '136 solutions (C(16, 2)).', correct: false },
        { text: '45 solutions (C(10, 2)).', correct: false },
      ],
      learning_objective: 'Combinatorics, Stars and Bars theorem (compositions of integers), variable change for boundary offsets, and binomial coefficients.',
      hint: 'First give 2 to x, 3 to y, and 1 to z (total 6 items used). That leaves 18 - 6 = 12 items to distribute freely among 3 variables: C(12 + 3 - 1, 3 - 1) = C(14, 2).',
      irt_a: 1.55,
      irt_b: 1.1,
      irt_c: 0.25,
      international_benchmark: 'AIME Qualifier / AMC 10 Distinction',
    },
    {
      scenario_code: 'C09-MAT-05',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'Let f(x) be a polynomial with integer coefficients such that f(1) = 5 and f(7) = 23. Using the polynomial remainder divisibility lemma (for any integer polynomial, (a - b) divides (f(a) - f(b))), which of the following could potentially be the integer value of f(19)?',
      options: [
        { text: '59 (Divisibility requirements: (19 - 1) = 18 must divide f(19) - 5; and (19 - 7) = 12 must divide f(19) - 23. For 59: 59 - 5 = 54 (divisible by 18, 54/18 = 3); and 59 - 23 = 36 (divisible by 12, 36/12 = 3). Both hold!).', correct: true },
        { text: '50 (50 - 5 = 45, not divisible by 18).', correct: false },
        { text: '72 (72 - 5 = 67, prime and not divisible by 18).', correct: false },
        { text: '41 (41 - 23 = 18, not divisible by 12).', correct: false },
      ],
      learning_objective: 'Integer polynomial properties, (a - b) | (P(a) - P(b)) divisibility lemma, modular congruence constraints, and Diophantine analysis.',
      hint: 'Test each option: f(19) - 5 must be a multiple of 18 (19-1), AND f(19) - 23 must be a multiple of 12 (19-7). Check 59.',
      irt_a: 1.65,
      irt_b: 1.4,
      irt_c: 0.25,
      international_benchmark: 'USAMO Junior / Canadian Mathematical Olympiad / Tournament of Towns',
    },
    {
      scenario_code: 'C09-MAT-06',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'In a convex cyclic quadrilateral ABCD inscribed in a circle, side lengths are AB = 2, BC = 3, CD = 4, and DA = 5. Using Brahmagupta’s formula (Area = √[(s-a)(s-b)(s-c)(s-d)]), what is the exact area of quadrilateral ABCD, and what condition allows this formula to apply?',
      options: [
        { text: 'Area = 2√30 (Semi-perimeter s = (2+3+4+5)/2 = 7; Area = √[(7-2)(7-3)(7-4)(7-5)] = √[5 × 4 × 3 × 2] = √120 = 2√30 ≈ 10.954); applies because the quadrilateral is concyclic (inscribed in a circle).', correct: true },
        { text: 'Area = 14 (assuming the quadrilateral is a rectangle).', correct: false },
        { text: 'Area = 30 (multiplying (s-a)(s-b)... without square root).', correct: false },
        { text: 'Area = 5√6 (arithmetic error under radical).', correct: false },
      ],
      learning_objective: 'Brahmagupta’s formula for cyclic quadrilaterals, semi-perimeter derivation, Ptolemy’s theorem context, and exact radical geometry.',
      hint: 'Find semi-perimeter s = (2+3+4+5)/2 = 7. Subtract each side from 7: (5, 4, 3, 2). Multiply them together under the square root: √(5×4×3×2) = √120.',
      irt_a: 1.7,
      irt_b: 1.6,
      irt_c: 0.25,
      international_benchmark: 'IMO Foundation / Harvard-MIT Mathematics Tournament (HMMT)',
    },

    // 5. Systems Thinking (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C09-SYS-01',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'In modern semiconductor manufacturing, lithography fab lines operate with statistical process control (SPC). If a wafer manufacturing step has an upper specification limit (USL) and lower specification limit (LSL), what does a Process Capability Index C_pk = 1.67 signify to quality engineering systems?',
      options: [
        { text: 'The process operates at Six Sigma quality (process distribution width 6σ is well within tolerance band with virtually zero defective parts per million, PPM < 0.6).', correct: true },
        { text: '1.67% of all manufactured microchips will fail during the first month.', correct: false },
        { text: 'The factory must immediately shut down all cleanrooms for chemical decontamination.', correct: false },
        { text: 'Process variance is completely random and cannot be modeled mathematically.', correct: false },
      ],
      learning_objective: 'Statistical Process Control (SPC), Process Capability Index (C_pk), Six Sigma manufacturing quality, and defect ppm reduction.',
      hint: 'A C_pk of 1.0 means the 3-sigma curve just touches the spec limits (~0.27% defect). A C_pk of 1.67 means 5-sigma margin, indicating world-class precision.',
      irt_a: 1.35,
      irt_b: 0.35,
      irt_c: 0.25,
      international_benchmark: 'IEEE Semiconductor Manufacturing / ASQ Quality Engineering Certification Primer',
    },
    {
      scenario_code: 'C09-SYS-02',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'A municipal electric utility implements Dynamic Time-of-Use (TOU) electricity pricing. Rates are $0.08/kWh from 11 PM - 7 AM (off-peak), $0.16/kWh from 7 AM - 4 PM (mid-peak), and $0.45/kWh from 4 PM - 9 PM (critical peak). In systems dynamics, what structural archetype does TOU pricing leverage to mitigate the utility’s evening "Duck Curve"?',
      options: [
        { text: 'Price elasticity of demand feedback: high peak prices incentivize automated smart thermostats and EV chargers to shift discretionary electrical load away from peak solar drop-off hours.', correct: true },
        { text: 'Tragedy of the Commons: forcing all consumers to permanently disconnect from the grid.', correct: false },
        { text: 'Unregulated positive feedback: driving electrical consumption to infinity during peak hours.', correct: false },
        { text: 'Planned obsolescence: causing air conditioning compressors to mechanically fail at 4 PM.', correct: false },
      ],
      learning_objective: 'California Duck Curve power dynamics, demand-side management, dynamic TOU pricing feedback, and grid load-shifting.',
      hint: 'When rooftop solar drops as the sun sets while families return home, electricity demand spikes vertically. Raising prices during those exact hours convinces machines to run later at night.',
      irt_a: 1.4,
      irt_b: 0.55,
      irt_c: 0.25,
      international_benchmark: 'Nature Hum. Soc. Sci. 2026 Smart Systems / IEEE Power Engineering',
    },
    {
      scenario_code: 'C09-SYS-03',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In synthetic biology and genetic circuit design, a "Repressilator" consists of three genes (tetR, lacI, and cI) connected in a cyclic negative feedback loop where Protein A represses Gene B, Protein B represses Gene C, and Protein C represses Gene A. Under what kinetic parameter conditions does this synthetic gene regulatory network exhibit sustained limit-cycle oscillations rather than dampening to a stable steady state?',
      options: [
        { text: 'High cooperativity (Hill coefficient n > 2 in transcriptional repression), balanced protein/mRNA degradation rates, and sufficient transcriptional delay/gain.', correct: true },
        { text: 'Complete absence of any cellular ribosomes.', correct: false },
        { text: 'Hill coefficient n = 0, meaning repression is completely independent of repressor concentration.', correct: false },
        { text: 'Instantaneous infinite degradation of all mRNA transcripts within 1 femtosecond.', correct: false },
      ],
      learning_objective: 'Synthetic biology gene regulatory circuits, Repressilator design (Elowitz & Leibler), limit cycle oscillations, and nonlinear Hill kinetics.',
      hint: 'To get a sustained biological clock oscillation rather than settling down, repression must be steep and cooperative (high Hill coefficient n > 2) with time delays.',
      irt_a: 1.5,
      irt_b: 0.95,
      irt_c: 0.25,
      international_benchmark: 'iGEM (International Genetically Engineered Machine) High School / Nature Biotechnology',
    },
    {
      scenario_code: 'C09-SYS-04',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In urban climate science, the "Urban Heat Island" (UHI) effect elevates metropolitan temperatures by 3-8°C above surrounding rural landscapes. Which multi-system intervention matrix provides the most synergistic cooling by addressing both sensible heat flux and latent heat flux simultaneously?',
      options: [
        { text: 'High-albedo "cool roofs" (increasing solar reflectance to reduce sensible heat absorption) paired with extensive urban tree canopy and bioswales (maximizing latent heat dissipating evapotranspiration).', correct: true },
        { text: 'Installing 10,000 outdoor air-conditioning chiller fans blasting heat directly into downtown sidewalks.', correct: false },
        { text: 'Paving all city parks with dark asphalt to absorb heat deep into underground bedrock.', correct: false },
        { text: 'Erecting giant glass mirrors around city borders to block natural wind ventilation.', correct: false },
      ],
      learning_objective: 'Urban climatology, sensible vs. latent heat flux partitioning, albedo surface physics, and urban nature-based resilience engineering.',
      hint: 'Cool roofs reflect sunlight before it turns into heat (sensible heat), while living plants use solar energy to evaporate water vapor, chilling the air (latent heat).',
      irt_a: 1.55,
      irt_b: 1.15,
      irt_c: 0.25,
      international_benchmark: 'UN SDG 11 Sustainable Cities / IPCC Working Group II Urban Climate Systems',
    },
    {
      scenario_code: 'C09-SYS-05',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In modern macroeconomic modeling, the New Keynesian Dynamic Stochastic General Equilibrium (DSGE) model couples three core equations: (1) Forward-looking Investment-Saving (IS) curve, (2) New Keynesian Phillips Curve (NKPC), and (3) Monetary Policy Taylor Rule: i_t = r* + π_t + 0.5(π_t - π*) + 0.5(y_t - y*). According to the "Taylor Principle", what mathematical condition on the monetary response coefficient to inflation (ϕ_π) is required to guarantee determinacy (a unique, non-explosive rational expectations equilibrium)?',
      options: [
        { text: 'ϕ_π > 1 (The central bank must raise the nominal interest rate more than one-for-one with increases in inflation, ensuring that the REAL interest rate rises to cool aggregate demand).', correct: true },
        { text: 'ϕ_π = 0 (Interest rates must remain completely fixed regardless of inflation).', correct: false },
        { text: 'ϕ_π < -1 (Central banks should cut interest rates aggressively whenever inflation surges).', correct: false },
        { text: 'Determinacy in rational expectations models is mathematically independent of central bank policy.', correct: false },
      ],
      learning_objective: 'New Keynesian DSGE macroeconomic modeling, Taylor Rule, Taylor Principle (ϕ_π > 1), real interest rate transmission, and rational expectations determinacy.',
      hint: 'If inflation rises by 1%, the central bank must raise nominal interest rates by MORE than 1% so that the real interest rate (r = i - π) actually rises to dampen borrowing.',
      irt_a: 1.65,
      irt_b: 1.45,
      irt_c: 0.25,
      international_benchmark: 'International Economics Olympiad / MIT System Dynamics Macroeconomics Group',
    },
    {
      scenario_code: 'C09-SYS-06',
      class_level: 9,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In nonlinear dynamics and chaos theory, the Lorenz system: dx/dt = σ(y - x), dy/dt = x(ρ - x) - y, dz/dt = xy - βz exhibits deterministic chaos for classical parameters σ=10, β=8/3, ρ=28. The trajectories in phase space are attracted to a strange attractor with fractional Hausdorff dimension d ≈ 2.06. What is the fundamental physical implication of a positive maximal Lyapunov exponent (λ_max > 0) in this system?',
      options: [
        { text: 'Sensitive dependence on initial conditions ("Butterfly Effect"): nearby trajectories in phase space diverge exponentially at rate e^(λt), rendering long-term deterministic forecasting fundamentally impossible despite deterministic governing equations.', correct: true },
        { text: 'The system collapses into a static stationary point at the origin (0, 0, 0) within finite time.', correct: false },
        { text: 'Trajectories form perfectly closed periodic circles with constant orbital velocity.', correct: false },
        { text: 'The system violates the conservation of energy by generating infinite kinetic energy.', correct: false },
      ],
      learning_objective: 'Deterministic chaos, Lorenz strange attractor, Lyapunov exponents, phase space trajectories, and limits of deterministic predictability.',
      hint: 'A positive Lyapunov exponent means that two starting points separated by a microscopic distance δx₀ will diverge apart as δx(t) ≈ δx₀ · e^(λt).',
      irt_a: 1.7,
      irt_b: 1.65,
      irt_c: 0.25,
      international_benchmark: 'Santa Fe Institute Complex Systems Scholar / European Physics Olympiad Advanced Theory',
    },

    // ═════════════════════════════════════════════════════════════════════════
    // CLASS 10 (Grade 10 · Developmental Band 9-10) - 30 Unique Questions
    // ═════════════════════════════════════════════════════════════════════════

    // 1. Scientific Inquiry (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C10-SCI-01',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'An analytical chemist measures the standard cell potential (E°_cell) of a galvanic Daniell cell: Zn(s) | Zn²⁺(1.0 M) || Cu²⁺(1.0 M) | Cu(s). Standard reduction potentials: Cu²⁺ + 2e⁻ → Cu(s) (E° = +0.34 V); Zn²⁺ + 2e⁻ → Zn(s) (E° = -0.76 V). What is the standard cell potential E°_cell and the standard Gibbs free energy change (ΔG°), taking Faraday\'s constant F = 96,485 C/mol?',
      options: [
        { text: 'E°_cell = +1.10 V; ΔG° = -nFE° = -2 × 96,485 × 1.10 = -212.3 kJ/mol (spontaneous electrochemical reaction).', correct: true },
        { text: 'E°_cell = -0.42 V; ΔG° = +81.1 kJ/mol (non-spontaneous).', correct: false },
        { text: 'E°_cell = +0.42 V; ΔG° = -40.5 kJ/mol.', correct: false },
        { text: 'E°_cell = +1.10 V; ΔG° = +212.3 kJ/mol (requiring continuous external electrical power).', correct: false },
      ],
      learning_objective: 'Electrochemistry, galvanic Daniell cell, standard reduction potentials (E°_cell = E°_cathode - E°_anode), and Gibbs free energy relation (ΔG° = -nFE°).',
      hint: 'E°_cell = E°_reduction(cathode) - E°_reduction(anode) = +0.34 - (-0.76) = +1.10 V. Plug into ΔG° = -n F E° with n = 2 electrons transferred.',
      irt_a: 1.35,
      irt_b: 0.45,
      irt_c: 0.25,
      international_benchmark: 'PISA 2022 Science Advanced / Cambridge IGCSE / GCE O-Level Chemistry',
    },
    {
      scenario_code: 'C10-SCI-02',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'standard',
      prompt: 'A physics student directs a monochromatic green laser (λ = 532 nm) through a double slit with slit separation d = 0.20 mm onto a projection screen placed L = 2.0 meters away. What is the fringe spacing (distance Δy between adjacent bright constructive interference fringes on the screen)?',
      options: [
        { text: '5.32 mm (Using Young’s double slit formula Δy = (λ·L)/d = (532 × 10⁻⁹ m × 2.0 m) / (0.20 × 10⁻³ m) = 1.064 × 10⁻⁶ / 2.0 × 10⁻⁴ = 5.32 × 10⁻³ m = 5.32 mm).', correct: true },
        { text: '1.06 mm (dividing by 10).', correct: false },
        { text: '10.64 mm (forgetting to divide by slit separation).', correct: false },
        { text: '0.53 mm (unit conversion error from nanometers to meters).', correct: false },
      ],
      learning_objective: 'Wave optics, Young’s double-slit experiment, interference fringe width derivation (Δy = λL/d), and wave-particle duality evidence.',
      hint: 'Fringe spacing formula is Δy = (λ × L) / d. Make sure all units are converted to meters before calculating: 532×10⁻⁹ m, 2.0 m, 0.20×10⁻³ m.',
      irt_a: 1.4,
      irt_b: 0.65,
      irt_c: 0.25,
      international_benchmark: 'TIMSS Advanced Physics / Cambridge International A-Level Physics Foundation',
    },
    {
      scenario_code: 'C10-SCI-03',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'In organic chemistry, 2-bromo-2-methylpropane undergoes nucleophilic substitution in aqueous ethanol to form 2-methylpropan-2-ol. Kinetic measurements show that doubling the concentration of alkyl halide doubles the reaction rate, but doubling the concentration of hydroxide nucleophile has zero effect on the rate (Rate = k[R-Br]¹[OH⁻]⁰). What reaction mechanism is occurring, and what is the rate-determining step?',
      options: [
        { text: 'S_N1 mechanism (unimolecular nucleophilic substitution): the slow rate-determining step is heterolytic dissociation of the C-Br bond forming a stable tertiary carbocation intermediate.', correct: true },
        { text: 'S_N2 mechanism (bimolecular nucleophilic substitution): backside attack with a pentacoordinate transition state.', correct: false },
        { text: 'E2 elimination forming 2-methylpropene gas exclusively.', correct: false },
        { text: 'Free-radical halogenation catalyzed by ambient room ultraviolet light.', correct: false },
      ],
      learning_objective: 'Reaction mechanisms in organic chemistry, S_N1 vs S_N2 kinetics, carbocation intermediate stability, and rate-determining steps.',
      hint: 'Because the rate depends ONLY on the alkyl halide concentration and NOT on the nucleophile (Rate = k[substrate]), it must be unimolecular (S_N1).',
      irt_a: 1.5,
      irt_b: 0.95,
      irt_c: 0.25,
      international_benchmark: 'USNCO Local / National Chemistry Olympiad Prep / Singapore GCE A-Level H2 Chemistry',
    },
    {
      scenario_code: 'C10-SCI-04',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'advanced',
      prompt: 'A uniform solid cylinder of mass M and radius R rolls without slipping down an incline of angle θ from height h. Its moment of inertia is I = ½MR². Using conservation of mechanical energy (Mgh = ½Mv² + ½Iω²) and the rolling constraint (v = ωR), what is the translational acceleration of the cylinder down the incline?',
      options: [
        { text: 'a = ⅔ g·sin(θ) (Total kinetic energy = ½Mv² + ½(½MR²)(v/R)² = ¾Mv²; applying Newton’s 2nd law or energy: acceleration = g·sin(θ) / (1 + I/MR²) = g·sin(θ) / (1 + 0.5) = ⅔ g·sin(θ)).', correct: true },
        { text: 'a = g·sin(θ) (identical to a frictionless sliding block).', correct: false },
        { text: 'a = ½ g·sin(θ) (assuming rotational kinetic energy equals translational energy).', correct: false },
        { text: 'a = ¾ g·sin(θ).', correct: false },
      ],
      learning_objective: 'Rotational dynamics, rolling without slipping, rotational kinetic energy (½Iω²), and angular acceleration down an inclined plane.',
      hint: 'Because some potential energy converts into rotational kinetic energy rather than translational motion, rolling objects accelerate slower than frictionless sliders: a = g sin(θ) / (1 + I/(MR²)).',
      irt_a: 1.55,
      irt_b: 1.15,
      irt_c: 0.25,
      international_benchmark: 'AAPF US Physics Bowl / F=ma Contest / Singapore Physics Olympiad',
    },
    {
      scenario_code: 'C10-SCI-05',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'In molecular orbital (MO) theory, the oxygen molecule (O₂) exhibits paramagnetism (it is attracted into magnetic field gradients). Why does Lewis valence-bond structure (:Ö=Ö:) fail to explain this magnetic property, and how does the MO electron configuration of O₂ resolve it?',
      options: [
        { text: 'Lewis structures show all electrons paired in bonds or lone pairs (diamagnetic); MO theory shows that filling the highest occupied molecular orbitals results in two unpaired electrons with parallel spins in the degenerate antibonding π*₂p_x and π*₂p_y orbitals (Hund’s rule).', correct: true },
        { text: 'Lewis structures predict oxygen contains metallic iron impurities that align with magnets.', correct: false },
        { text: 'MO theory proves that oxygen molecules have zero electrons in their valence shell.', correct: false },
        { text: 'Paramagnetism is caused exclusively by nuclear spin states that molecular orbitals ignore.', correct: false },
      ],
      learning_objective: 'Molecular Orbital (MO) theory, paramagnetism vs. diamagnetism, degenerate π* antibonding orbitals, Hund’s rule of maximum multiplicity, and failure of Lewis structures.',
      hint: 'Liquid oxygen sticks between the poles of a strong magnet! Lewis structures show all paired electrons, but MO theory reveals two lonely unpaired electrons in the π* antibonding level.',
      irt_a: 1.65,
      irt_b: 1.5,
      irt_c: 0.25,
      international_benchmark: 'International Chemistry Olympiad (IChO) / US National Chemistry Olympiad (USNCO)',
    },
    {
      scenario_code: 'C10-SCI-06',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'scientificInquiry',
      difficulty: 'olympiad',
      prompt: 'A particle of mass m is trapped in a one-dimensional infinite square potential well of width L (V(x) = 0 for 0 < x < L, and V(x) = ∞ otherwise). By solving the time-independent Schrödinger equation (-ℏ²/2m · d²ψ/dx² = Eψ), what are the quantized energy eigenvalues E_n and what is the probability of finding a particle in the ground state (n = 1) between x = 0 and x = L/4?',
      options: [
        { text: 'E_n = (n²π²ℏ²) / (2mL²) = (n²h²) / (8mL²); Probability P = ∫₀^(L/4) (2/L)sin²(πx/L)dx = [x/L - (1/2π)sin(2πx/L)]₀^(L/4) = 1/4 - 1/(2π) ≈ 0.25 - 0.159 = 0.091 (approx 9.1%).', correct: true },
        { text: 'E_n = nhf; Probability is exactly 25.0% because probability density is uniform across the entire well.', correct: false },
        { text: 'E_n = ½mω²L²; Probability is zero because quantum particles only exist at the exact center x = L/2.', correct: false },
        { text: 'E_n = nℏc/L; Probability is 50.0%.', correct: false },
      ],
      learning_objective: 'Quantum mechanics, particle in a box (1D infinite well), Schrödinger wave equation solution, quantized eigenvalues, and wave function probability density integration (ψ²).',
      hint: 'Energy is E_n = n²h² / (8mL²). The ground state wave function is ψ(x) = √(2/L) sin(πx/L). Integrate ψ² from 0 to L/4: it is less than 25% because sin² peaks at the center.',
      irt_a: 1.7,
      irt_b: 1.75,
      irt_c: 0.25,
      international_benchmark: 'IPhO Theoretical Exam / European Physics Olympiad / International Physics Olympiad',
    },

    // 2. Computational Thinking (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C10-COM-01',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'In cryptographic protocols, a cryptographic hash function (e.g., SHA-256) maps arbitrary-length data to a fixed 256-bit digest. According to the "Birthday Paradox", approximately how many random inputs must an attacker hash before having a 50% probability of finding ANY two inputs with an identical hash collision (collision resistance attack)?',
      options: [
        { text: 'Approximately 2¹²⁸ hash evaluations (~√(2²⁵⁶) = 2^(256/2)), drastically lower than brute-forcing a specific preimage (2²⁵⁶).', correct: true },
        { text: 'Exactly 2²⁵⁶ hash evaluations (requiring an exhaustive check of all possible digests).', correct: false },
        { text: '256 hash evaluations (one for each bit of the digest).', correct: false },
        { text: '365 hash evaluations (based on calendar days).', correct: false },
      ],
      learning_objective: 'Cryptographic hash functions, Birthday Paradox, collision resistance bounds (O(2^(n/2))), and security parameter sizing.',
      hint: 'The Birthday Paradox states that finding ANY collision between any two elements in a space of size N requires only ~√N samples. For 2²⁵⁶, √N = 2¹²⁸.',
      irt_a: 1.35,
      irt_b: 0.5,
      irt_c: 0.25,
      international_benchmark: 'CyberPatriot / CSTA Level 3B Cybersecurity / Bebras Senior',
    },
    {
      scenario_code: 'C10-COM-02',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'standard',
      prompt: 'An autonomous navigation robot uses an occupancy grid map to plan paths with the A* search algorithm. The heuristic function h(n) estimates distance from node n to the target. What mathematical condition must the heuristic satisfy to be "admissible", and what happens if an inadmissible heuristic is used?',
      options: [
        { text: 'The heuristic must never overestimate the true minimum cost to reach the goal (h(n) ≤ h*(n)); an inadmissible heuristic may cause A* to return a suboptimal path instead of the true shortest path.', correct: true },
        { text: 'The heuristic must always equal zero (turning A* into depth-first search).', correct: false },
        { text: 'The heuristic must overestimate cost by at least 100% to ensure safety margins.', correct: false },
        { text: 'Admissibility means the heuristic can only use integer coordinates.', correct: false },
      ],
      learning_objective: 'A* heuristic search, admissibility criterion (h(n) ≤ h*(n)), consistency (triangle inequality), and optimality guarantees.',
      hint: 'Admissible means optimistic: if your estimate of remaining distance is never larger than reality, A* is mathematically guaranteed to find the true shortest path.',
      irt_a: 1.4,
      irt_b: 0.7,
      irt_c: 0.25,
      international_benchmark: 'USACO Silver Division / AP Computer Science Principles AI',
    },
    {
      scenario_code: 'C10-COM-03',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'In dynamic programming, the Longest Common Subsequence (LCS) problem finds the longest subsequence present in both string X of length m and string Y of length n. If the recurrence is: \nLCS(i, j) = LCS(i-1, j-1) + 1 if X[i] == Y[j] \nelse max(LCS(i-1, j), LCS(i, j-1)). \nFor strings X = "ALGORITHM" and Y = "LOGARITHMIC", what is the length of their Longest Common Subsequence?',
      options: [
        { text: '6 characters (Subsequence: "L-G-R-I-T-M" appears in order in both strings: "a-L-G-o-R-I-T-h-M" and "L-o-G-a-R-I-T-h-M-i-c"; wait: "A-L-G-O-R-I-T-H-M" has L, G, R, I, T, H, M: 7 characters! Check: "L-G-R-I-T-H-M" -> X has L(1), G(2), R(4), I(5), T(6), H(7), M(8). Y has L(0), G(2), R(4), I(5), T(6), H(7), M(8). That is 7 characters: L, G, R, I, T, H, M!).', correct: false },
        { text: '7 characters ("L", "G", "R", "I", "T", "H", "M" appear sequentially in both "ALGORITHM" and "LOGARITHMIC").', correct: true },
        { text: '5 characters ("A", "L", "G", "O", "R").', correct: false },
        { text: '9 characters (identical to the length of ALGORITHM).', correct: false },
      ],
      learning_objective: 'Dynamic programming, Longest Common Subsequence (LCS) table construction, recurrence memoization, and bioinformatics sequence alignment (Needleman-Wunsch).',
      hint: 'Trace the shared letters in order: L... G... R... I... T... H... M. All 7 letters appear in the exact same left-to-right sequence in both words!',
      irt_a: 1.5,
      irt_b: 1.0,
      irt_c: 0.25,
      international_benchmark: 'USACO Gold Division / Canadian Computing Competition Senior',
    },
    {
      scenario_code: 'C10-COM-04',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'advanced',
      prompt: 'A convolutional neural network (CNN) for computer vision processes an input RGB image of size 224 × 224 × 3 pixels. The first layer applies 64 filters of size 7 × 7 with stride s = 2 and padding p = 3. What is the spatial dimensions (height × width × depth) of the resulting output feature map, and how many trainable weight parameters does this convolutional layer contain (excluding biases)?',
      options: [
        { text: 'Output size: 112 × 112 × 64; Trainable weights: 9,408 (Output spatial dimension = ⌊(224 - 7 + 2×3)/2⌋ + 1 = ⌊223/2⌋ + 1 = 111 + 1 = 112; Weights = 7 × 7 × 3_input_channels × 64_filters = 49 × 3 × 64 = 9,408).', correct: true },
        { text: 'Output size: 224 × 224 × 64; Trainable weights: 3,136.', correct: false },
        { text: 'Output size: 56 × 56 × 64; Trainable weights: 18,816.', correct: false },
        { text: 'Output size: 112 × 112 × 3; Trainable weights: 64.', correct: false },
      ],
      learning_objective: 'Convolutional neural networks (CNNs), feature map dimension formula (⌊(W - K + 2P)/S⌋ + 1), filter tensor sizing, and parameter counting in deep learning.',
      hint: 'Spatial size formula: (W - K + 2P)/S + 1 = (224 - 7 + 6)/2 + 1 = 223/2 + 1 = 112. Parameter count: filter_height × filter_width × input_channels × num_filters.',
      irt_a: 1.55,
      irt_b: 1.25,
      irt_c: 0.25,
      international_benchmark: 'Nature Hum. Soc. Sci. 2026 AI Pillar / International Olympiad in Artificial Intelligence (IOAI)',
    },
    {
      scenario_code: 'C10-COM-05',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'In maximum network flow problems, the Ford-Fulkerson method finds maximum flow from source S to sink T. The Edmonds-Karp algorithm specifies using Breadth-First Search (BFS) to select the shortest augmenting path (fewest edges) at each step. What is the guaranteed asymptotic upper bound on the time complexity of the Edmonds-Karp algorithm for a network with V vertices and E edges?',
      options: [
        { text: 'O(V · E²), because the length of the shortest augmenting path increases monotonically, and each of the E edges can become critical at most V/2 times.', correct: true },
        { text: 'O(V² · E), identical to Dinic’s algorithm with blocking flows.', correct: false },
        { text: 'O(E · log V), identical to Dijkstra’s algorithm.', correct: false },
        { text: 'O(V³), independent of the number of edges.', correct: false },
      ],
      learning_objective: 'Network flow algorithms, Edmonds-Karp BFS augmentation, critical edge bounding, and asymptotic complexity proofs (O(VE²)).',
      hint: 'BFS guarantees that shortest path distances in the residual graph never decrease. An edge becomes bottlenecked ("critical") at most V/2 times. E edges × (V/2) iterations × O(E) per BFS = O(V·E²).',
      irt_a: 1.65,
      irt_b: 1.55,
      irt_c: 0.25,
      international_benchmark: 'IOI / ACM ICPC World Finals Foundation / USACO Platinum',
    },
    {
      scenario_code: 'C10-COM-06',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'computationalThinking',
      difficulty: 'olympiad',
      prompt: 'In computational geometry, finding the Convex Hull of a set of n planar 2D points is fundamental. The Graham Scan algorithm sorts points by polar angle and uses a stack with orientation 2D cross-products to maintain counterclockwise turns in O(n log n) time. Why is O(n log n) mathematically proven to be the absolute lower bound for convex hull algorithms in the algebraic decision tree model?',
      options: [
        { text: 'Sorting can be reduced in linear time to the 2D Convex Hull problem (by mapping numbers x_i to parabolas (x_i, x_i²)); since comparison sorting has an Ω(n log n) lower bound, finding the convex hull cannot be faster than Ω(n log n).', correct: true },
        { text: 'Because triangles have three vertices and 3 × n = 3n which equals n log n in binary notation.', correct: false },
        { text: 'Computer monitors cannot refresh pixels faster than log(n) frames per second.', correct: false },
        { text: 'Convex hull algorithms must evaluate all n! permutations of points.', correct: false },
      ],
      learning_objective: 'Computational geometry lower bounds, Graham Scan mechanics, asymptotic reduction proofs (sorting to convex hull reduction), and Ω(n log n) optimality.',
      hint: 'If you could find the convex hull in O(n) time, you could sort numbers in O(n) time by projecting them onto y = x² and reading off the hull. But comparison sorting is Ω(n log n)!',
      irt_a: 1.7,
      irt_b: 1.75,
      irt_c: 0.25,
      international_benchmark: 'IOI Advanced Theory / ACM-SIAM Symposium on Discrete Algorithms (SODA)',
    },

    // 3. Engineering Design (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C10-ENG-01',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'In civil engineering, the Euler critical buckling load for an ideal slender column of length L, elastic modulus E, and second moment of area I is given by: P_cr = (π²·E·I) / (K·L)², where K is the effective length factor. If a column with pinned-pinned ends (K = 1.0) is redesigned to have both ends rigidly clamped/fixed into solid concrete footings (fixed-fixed, K = 0.5), how does its critical buckling load change?',
      options: [
        { text: 'The critical buckling load increases by a factor of 4 (P_cr ∝ 1/K² = 1/(0.5)² = 1/0.25 = 4).', correct: true },
        { text: 'The critical buckling load doubles (factor of 2).', correct: false },
        { text: 'The critical buckling load is halved because fixed ends trap bending stress.', correct: false },
        { text: 'The buckling load remains unchanged because material E and column length L are identical.', correct: false },
      ],
      learning_objective: 'Structural mechanics, Euler column buckling equation (P_cr = π²EI/(KL)²), boundary condition effective length factor K, and compressive stability.',
      hint: 'The factor K is in the denominator and is squared: (K·L)². If K drops from 1.0 to 0.5, the denominator is multiplied by (0.5)² = 0.25. Dividing by 0.25 is multiplying by 4!',
      irt_a: 1.35,
      irt_b: 0.45,
      irt_c: 0.25,
      international_benchmark: 'ASCE Student Bridge Competition / Cambridge A-Level Engineering',
    },
    {
      scenario_code: 'C10-ENG-02',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'standard',
      prompt: 'A bio-medical engineering team designs a high-gradient magnetic drug delivery catheter. Superparamagnetic iron oxide nanoparticles (SPIONs) in the bloodstream experience a magnetic force F_m = (m · ∇)B. Why must the external magnetic field have a high SPATIAL GRADIENT (∇B) rather than merely a high uniform magnetic field strength B?',
      options: [
        { text: 'A uniform magnetic field exerts zero net translational force on a magnetic dipole (it only exerts an alignment torque τ = m × B); a spatial gradient (∇B ≠ 0) is required to exert directional pulling force.', correct: true },
        { text: 'Uniform fields turn blood cells into solid permanent bar magnets that cause immediate heart attacks.', correct: false },
        { text: 'Magnetic gradients destroy the plastic catheter tubing through electromagnetic induction.', correct: false },
        { text: 'Nanoparticles dissolve instantly when exposed to uniform magnetic fields.', correct: false },
      ],
      learning_objective: 'Electromagnetic force on magnetic dipoles (F = (m·∇)B), uniform vs. gradient fields, biomedical nanotechnology, and targeted drug delivery mechanics.',
      hint: 'In a uniform magnetic field, the north pole is pulled right and the south pole is pulled left with equal force-net force is zero! You need a gradient so one side is pulled harder than the other.',
      irt_a: 1.4,
      irt_b: 0.7,
      irt_c: 0.25,
      international_benchmark: 'IEEE Engineering in Medicine and Biology Society / BMES High School Scholar',
    },
    {
      scenario_code: 'C10-ENG-03',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'An RF microwave engineer designs a quarter-wavelength transmission line impedance transformer (length ℓ = λ/4) to match a 50 Ω coaxial cable to a 200 Ω antenna load without signal reflection. What characteristic impedance Z₀_line must the quarter-wave matching section possess?',
      options: [
        { text: '100 Ω (Using quarter-wave impedance formula Z₀_line = √(Z_in × Z_load) = √(50 × 200) = √10,000 = 100 Ω).', correct: true },
        { text: '125 Ω (the arithmetic average: (50 + 200)/2).', correct: false },
        { text: '150 Ω (the difference: 200 - 50).', correct: false },
        { text: '40 Ω (dividing 200 by 50).', correct: false },
      ],
      learning_objective: 'RF transmission lines, impedance matching, quarter-wave transformers (Z₀ = √(Z_in·Z_L)), standing wave ratio (SWR), and reflection coefficient elimination.',
      hint: 'A quarter-wave matching line has characteristic impedance equal to the geometric mean of the input and load impedances: Z = √(Z₁ · Z₂).',
      irt_a: 1.5,
      irt_b: 1.0,
      irt_c: 0.25,
      international_benchmark: 'IEEE Microwave Theory and Technology Society (MTT-S) Student Challenge',
    },
    {
      scenario_code: 'C10-ENG-04',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'advanced',
      prompt: 'In designing a high-temperature solid oxide fuel cell (SOFC), yttria-stabilized zirconia (YSZ) is chosen as the solid electrolyte membrane operating at 800°C. Which transport property makes YSZ uniquely effective at separating gaseous fuel (H₂) from air (O₂) while conducting electrochemical current?',
      options: [
        { text: 'High ionic conductivity for oxide ions (O²⁻) via oxygen vacancy hopping, combined with negligible electronic conductivity, preventing internal electrical short-circuiting.', correct: true },
        { text: 'High electrical conductivity for electrons combined with zero gas impermeability.', correct: false },
        { text: 'It acts as a porous sponge that lets hydrogen and oxygen gases mix and burn in open flame.', correct: false },
        { text: 'It converts ambient thermal radiation into nuclear fission products.', correct: false },
      ],
      learning_objective: 'Solid-state ionics, Solid Oxide Fuel Cells (SOFC), defect chemistry, oxygen vacancy transport mechanisms, and electronic insulation requirements.',
      hint: 'A fuel cell electrolyte must conduct ions (charged atoms) while completely blocking electrons (so electrons are forced to travel through the external circuit doing useful work).',
      irt_a: 1.55,
      irt_b: 1.25,
      irt_c: 0.25,
      international_benchmark: 'Materials Research Society (MRS) Student Challenge / UN SDG 7',
    },
    {
      scenario_code: 'C10-ENG-05',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'In designing a satellite attitude determination and control system (ADCS), three orthogonal reaction wheels provide 3-axis torque. The spacecraft\'s rotational equations of motion are governed by Euler\'s moment equations for a rigid body with principal moments of inertia I_x > I_y > I_z: \nI_x·dω_x/dt - (I_y - I_z)ω_yω_z = M_x \nI_y·dω_y/dt - (I_z - I_x)ω_zω_x = M_y \nI_z·dω_z/dt - (I_x - I_y)ω_xω_y = M_z. \nAccording to the Intermediate Axis Theorem (Tennis Racket Theorem / Dzhanibekov Effect), rotation about which principal axis is dynamically UNSTABLE to small perturbations?',
      options: [
        { text: 'The intermediate axis (I_y): perturbation analysis shows that linearization around the intermediate moment of inertia produces imaginary eigenvalues (positive real parts in perturbation coupling), causing wild 180° flipping oscillations.', correct: true },
        { text: 'The major axis (I_x) with the largest moment of inertia.', correct: false },
        { text: 'The minor axis (I_z) with the smallest moment of inertia.', correct: false },
        { text: 'All three axes are equally stable in zero-gravity space environments.', correct: false },
      ],
      learning_objective: 'Euler’s rigid body rotational dynamics, Intermediate Axis Theorem (Dzhanibekov effect), principal moments of inertia, and spacecraft attitude stability.',
      hint: 'Try spinning a tennis racket or a book in the air: spinning about its longest dimension is stable; spinning about its flattest dimension is stable; spinning about the middle dimension flips uncontrollably!',
      irt_a: 1.65,
      irt_b: 1.55,
      irt_c: 0.25,
      international_benchmark: 'AIAA Space Systems Award / International Space Settlement Design Competition',
    },
    {
      scenario_code: 'C10-ENG-06',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'engineeringDesign',
      difficulty: 'olympiad',
      prompt: 'A tokamak fusion reactor design requires confining a deuterium-tritium plasma at temperature T = 15 keV (approx 150 million K) with plasma particle density n = 2.0 × 10²⁰ m⁻³. According to the Lawson Criterion for fusion ignition (n·T·τ_E ≥ 3 × 10²¹ keV·s/m³ for D-T fusion), what is the minimum required energy confinement time (τ_E) in seconds?',
      options: [
        { text: 'τ_E ≥ 1.0 seconds (n·T = 2.0 × 10²⁰ × 15 = 3.0 × 10²¹ keV/m³; τ_E = (3 × 10²¹ keV·s/m³) / (3.0 × 10²¹ keV/m³) = 1.0 second).', correct: true },
        { text: 'τ_E ≥ 0.10 seconds.', correct: false },
        { text: 'τ_E ≥ 10.0 seconds.', correct: false },
        { text: 'τ_E ≥ 100.0 seconds.', correct: false },
      ],
      learning_objective: 'Nuclear fusion engineering, Lawson criterion triple product (n·T·τ_E), magnetic confinement fusion physics, and tokamak stability parameters (ITER).',
      hint: 'Multiply density by temperature: (2.0 × 10²⁰) × 15 = 3.0 × 10²¹. Compare this directly to the Lawson threshold 3.0 × 10²¹ keV·s/m³.',
      irt_a: 1.7,
      irt_b: 1.8,
      irt_c: 0.25,
      international_benchmark: 'ITER International Fusion Youth / US Department of Energy Nuclear STEM Fellowship',
    },

    // 4. Mathematical Reasoning (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C10-MAT-01',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'Find the derivative f\'(x) of the rational function: \nf(x) = (3x² - 5) / (2x + 1) \nusing the Quotient Rule (d/dx [u/v] = (u\'v - uv\') / v²). What is the value of f\'(1)?',
      options: [
        { text: 'f\'(1) = 14/9 (u = 3x² - 5 → u\' = 6x; v = 2x + 1 → v\' = 2. At x = 1: u(1) = -2, u\'(1) = 6, v(1) = 3, v\'(1) = 2; f\'(1) = [(6 × 3) - (-2 × 2)] / 3² = (18 - (-4)) / 9 = 22/9... wait! 18 - (-4) = 22! Let us check: f\'(1) = 22/9).', correct: false },
        { text: '22/9 (At x = 1: u = 3(1) - 5 = -2; u\' = 6(1) = 6; v = 2(1) + 1 = 3; v\' = 2; Quotient rule: [u\'v - uv\'] / v² = [(6)(3) - (-2)(2)] / (3)² = [18 - (-4)] / 9 = 22/9).', correct: true },
        { text: '14/9 (subtracting 4 instead of adding negative 4).', correct: false },
        { text: '2/3 (using ratio of derivatives: 6x / 2 = 3).', correct: false },
      ],
      learning_objective: 'Differential calculus, Quotient Rule for derivatives, polynomial differentiation, and evaluation at specific points.',
      hint: 'Carefully compute [u\'·v - u·v\'] / v². Notice that subtracting a negative value (-2 × 2 = -4) becomes addition: 18 - (-4) = 22.',
      irt_a: 1.35,
      irt_b: 0.45,
      irt_c: 0.25,
      international_benchmark: 'PISA 2022 Advanced Math / AP Calculus AB Foundation',
    },
    {
      scenario_code: 'C10-MAT-02',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'standard',
      prompt: 'An ellipse centered at the origin has major axis along the x-axis with equation: \n(x² / 25) + (y² / 9) = 1. \nWhat is the eccentricity (e) of this ellipse, and what are the exact coordinates of its two foci?',
      options: [
        { text: 'Eccentricity e = 4/5 = 0.8; Foci are located at (±4, 0) (Semi-major a = √25 = 5; Semi-minor b = √9 = 3; Focal distance c = √(a² - b²) = √(25 - 9) = √16 = 4; e = c/a = 4/5).', correct: true },
        { text: 'Eccentricity e = 3/5; Foci at (0, ±3).', correct: false },
        { text: 'Eccentricity e = 1.25; Foci at (±5, 0).', correct: false },
        { text: 'Eccentricity e = 0.5; Foci at (±2, 0).', correct: false },
      ],
      learning_objective: 'Conic sections, ellipse geometry (x²/a² + y²/b² = 1), focal distance equation (c² = a² - b²), and eccentricity (e = c/a).',
      hint: 'Semi-major axis a = 5, semi-minor axis b = 3. In an ellipse, c² = a² - b² = 25 - 9 = 16, so c = 4. Eccentricity is c / a.',
      irt_a: 1.4,
      irt_b: 0.7,
      irt_c: 0.25,
      international_benchmark: 'TIMSS Advanced Mathematics / Cambridge IGCSE Additional Math',
    },
    {
      scenario_code: 'C10-MAT-03',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'Evaluate the definite integral representing the area under a curve: \n∫₀^(π/2) x · cos(x) dx. \nUsing Integration by Parts (∫ u dv = u·v - ∫ v du), what is the exact numerical value of this integral?',
      options: [
        { text: 'π/2 - 1 (Let u = x → du = dx; dv = cos(x)dx → v = sin(x); ∫ x cos(x)dx = [x sin(x)]₀^(π/2) - ∫₀^(π/2) sin(x)dx = (π/2 · 1 - 0) - [-cos(x)]₀^(π/2) = π/2 - [-0 - (-1)] = π/2 - 1 ≈ 0.5708).', correct: true },
        { text: 'π/2 (forgetting the second integral term).', correct: false },
        { text: '1.0 (evaluating without the boundary factor).', correct: false },
        { text: 'π² / 4 (multiplying limits directly).', correct: false },
      ],
      learning_objective: 'Integral calculus, Integration by Parts formula (∫ u dv = uv - ∫ v du), trigonometric definite integrals, and exact evaluations.',
      hint: 'Set u = x (so du = dx) and dv = cos(x)dx (so v = sin(x)). Evaluate [x·sin(x)] from 0 to π/2, then subtract the integral of sin(x).',
      irt_a: 1.5,
      irt_b: 1.05,
      irt_c: 0.25,
      international_benchmark: 'AP Calculus BC / Cambridge International A-Level Further Mathematics',
    },
    {
      scenario_code: 'C10-MAT-04',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'advanced',
      prompt: 'A 3×3 matrix A has eigenvalues λ₁ = 2, λ₂ = -1, and λ₃ = 4. What is the Trace of matrix A, the Determinant of matrix A, and the Determinant of the inverse matrix A⁻¹?',
      options: [
        { text: 'Trace(A) = 5 (sum of eigenvalues: 2 + (-1) + 4 = 5); Det(A) = -8 (product of eigenvalues: 2 × (-1) × 4 = -8); Det(A⁻¹) = -1/8 (-0.125).', correct: true },
        { text: 'Trace(A) = -8; Det(A) = 5; Det(A⁻¹) = 1/5.', correct: false },
        { text: 'Trace(A) = 7; Det(A) = 8; Det(A⁻¹) = 8.', correct: false },
        { text: 'Trace(A) = 0; Det(A) = 0; matrix A is singular and cannot be inverted.', correct: false },
      ],
      learning_objective: 'Linear algebra, eigenvalue properties, spectral trace theorem (Trace = Σλ_i), determinant product theorem (Det = Πλ_i), and inverse determinant (Det(A⁻¹) = 1/Det(A)).',
      hint: 'The trace of any matrix is the sum of its eigenvalues. The determinant is the product of its eigenvalues. The determinant of the inverse is 1 / Det(A).',
      irt_a: 1.55,
      irt_b: 1.3,
      irt_c: 0.25,
      international_benchmark: 'MIT 18.06 Linear Algebra Foundation / AMC 12',
    },
    {
      scenario_code: 'C10-MAT-05',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'Let a, b, c be positive real numbers such that a + b + c = 1. Using Cauchy-Schwarz inequality in Engel form (Sedrakyan’s Lemma: Σ (x_i²/a_i) ≥ (Σ x_i)² / Σ a_i), what is the minimum possible value of the expression: \nS = 1/(1 + a) + 1/(1 + b) + 1/(1 + c)?',
      options: [
        { text: '9/4 (By Cauchy-Schwarz: (1/(1+a) + 1/(1+b) + 1/(1+c)) ≥ (1 + 1 + 1)² / ((1+a) + (1+b) + (1+c)) = 3² / (3 + (a+b+c)) = 9 / (3 + 1) = 9/4 = 2.25, achieved when a = b = c = 1/3).', correct: true },
        { text: '3.0 (assuming minimum occurs at boundary points).', correct: false },
        { text: '2.0 (arithmetic estimation).', correct: false },
        { text: '1.0 (assuming the expression sums to the constraint).', correct: false },
      ],
      learning_objective: 'Olympiad inequalities, Cauchy-Schwarz inequality (Engel / Titu form), symmetry exploitation, and constrained minimization.',
      hint: 'Apply Engel form: 1/(1+a) + 1/(1+b) + 1/(1+c) ≥ (1+1+1)² / ((1+a)+(1+b)+(1+c)). Substitute a+b+c = 1 in the denominator.',
      irt_a: 1.65,
      irt_b: 1.6,
      irt_c: 0.25,
      international_benchmark: 'USAMO / Romanian Master of Mathematics / IMO Training',
    },
    {
      scenario_code: 'C10-MAT-06',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'mathematicalReasoning',
      difficulty: 'olympiad',
      prompt: 'In a triangle ABC, point D lies on side BC such that AD is an angle bisector of angle BAC. Side lengths are AB = c, AC = b, BC = a. By the Angle Bisector Theorem and Stewart’s Theorem, what is the exact length of the angle bisector d = AD in terms of sides a, b, c and segments m = BD, n = CD?',
      options: [
        { text: 'AD² = b·c - m·n (where m = ac/(b+c) and n = ab/(b+c); Stewart’s theorem simplifies directly to d² = bc(1 - (a/(b+c))²)).', correct: true },
        { text: 'AD² = b² + c² - 2bc·cos(A).', correct: false },
        { text: 'AD = (b + c) / 2.', correct: false },
        { text: 'AD = √(a² + b² + c²).', correct: false },
      ],
      learning_objective: 'Advanced Euclidean geometry, Angle Bisector Theorem, Stewart’s Theorem (b²m + c²n = a(d² + mn)), and length derivation.',
      hint: 'The classic formula for angle bisector length d using segment lengths m and n is d² = b·c - m·n.',
      irt_a: 1.7,
      irt_b: 1.8,
      irt_c: 0.25,
      international_benchmark: 'International Mathematical Olympiad (IMO) / USAMO',
    },

    // 5. Systems Thinking (6 items: 2 standard, 2 advanced, 2 olympiad)
    {
      scenario_code: 'C10-SYS-01',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'In electrical power systems engineering, the "N-1 Reliability Criterion" mandates that a transmission grid must continue operating within normal voltage and frequency limits even if ANY single critical element (a large 1,000 MW generator, a high-voltage transmission line, or a primary transformer) experiences an immediate catastrophic trip. How do system operators practically enforce N-1 compliance?',
      options: [
        { text: 'By maintaining spinning operating reserves (fast-start thermal/hydro units and battery storage) and running real-time contingency analysis power flow software.', correct: true },
        { text: 'By turning off power to hospitals and schools during thunderstorms.', correct: false },
        { text: 'By operating all transmission lines at 100% maximum thermal capacity around the clock.', correct: false },
        { text: 'By banning industrial factories from consuming alternating current.', correct: false },
      ],
      learning_objective: 'Power grid reliability, N-1 contingency criterion, spinning reserves, real-time AC power flow modeling, and blackout prevention.',
      hint: 'To survive the sudden loss of any single major powerplant, the system must always have enough idling "spinning" reserve power ready to take over within seconds.',
      irt_a: 1.35,
      irt_b: 0.5,
      irt_c: 0.25,
      international_benchmark: 'IEEE Power & Energy Society / NERC Reliability Standards',
    },
    {
      scenario_code: 'C10-SYS-02',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'standard',
      prompt: 'In cybersecurity and identity systems, multi-factor authentication (MFA) requires presenting at least two distinct authentication factor categories: (1) Knowledge (something you know), (2) Possession (something you have), and (3) Inherence (something you are). Which combination represents true multi-factor authentication?',
      options: [
        { text: 'A memorized password (Knowledge) combined with a Time-based One-Time Password (TOTP) from a hardware security token (Possession).', correct: true },
        { text: 'A user password combined with a security question asking for their mother’s maiden name (both are Knowledge factors).', correct: false },
        { text: 'A fingerprint scan combined with a facial recognition camera scan (both are Inherence factors).', correct: false },
        { text: 'Entering the same alphanumeric password twice in two separate text boxes.', correct: false },
      ],
      learning_objective: 'Cybersecurity systems architecture, multi-factor authentication (MFA) taxonomy (Knowledge, Possession, Inherence), and defense-in-depth principles.',
      hint: 'Two passwords are both "something you know" (one category). True MFA requires factors from DIFFERENT categories (e.g., something you know + something you have).',
      irt_a: 1.4,
      irt_b: 0.7,
      irt_c: 0.25,
      international_benchmark: 'NIST Special Publication 800-63B / CyberPatriot High School',
    },
    {
      scenario_code: 'C10-SYS-03',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In systems immunology, monoclonal antibody therapies for autoimmune diseases target Tumor Necrosis Factor-alpha (TNF-α) to suppress chronic inflammation. However, patients undergoing anti-TNF therapy have a tenfold increased risk of reactivating latent tuberculosis. What systemic immunological trade-off explains this vulnerability?',
      options: [
        { text: 'Pleiotropic immune signaling: TNF-α is required for maintaining macrophage granuloma structural integrity that physically encapsulates latent Mycobacterium tuberculosis bacteria in lung tissue.', correct: true },
        { text: 'Anti-TNF antibodies chemically mutate into live tuberculosis bacteria.', correct: false },
        { text: 'Blocking TNF causes the spleen to dissolve completely into lymph fluid.', correct: false },
        { text: 'Tuberculosis bacteria eat synthetic antibody proteins as their primary sugar fuel.', correct: false },
      ],
      learning_objective: 'Systems immunology, cytokine pleiotropy, homeostatic trade-offs, granuloma maintenance (TNF-α), and opportunistic infection risks.',
      hint: 'The very same signaling molecule that causes painful arthritis inflammation is also the molecular glue that keeps dangerous dormant tuberculosis bacteria trapped inside microscopic cages in the lung.',
      irt_a: 1.5,
      irt_b: 1.1,
      irt_c: 0.25,
      international_benchmark: 'USABO Semifinalist / Biomedical Engineering Society Systems Physiology',
    },
    {
      scenario_code: 'C10-SYS-04',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'advanced',
      prompt: 'In planetary carbon cycle modeling, the Permafrost Carbon Feedback is a major climate tipping risk. Arctic permafrost soils store ~1,400 to 1,600 gigatonnes of frozen organic carbon. As rising global temperatures thaw the active permafrost layer, microbial anaerobic decomposition produces methane (CH₄, which has a 28× higher 100-year Global Warming Potential than CO₂). Why is this modeled as an accelerating positive feedback loop with strong hysteresis?',
      options: [
        { text: 'Warming thaws permafrost → microbial respiration emits greenhouse gases (CO₂ & CH₄) → increased atmospheric radiative forcing drives further planetary warming → accelerates deeper thermokarst thawing.', correct: true },
        { text: 'Methane emissions instantly freeze the Arctic ocean into solid glaciers, cooling the planet.', correct: false },
        { text: 'Thawed permafrost creates black holes that absorb the Earth’s atmosphere.', correct: false },
        { text: 'Microbes consume atmospheric nitrogen, eliminating all air resistance.', correct: false },
      ],
      learning_objective: 'Earth systems climate modeling, permafrost carbon feedback, radiative forcing, hysteresis, and methane Global Warming Potential (GWP).',
      hint: 'Notice the self-reinforcing circle: heat melts frozen mud, bugs in the mud wake up and release greenhouse gas, the gas traps more heat, melting even more frozen mud.',
      irt_a: 1.55,
      irt_b: 1.35,
      irt_c: 0.25,
      international_benchmark: 'IPCC AR6 Working Group I / Nature Climate Change / UN SDG 13',
    },
    {
      scenario_code: 'C10-SYS-05',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In high-frequency algorithmic trading systems, market makers provide liquidity using Limit Order Books. During the "2010 Flash Crash", automated algorithmic trading programs simultaneously pulled bids from market order books across hundreds of equities when volatility spiked, creating a sudden vacuum of buying liquidity that caused the Dow Jones to plummet 1,000 points in 10 minutes. What positive feedback loop caused this liquidity spiral?',
      options: [
        { text: 'Correlated algorithmic stop-loss triggers and automated dynamic risk limits: falling prices prompted automated sell orders, which consumed remaining thin bids, triggering further margin calls and algorithmic liquidation cascades across interconnected exchanges.', correct: true },
        { text: 'Transatlantic fiber optic cables were severed by deep-sea sharks.', correct: false },
        { text: 'Traders physically ran out of printed US paper currency.', correct: false },
        { text: 'Stock exchanges automatically switched from digital computers back to mechanical wooden gears.', correct: false },
      ],
      learning_objective: 'Market microstructure, automated algorithmic feedback loops, liquidity dry-ups, correlated risk limits, and financial stability systems.',
      hint: 'When market algorithms are programmed with identical risk rules ("if price drops 2%, sell immediately"), their simultaneous selling pushes the price down further, triggering the next wave of automated sales.',
      irt_a: 1.65,
      irt_b: 1.65,
      irt_c: 0.25,
      international_benchmark: 'International Economics Olympiad / MIT System Dynamics Finance',
    },
    {
      scenario_code: 'C10-SYS-06',
      class_level: 10,
      developmental_band: '9-10',
      competency: 'systemsThinking',
      difficulty: 'olympiad',
      prompt: 'In game theory and evolutionary systems, the Iterated Prisoner’s Dilemma examines the evolution of cooperation in competitive environments. In Axelrod’s famous computer tournaments, the simplest strategy-"Tit-for-Tat" (cooperate on round 1, then simply copy whatever the opponent did in the previous round)-consistently defeated complex predatory strategies. What four structural systems properties explain Tit-for-Tat’s evolutionary dominance?',
      options: [
        { text: 'It is Nice (never the first to defect), Retaliatory (punishes defection immediately), Forgiving (returns to cooperation as soon as the opponent cooperates), and Clear (transparent and easily recognized by opponents).', correct: true },
        { text: 'It is Deceptive (always promises to cooperate but always defects at the end).', correct: false },
        { text: 'It uses quantum random number generators to confuse opposing players.', correct: false },
        { text: 'It hacks the computer memory of the opposing program to force it into an infinite loop.', correct: false },
      ],
      learning_objective: 'Evolutionary game theory, Axelrod’s tournament, Iterated Prisoner’s Dilemma, Tit-for-Tat dynamics, and conditions for the evolution of cooperation.',
      hint: 'Robert Axelrod identified four key traits: it never starts a fight (nice), it hits back immediately if attacked (retaliatory), it doesn’t hold a grudge (forgiving), and its rules are simple to predict (clear).',
      irt_a: 1.7,
      irt_b: 1.8,
      irt_c: 0.25,
      international_benchmark: 'Santa Fe Institute Evolutionary Dynamics / International Philosophy & Social Sciences Olympiad',
    },
  ];
}
