import { ScenarioDef, makeOptions } from './english_types';

export const englishBand9_10: ScenarioDef[] = [
  // ── Understanding (10 items) ──
  {
    scenario_code: 'ENG-910-UND-01',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: '"The biographer does not romanticize the statesman\'s triumphs; rather, she dissects his compromises with the forensic detachment of an anatomist." What characterizes the biographer\'s intellectual style?',
    options: makeOptions('understanding',
      'Unsentimental, rigorous, and analytically critical examination.',
      ['Hagiographic celebration of patriotic martyrdom.', 'Superficial sensationalism focused on court intrigue.', 'Nostalgic praise for obsolete diplomatic conventions.']
    ),
    learning_objective: 'Analyzing tone, register, and authorial detachment in high-level biographical prose.',
    hint: 'Notice words like "forensic detachment" and "dissects compromises".',
    irt_a: 1.3,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'IGCSE English Language / Cambridge O-Level'
  },
  {
    scenario_code: 'ENG-910-UND-02',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: '"The judicial majority held that freedom of expression is not an absolute sovereign license, but a situated right bounded by the state\'s compelling interest in preventing imminent incitement to violence." How does the court define the boundary of free speech?',
    options: makeOptions('understanding',
      'As a vital but conditional right that may be curtailed when speech creates an immediate threat of unlawful violence.',
      ['As an unlimited personal entitlement that supersedes all public safety laws.', 'As a privilege granted exclusively to licensed journalistic media organizations.', 'As an obsolete constitutional principle that has no modern relevance.']
    ),
    learning_objective: 'Deconstructing complex constitutional legal prose and conditional rights.',
    hint: 'Look for the boundary: "bounded by the state\'s compelling interest in preventing imminent incitement".',
    irt_a: 1.35,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 10 English Language'
  },
  {
    scenario_code: 'ENG-910-UND-03',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: '"In describing the sprawling megalopolis as \'a voracious metabolic engine ingesting rivers of freshwater and exhaling plumes of toxic carbon,\' what ecological paradigm is the author deploying?"',
    options: makeOptions('understanding',
      'An industrial metabolism paradigm, framing the modern city as an organism with consumptive and excretory resource flows.',
      ['A celebration of urban architectural density and civil engineering mastery.', 'A literal claim that asphalt highways possess biological lungs.', 'A historical economic treatise on pre-industrial river transportation.']
    ),
    learning_objective: 'Interpreting ecological paradigms and metabolic metaphors in urban studies essays.',
    hint: 'Notice: ingesting freshwater, exhaling carbon, "metabolic engine".',
    irt_a: 1.4,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore MOE Secondary 4 O-Level English'
  },
  {
    scenario_code: 'ENG-910-UND-04',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: '"The novel\'s narrator maintains an ironic distance, recounting his family\'s catastrophic bankruptcy with the dry amusement of a spectator watching a badly rehearsed farce." What does this tonal dissonance signify?',
    options: makeOptions('understanding',
      'A psychological coping defense: using cynical levity to shield himself from the raw trauma of domestic ruin.',
      ['Genuine financial joy at being liberated from material wealth.', 'Total ignorance regarding the reality of debt and insolvency.', 'A technical theatrical critique of amateur stage productions.']
    ),
    learning_objective: 'Analyzing tonal dissonance as a psychological coping mechanism in first-person narrative.',
    hint: 'Why would someone narrate their own ruin like it\'s a "badly rehearsed farce"?',
    irt_a: 1.35,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 10 Reading Literature'
  },
  {
    scenario_code: 'ENG-910-UND-05',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: '"The epistemologist cautioned that our intuitive perception of time as an unbroken flowing river is an evolutionary cognitive convenience, not an ontological feature of physical space-time." What distinction is being drawn?',
    options: makeOptions('understanding',
      'Between the brain\'s adaptive subjective experience of time and the actual mathematical reality of the physical universe.',
      ['Between liquid hydrological flows and mechanical clock escapements.', 'Between ancient mythological rivers and modern navigational canals.', 'Between human memory capacity and computer hard drive storage.']
    ),
    learning_objective: 'Distinguishing ontological reality from evolutionary cognitive adaptation.',
    hint: 'Contrast "cognitive convenience" (how the mind experiences it) with "ontological feature" (what is physically true).',
    irt_a: 1.4,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'CBSE Class 10 English Communicative'
  },
  {
    scenario_code: 'ENG-910-UND-06',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: '"The essay posits that modern commodification of art reduces the museum from a temple of contemplative aesthetic communion to a transactional gallery of speculative financial assets." What societal transformation does this critique diagnose?',
    options: makeOptions('understanding',
      'The subordination of authentic artistic spiritual and cultural value to capitalist investment and elite status display.',
      ['An increase in religious visitors attending art galleries for prayer.', 'The total obsolescence of oil painting in the face of digital photography.', 'A legal requirement that all museums operate as private commercial banks.']
    ),
    learning_objective: 'Deconstructing critical cultural theory regarding the financialization of art.',
    hint: 'Contrast "temple of contemplative aesthetic communion" with "transactional gallery of financial assets".',
    irt_a: 1.45,
    irt_b: 0.7,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE Literature in English'
  },
  {
    scenario_code: 'ENG-910-UND-07',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: '"The cultural theorist argues that nostalgia is not an innocent wistfulness for the past, but an active ideological weapon that rewrites history to legitimize contemporary exclusion." How is nostalgia redefined here?',
    options: makeOptions('understanding',
      'As a potent political instrument that curates a mythic golden age to justify current sociopolitical oppression.',
      ['As an incurable neurological disease affecting elderly citizens.', 'As an artistic aesthetic limited exclusively to Victorian interior decorating.', 'As an objective chronological method for cataloging museum antiquities.']
    ),
    learning_objective: 'Interpreting critical ideological definitions of collective memory and nostalgia.',
    hint: 'Look at what nostalgia does politically: "rewrites history to legitimize contemporary exclusion".',
    irt_a: 1.5,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 4 Express / GCE O-Level'
  },
  {
    scenario_code: 'ENG-910-UND-08',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: '"The author describes the desert landscape as \'indifferent rather than cruel,\' insisting that projecting malevolence onto arid dunes is merely human vanity unable to accept a universe that does not care about its survival." What philosophical realization is articulated?',
    options: makeOptions('understanding',
      'Cosmic indifference: nature operates by physical laws entirely detached from human moral narratives or emotional desires.',
      ['Deserts actively conspire to punish travelers who violate ancient tribal customs.', 'Human survival is guaranteed in any extreme environment through sheer willpower.', 'Arid climates are biologically superior to temperate deciduous forests.']
    ),
    learning_objective: 'Analyzing cosmic indifference and the pathetic fallacy in existential literature.',
    hint: 'Notice: "indifferent rather than cruel", refusing to project malevolence.',
    irt_a: 1.5,
    irt_b: 0.9,
    irt_c: 0.25,
    international_benchmark: 'US AP English Language Entry Diagnostic'
  },
  {
    scenario_code: 'ENG-910-UND-09',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: '"The structuralist literary critic asserts that the protagonist\'s tragedy was not forged in the crucible of his fatal moral flaw (hamartia), but was mechanically predetermined by the socioeconomic constraints of the narrative architecture." How does this interpretation challenge classical Aristotelian poetics?',
    options: makeOptions('understanding',
      'It displaces individual moral agency and personal fault in favor of systemic, deterministic societal structures.',
      ['It reaffirms that individual ethical choices are the sole driving force of dramatic tragedy.', 'It argues that ancient Greek tragedies were written exclusively for comedic entertainment.', 'It proves that plays must have five acts to maintain dramatic tension.']
    ),
    learning_objective: 'Contrasting classical individual hamartia with structuralist socioeconomic determinism.',
    hint: 'Notice the shift from personal moral flaw to narrative/socioeconomic predetermination.',
    irt_a: 1.6,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary English Olympiad / National Team Trials'
  },
  {
    scenario_code: 'ENG-910-UND-10',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: '"The political essayist warns that when totalitarian regimes monopolize language through state-sanctioned euphemisms, they do not merely censor dissenting speech—they dismantle the cognitive conceptual vocabulary required to formulate dissenting thoughts." What profound mechanism of control is identified?',
    options: makeOptions('understanding',
      'Linguistic determinism: restricting language to preemptively eradicate the mental capacity for critical rebellion.',
      ['Physical imprisonment of political dissidents in remote penal colonies.', 'Enforcing compulsory attendance at patriotic military rallies.', 'Banning all import tariffs on foreign consumer electronics.']
    ),
    learning_objective: 'Analyzing Orwellian linguistic hegemony and the constriction of cognitive conceptual horizons.',
    hint: 'Think about Orwell\'s Newspeak: if there are no words for freedom, can people think of freedom?',
    irt_a: 1.65,
    irt_b: 1.2,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE Distinction / IB Middle Years Program'
  },

  // ── Locating Information (10 items) ──
  {
    scenario_code: 'ENG-910-LOC-01',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Food Safety Regulatory Dossier: "Section 4.2: Plasticizer Additive DEHP is strictly prohibited in dairy contact packaging unless the migration coefficient into aqueous food simulants remains below 0.05 mg/dm² over a standardized 10-day test cycle at 40°C." What threshold must DEHP satisfy to be legally permissible?',
    options: makeOptions('locatingInformation',
      'Migration coefficient strictly below 0.05 mg/dm² under standard 10-day, 40°C conditions.',
      ['Total absence of chemical migration over a 30-day cycle at room temperature.', 'A concentration exceeding 0.5 mg/dm² in lipid food simulants.', 'Thermal stability up to 100°C regardless of packaging contact.']
    ),
    learning_objective: 'Extracting precise biochemical migration standards and testing conditions from regulatory codes.',
    hint: 'Check the exact number (0.05 mg/dm²), duration (10 days), and temperature (40°C).',
    irt_a: 1.35,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'Cambridge O-Level Informational Text'
  },
  {
    scenario_code: 'ENG-910-LOC-02',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Nanotechnology Safety Guidelines: "Carbon nanotube dispersion handling requires a Class II Type B2 biosafety cabinet with 100% exhaust through dual HEPA filtration. Minimum face velocity must be calibrated to 0.53 m/s ± 0.02 m/s." What is the mandated face velocity for the cabinet?',
    options: makeOptions('locatingInformation',
      '0.53 m/s ± 0.02 m/s',
      ['100 m/s', '2.0 m/s ± 0.5 m/s', '10 m/s']
    ),
    learning_objective: 'Scanning occupational health manuals for specific aerodynamic velocity tolerances.',
    hint: 'Look for "face velocity must be calibrated to".',
    irt_a: 1.35,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 3 Express'
  },
  {
    scenario_code: 'ENG-910-LOC-03',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Patent Disclosure Statement: "Claim 1: The solar thermoelectric device utilizes bismuth telluride nanowires having an average diameter between 15 nm and 25 nm and an electrical conductivity greater than 1.2 × 10⁵ S/m at 300 K." What is the required diameter range for the nanowires?',
    options: makeOptions('locatingInformation',
      'Between 15 nm and 25 nm',
      ['Greater than 1.2 × 10⁵ nm', '300 nm', 'Exactly 1 nm']
    ),
    learning_objective: 'Extracting dimensional nanoscale parameters from formal patent claims.',
    hint: 'Scan for the word "diameter" and note the nanometer range.',
    irt_a: 1.4,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 10 Technical Reading'
  },
  {
    scenario_code: 'ENG-910-LOC-04',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Clinical Trial Pharmacokinetics: "In Cohort 3, the half-life (t1/2) of mAb-71 was determined to be 18.4 days, while renal clearance averaged 2.1 mL/h. Neutralizing anti-drug antibodies (ADAs) were detected in 3 out of 42 subjects at Day 56." In what fraction of subjects were neutralizing antibodies detected at Day 56?',
    options: makeOptions('locatingInformation',
      '3 out of 42 subjects',
      ['18.4 out of 100 subjects', '2.1 out of 42 subjects', 'All 42 subjects']
    ),
    learning_objective: 'Locating specific immunogenicity incidence rates in clinical cohort summaries.',
    hint: 'Find the sentence mentioning "anti-drug antibodies (ADAs)".',
    irt_a: 1.4,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 10 English Language'
  },
  {
    scenario_code: 'ENG-910-LOC-05',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Urban Zoning Statute: "Mixed-Use Commercial Zone C-4 mandates a Floor Area Ratio (FAR) not exceeding 4.5. Maximum building height is capped at 65 meters, with a minimum 8-meter setback from primary road centrelines for all structures exceeding 30 meters." What is the maximum permissible FAR?',
    options: makeOptions('locatingInformation',
      'Not exceeding 4.5',
      ['65 meters', '8 meters', '30 meters']
    ),
    learning_objective: 'Extracting precise regulatory ratios from municipal zoning ordinances.',
    hint: 'Look directly for "Floor Area Ratio (FAR)".',
    irt_a: 1.35,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'CBSE Class 10 English Language'
  },
  {
    scenario_code: 'ENG-910-LOC-06',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: 'International Environmental Treaty: "Under Annex II of the Minamata Convention on Mercury, parties shall prohibit the manufacturing, import, and export of dental amalgam containing over 50% mercury by mass starting January 1, 2030, unless an exemption for pediatric encapsulation is filed before July 1, 2028." What is the final exemption filing date?',
    options: makeOptions('locatingInformation',
      'Before July 1, 2028',
      ['January 1, 2030', 'After 50 years', 'July 1, 2032']
    ),
    learning_objective: 'Disentangling prohibition enforcement dates from preliminary exemption filing deadlines.',
    hint: 'Distinguish between the 2030 prohibition date and the 2028 exemption deadline.',
    irt_a: 1.45,
    irt_b: 0.6,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE English First Language'
  },
  {
    scenario_code: 'ENG-910-LOC-07',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: 'Deep Space Mission Trajectory: "The gravitational slingshot maneuver around Jupiter will impart an orbital delta-v of 5.8 km/s, adjusting perihelion distance to 0.72 AU. Trajectory correction burn TCM-2 is scheduled for mission elapsed time MET +180 days with a thruster burn duration of 412 seconds." What is the duration of thruster burn TCM-2?',
    options: makeOptions('locatingInformation',
      '412 seconds',
      ['180 days', '5.8 km/s', '0.72 AU']
    ),
    learning_objective: 'Scanning orbital mechanics mission timelines for exact engine burn durations.',
    hint: 'Find the duration paired specifically with "TCM-2".',
    irt_a: 1.5,
    irt_b: 0.7,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 4 Express / O-Level'
  },
  {
    scenario_code: 'ENG-910-LOC-08',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: 'Semiconductor Fabrication Manual: "Photolithography process 7A operates at an extreme ultraviolet (EUV) wavelength of 13.5 nm. Mirror optics must be maintained in a vacuum below 10⁻⁷ Torr, with chamber hydrogen flow stabilized at 25 sccm to mitigate tin debris deposition." What vacuum pressure threshold is required?',
    options: makeOptions('locatingInformation',
      'Below 10⁻⁷ Torr',
      ['13.5 nm', '25 sccm', '7A Torr']
    ),
    learning_objective: 'Locating exponential scientific vacuum thresholds in advanced microelectronics literature.',
    hint: 'Look for the pressure unit "Torr" and the exponential notation.',
    irt_a: 1.5,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 10 Technical Evaluation'
  },
  {
    scenario_code: 'ENG-910-LOC-09',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: 'Constitutional Court Opinion: "The Appellate Bench held that while Article 19(1)(g) secures the right to practice any trade, reasonable restrictions under Article 19(6) permit mandatory licensing schemes if the licensing fee does not exceed 2% of annual net turnover and an appeal mechanism is adjudicated within 45 days." What is the maximum permitted licensing fee percentage?',
    options: makeOptions('locatingInformation',
      'Not exceeding 2% of annual net turnover',
      ['45% of gross profit', '19% of operating revenue', '1% of net assets']
    ),
    learning_objective: 'Locating exact statutory financial limitations in complex judicial holdings.',
    hint: 'Find the percentage limit associated with the "licensing fee".',
    irt_a: 1.6,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad Senior'
  },
  {
    scenario_code: 'ENG-910-LOC-10',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: 'Biomedical Proteomics Paper: "Mass spectrometry analysis identified phosphorylation at serine residue Ser-342 of protein Kinase-B, which increased enzymatic kinase activity by 4.2-fold compared to wild-type, whereas mutation to alanine (Ser342Ala) eliminated phosphorylation and reduced baseline activity by 85%." What effect did the Ser342Ala mutation have on baseline enzymatic activity?',
    options: makeOptions('locatingInformation',
      'Reduced baseline activity by 85%',
      ['Increased activity by 4.2-fold', 'Doubled phosphorylation rate', 'Elevated kinase expression by 342%']
    ),
    learning_objective: 'Extracting exact quantitative phenotypic outcomes of specific amino acid point mutations.',
    hint: 'Check specifically what the mutation (Ser342Ala) did, not the original phosphorylation.',
    irt_a: 1.65,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE / GCE O-Level Olympiad Rank'
  },

  // ── Synthesis (10 items) ──
  {
    scenario_code: 'ENG-910-SYN-01',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Perspective Alpha: "Generative linguistic AI expands cognitive productivity by automating boilerplate formulation and syntactical formatting." Perspective Beta: "Cognitive offloading to automated text generators atrophies the neural circuits responsible for deep semantic synthesis and independent critical reasoning." How do these viewpoints reconcile in an analytical synthesis?',
    options: makeOptions('synthesis',
      'While automated tools expedite mechanical drafting, deliberate unassisted writing remains essential for cultivating deep analytical intellect.',
      ['Both authors agree that writing has no connection to intellectual development.', 'Perspective Alpha proves that human critical thinking is entirely obsolete.', 'Perspective Beta argues that software tools should be outlawed by global decree.']
    ),
    learning_objective: 'Synthesizing conflicting positions on artificial intelligence and cognitive offloading.',
    hint: 'Acknowledge the productivity benefits of AI while preserving the irreplaceable need for critical thinking.',
    irt_a: 1.4,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE English Language Synthesis'
  },
  {
    scenario_code: 'ENG-910-SYN-02',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Study 1: "Marine phytoplankton generate roughly 50% of Earth\'s atmospheric oxygen via oceanic photosynthesis." Study 2: "Ocean acidification and rising sea surface temperatures have induced a 1.5% annual decline in global phytoplankton biomass over the past four decades." What systemic planetary inference is justified?',
    options: makeOptions('synthesis',
      'Anthropogenic marine warming and acidification threaten the foundational biological engine responsible for global oxygen generation.',
      ['Terrestrial trees will automatically expand their oxygen output to compensate for ocean losses.', 'Phytoplankton thrive and multiply rapidly in warmer, acidic ocean waters.', 'Atmospheric oxygen levels are completely independent of marine biological cycles.']
    ),
    learning_objective: 'Synthesizing biogeochemical oceanography with global climate destabilization.',
    hint: 'Connect the role of phytoplankton (50% oxygen) with their ongoing decline.',
    irt_a: 1.4,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 4 Express English'
  },
  {
    scenario_code: 'ENG-910-SYN-03',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Economic Report: "Automation and algorithmic trading now account for 78% of daily equity market liquidity." Sociological Review: "High-frequency flash crashes occur when autonomous algorithms execute simultaneous liquidation orders during localized volatility spikes." What synthesis connects these findings?',
    options: makeOptions('synthesis',
      'While algorithmic trading enhances daily transaction liquidity, synchronized automated decision-making introduces systemic risks of sudden catastrophic market instability.',
      ['Human floor traders are significantly faster at executing orders than fiber-optic algorithms.', 'Algorithmic trading has completely eliminated market volatility permanently.', 'Liquidation orders can only be authorized by federal central bankers.']
    ),
    learning_objective: 'Synthesizing market liquidity mechanisms with algorithmic systemic vulnerabilities.',
    hint: 'Weigh high daily liquidity against the systemic danger of sudden "flash crashes".',
    irt_a: 1.45,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 10 Economics & English'
  },
  {
    scenario_code: 'ENG-910-SYN-04',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'Historical Account A: "The 1911 introduction of Henry Ford\'s moving assembly line reduced chassis production time from 12 hours to 93 minutes." Labor History B: "Assembly-line workers reported severe psychological alienation and physical strain from extreme repetitive task specialization, leading to 380% annual turnover until Ford doubled daily wages to $5." What synthesis unifies both accounts?',
    options: makeOptions('synthesis',
      'Industrial efficiency gains through extreme mechanization created severe human labor strains that necessitated unprecedented wage concessions to stabilize the workforce.',
      ['Ford\'s moving assembly line proved to be an economic failure that slowed car manufacturing.', 'Repetitive labor specialization enhanced worker job satisfaction and creative autonomy.', 'Assembly-line techniques were abandoned across American manufacturing by 1915.']
    ),
    learning_objective: 'Synthesizing technological productivity leaps with psychological labor alienation.',
    hint: 'Connect the massive speedup with the extreme worker turnover and wage doubling.',
    irt_a: 1.45,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 10 Synthesis'
  },
  {
    scenario_code: 'ENG-910-SYN-05',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: 'Theory X: "Technological determinism claims that autonomous technological innovation is the primary causal driver transforming human culture and social institutions." Theory Y: "Social constructivism argues that human values, political choices, and economic institutions actively steer and shape which technologies are funded, developed, and deployed." How can a dialectical synthesis reconcile these theories?',
    options: makeOptions('synthesis',
      'Technology and society co-evolve reciprocally: social values shape technological inception, while deployed technologies subsequently reshape societal behaviors and structures.',
      ['Theory X is entirely correct, proving that human culture has zero impact on technological tools.', 'Theory Y proves that machinery operates strictly according to moral and legal guidelines.', 'Both theories agree that pre-industrial societies were technologically superior.']
    ),
    learning_objective: 'Formulating a dialectical synthesis between opposing sociological paradigms.',
    hint: 'Look for reciprocal co-evolution: society shapes tools, tools shape society.',
    irt_a: 1.5,
    irt_b: 0.7,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE First Language English'
  },
  {
    scenario_code: 'ENG-910-SYN-06',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: 'Medical Source 1: "CRISPR-Cas9 somatic gene editing has cured patients of sickle-cell anemia by repairing the mutated beta-globin gene in blood stem cells." Bioethics Essay 2: "Germline genomic modifications alter inheritable DNA across future generations without the consent of unborn progeny, risking unforeseen off-target epigenetic mutations." What critical synthesis distinguishes somatic from germline editing?',
    options: makeOptions('synthesis',
      'Somatic gene editing offers immediate therapeutic relief confined to an individual patient, whereas germline modification introduces multi-generational ethical and biological ramifications.',
      ['Somatic gene editing permanently alters every future descendant of the treated patient.', 'Germline editing is strictly prohibited because Cas9 enzymes cannot cut human DNA.', 'Both forms of gene therapy have been proven entirely free of any biological risk.']
    ),
    learning_objective: 'Synthesizing clinical therapeutic efficacy with bioethical boundaries in gene editing.',
    hint: 'Distinguish between treating an individual patient (somatic) vs altering inherited DNA (germline).',
    irt_a: 1.55,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 4 O-Level Science & English'
  },
  {
    scenario_code: 'ENG-910-SYN-07',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: 'Text Alpha: "Urban sprawl fragments natural forests into isolated island patches." Text Beta: "The theory of island biogeography demonstrates that smaller, isolated habitat patches experience exponentially higher extinction rates due to edge effects and inbreeding depression." What synthesized urban planning recommendation follows?',
    options: makeOptions('synthesis',
      'Urban master plans must incorporate continuous wildlife migration corridors that physically reconnect fragmented woodland islands.',
      ['Forest fragments should be fully cleared to eliminate confusing edges for wildlife.', 'Island biogeography applies strictly to volcanic islands in the Pacific Ocean.', 'Cities should concentrate heavy industrial factories inside forest fragments.']
    ),
    learning_objective: 'Synthesizing theoretical ecological biogeography with actionable urban landscape planning.',
    hint: 'If isolated patches cause extinctions, how do wildlife corridors solve that problem?',
    irt_a: 1.5,
    irt_b: 0.7,
    irt_c: 0.25,
    international_benchmark: 'CBSE Class 10 Environmental Literature'
  },
  {
    scenario_code: 'ENG-910-SYN-08',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: 'Linguistic Study: "Cognitive offloading through digital GPS navigation reduces hippocampal spatial mapping activity and deteriorates mental dead-reckoning." Anthropological Fieldwork: "Polynesian traditional wayfinders, navigating thousands of open-sea nautical miles via star paths, ocean swells, and avian flight vectors, exhibit significantly enlarged posterior hippocampal gray matter volume." What holistic neuro-cultural synthesis is established?',
    options: makeOptions('synthesis',
      'Active reliance on environmental spatial processing physically cultivates neurological mapping infrastructure, whereas technological outsourcing leads to structural neural atrophy.',
      ['Wayfinding is genetically encoded exclusively in Polynesian populations and cannot be learned.', 'GPS satellite signals emit microwave frequencies that damage brain tissue.', 'Hippocampal volume is completely fixed at birth and unaffected by environmental navigation.']
    ),
    learning_objective: 'Synthesizing cognitive neuroscience, neuroplasticity, and comparative cultural epistemology.',
    hint: 'Notice how using your brain for navigation enlarges the hippocampus, while using GPS atrophies it.',
    irt_a: 1.65,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad Senior Division'
  },
  {
    scenario_code: 'ENG-910-SYN-09',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: 'Epistemology Paper: "Karl Popper\'s falsificationism asserts that a hypothesis is scientific only if it makes empirical predictions that can be conclusively refuted by observation." Philosophy of Science: "Thomas Kuhn\'s paradigm theory shows that during periods of \'normal science,\' researchers regularly dismiss anomalous data rather than abandon their reigning foundational paradigm." How do these two frameworks intersect in scientific sociology?',
    options: makeOptions('synthesis',
      'While Popper articulates the normative logical ideal of how science ought to proceed, Kuhn describes the sociopsychological reality of how scientific communities actually behave.',
      ['Popper proves that scientists always immediately discard theories upon discovering a single error.', 'Kuhn demonstrates that empirical observation has zero relevance to scientific advancement.', 'Both philosophers agree that scientific consensus is identical to political voting.']
    ),
    learning_objective: 'Synthesizing normative philosophy of science (Popper) with descriptive sociology of science (Kuhn).',
    hint: 'Distinguish between how science "ought" to work (Popper) vs how humans "actually" act (Kuhn).',
    irt_a: 1.7,
    irt_b: 1.2,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE / O-Level High Distinction'
  },
  {
    scenario_code: 'ENG-910-SYN-10',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: 'Economic Ledger: "High-income nations have reduced domestic greenhouse gas emissions by 20% since 2000." Consumption Analysis: "When calculated by final consumer demand (importing manufactured goods whose emissions are booked in developing exporter nations), high-income national carbon footprints have actually increased by 8%." What synthesis deconstructs the domestic emissions claim?',
    options: makeOptions('synthesis',
      'Apparent domestic decarbonization in wealthy nations is largely an accounting illusion driven by the offshoring of emissions-intensive manufacturing to developing economies.',
      ['Developing nations emit carbon purely for amusement rather than export production.', 'High-income nations have completely eliminated fossil fuel usage across all sectors.', 'Imported manufactured goods do not generate carbon emissions during international maritime shipping.']
    ),
    learning_objective: 'Synthesizing territorial carbon accounting with consumption-based trade flows.',
    hint: 'If a country stops making steel at home and imports it from abroad, did emissions really drop?',
    irt_a: 1.7,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 10 National Merit Tier'
  },

  // ── Evaluating & Reflecting (10 items) ──
  {
    scenario_code: 'ENG-910-EVL-01',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: '"The columnist opens his editorial with a lyrical, nostalgic portrait of idyllic self-sufficient village life before arguing against subsidized rural broadband internet." What rhetorical purpose does this opening portrait serve?',
    options: makeOptions('evaluatingReflecting',
      'It constructs a romanticized pastoral ideal to frame modern digital connectivity as disruptive and culturally corrupting.',
      ['It provides audited economic figures on agricultural infrastructure spending.', 'It refutes claims that agricultural yields correlate with telecommunications access.', 'It demonstrates personal technical expertise in fiber-optic cable installation.']
    ),
    learning_objective: 'Evaluating nostalgic pastoral framing as a rhetorical strategy against technological modernization.',
    hint: 'Why begin an argument against broadband with a romantic picture of village life without technology?',
    irt_a: 1.35,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE English Language'
  },
  {
    scenario_code: 'ENG-910-EVL-02',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: '"The corporate spokesperson defended the chemical spill by stating: \'All environmental parameters are currently trending toward optimal equilibrium.\' How does the author characterize this response?',
    options: makeOptions('evaluatingReflecting',
      'As bureaucratic, obfuscating jargon designed to downplay catastrophic contamination and evade accountability.',
      ['As an accurate, transparent, and courageous scientific acknowledgment of liability.', 'As an apology accompanied by immediate financial compensation to victims.', 'As a legal lawsuit filed against municipal wastewater operators.']
    ),
    learning_objective: 'Deconstructing corporate obfuscation and sanitized technocratic language.',
    hint: 'Notice how "trending toward optimal equilibrium" hides the fact that chemicals spilled.',
    irt_a: 1.4,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 4 Express English'
  },
  {
    scenario_code: 'ENG-910-EVL-03',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'In an editorial arguing against space exploration, the writer asks: "How dare we gaze at the stars through billion-dollar lenses when children in our own city go to bed hungry?" What rhetorical appeal is predominantly employed?',
    options: makeOptions('evaluatingReflecting',
      'Pathos: an emotional appeal grounded in moral outrage and guilt to challenge resource allocation.',
      ['Logos: an econometric cost-benefit calculation of aerospace manufacturing returns.', 'Ethos: establishing the author\'s academic credentials in astrophysics.', 'Kairos: analyzing the specific launch window of planetary orbital alignments.']
    ),
    learning_objective: 'Identifying rhetorical appeals (pathos, logos, ethos) and emotional argumentation.',
    hint: 'Notice the emotional charge in "How dare we gaze at the stars while children go hungry".',
    irt_a: 1.35,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 10 Argumentation'
  },
  {
    scenario_code: 'ENG-910-EVL-04',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'standard',
    prompt: 'A historian analyzes a 19th-century colonial diary: "The diarist documents indigenous harvesting methods not to understand local ecology, but to estimate taxable surplus for the imperial treasury." What does this observation reveal about the diarist\'s perspective?',
    options: makeOptions('evaluatingReflecting',
      'The diarist\'s gaze was purely extractive and administrative, viewing indigenous practices through the lens of colonial fiscal exploitation.',
      ['The diarist was an objective botanical scientist committed to biodiversity conservation.', 'The diarist intended to surrender colonial authority to indigenous tribal councils.', 'The diary was forged by 20th-century counterfeiters to defame the colonial government.']
    ),
    learning_objective: 'Evaluating colonial administrative perspectives and extractive bias in historical primary sources.',
    hint: 'What is the difference between learning ecology vs calculating taxable surplus?',
    irt_a: 1.4,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 10 History & English'
  },
  {
    scenario_code: 'ENG-910-EVL-05',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: '"The defense attorney conceded that her client\'s conduct was \'unorthodox and unconventional,\' while vehemently rejecting the prosecution\'s characterization of it as \'fraudulent and criminal.\' What semantic battle is being waged here?',
    options: makeOptions('evaluatingReflecting',
      'A struggle over legal framing: rebranding deliberate unlawful deception as benign eccentricity to avoid criminal conviction.',
      ['A grammatical debate regarding the etymological origin of Latin legal terms.', 'An admission of guilt that automatically triggers an immediate maximum prison sentence.', 'A personal insult aimed at the presiding appellate judge\'s competence.']
    ),
    learning_objective: 'Analyzing semantic reframing and euphemistic characterization in legal discourse.',
    hint: 'Compare "unorthodox and unconventional" with "fraudulent and criminal".',
    irt_a: 1.5,
    irt_b: 0.7,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE First Language English'
  },
  {
    scenario_code: 'ENG-910-EVL-06',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: 'In reviewing a celebrated war memoir, a critic remarks: "The author displays extraordinary descriptive brilliance, but his total omission of civilian suffering renders the book an aesthetic celebration of tactical violence." What is the central moral critique?',
    options: makeOptions('evaluatingReflecting',
      'By selectively aestheticizing combat while erasing innocent casualties, the author sanitizes war into thrilling spectacle.',
      ['The author should have used simpler vocabulary to appeal to younger audiences.', 'The military memoir failed to include detailed maps of infantry fortifications.', 'The book contains factual inaccuracies regarding weapon caliber specifications.']
    ),
    learning_objective: 'Critiquing aestheticized violence and the ethical consequences of selective omission in war literature.',
    hint: 'Notice the flaw: "total omission of civilian suffering renders the book an aesthetic celebration".',
    irt_a: 1.55,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 4 Literature in English'
  },
  {
    scenario_code: 'ENG-910-EVL-07',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'advanced',
    prompt: '"The tech executive proclaimed that privacy is an obsolete concept in the modern era, conveniently ignoring that his own residential compound is shielded by armed guards and six-meter security walls." What rhetorical contradiction is exposed here?',
    options: makeOptions('evaluatingReflecting',
      'Hypocritical duality: demanding public transparency and data surrender from users while vigorously safeguarding his own elite personal sanctuary.',
      ['A legal dispute over property line easements with neighboring homeowners.', 'An endorsement of open-source software licensing agreements.', 'A technical design failure in residential perimeter fence construction.']
    ),
    learning_objective: 'Exposing hypocrisy and ideological inconsistency through behavioral juxtaposition.',
    hint: 'He tells the public privacy is dead, but surrounds his own house with 6-meter walls.',
    irt_a: 1.5,
    irt_b: 0.7,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 10 Critical Reading'
  },
  {
    scenario_code: 'ENG-910-EVL-08',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: '"When the author shifts from authoritative third-person omniscient narration to fractured, disjointed interior monologue during the catastrophe scene, what epistemological shift occurs for the reader?"',
    options: makeOptions('evaluatingReflecting',
      'The reader is stripped of panoramic objective certainty and plunged into subjective trauma, disorientation, and panic.',
      ['The author indicates that the entire plot was a fabricated dream sequence.', 'The narrative register formally adopts the legal language of accident inquest transcripts.', 'The pacing decelerates to insert detailed biographical flashbacks of secondary characters.']
    ),
    learning_objective: 'Analyzing the psychological and epistemic impact of sudden point-of-view disruptions.',
    hint: 'What happens to the reader when objective storytelling suddenly turns into fractured inner panic?',
    irt_a: 1.65,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad Senior'
  },
  {
    scenario_code: 'ENG-910-EVL-09',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: '"The satirist praises the media corporation for \'magnanimously simplifying political discourse into twenty-second gladiatorial soundbites, thereby sparing the public the exhausting ordeal of nuanced thought.\' What satirical target is being assaulted?"',
    options: makeOptions('evaluatingReflecting',
      'The degradation of democratic civic deliberation into sensationalized, anti-intellectual entertainment for commercial profit.',
      ['The high licensing fees charged for live broadcast television frequencies.', 'The decline of classical Roman gladiatorial arena fighting techniques.', 'The inability of political candidates to purchase digital advertising billboard slots.']
    ),
    learning_objective: 'Deconstructing sustained irony and satirical attacks on media commodification.',
    hint: 'Notice the bitter irony: calling sensationalized soundbites "magnanimous".',
    irt_a: 1.7,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge IGCSE Literature / First Language English'
  },
  {
    scenario_code: 'ENG-910-EVL-10',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '9-10',
    difficulty: 'olympiad',
    prompt: '"The historian asserts: \'To label the 19th-century treaty a \'voluntary commercial partnership\' is an insult to language itself; the ink was scarcely dry before naval gunboats were positioned in the harbor to enforce compliance.\'" What argument does this caustic metaphor solidify?',
    options: makeOptions('evaluatingReflecting',
      'The treaty was an act of coercive imperial subjugation under threat of violent bombardment, completely void of genuine mutual consent.',
      ['The naval gunboats were sent to protect merchant ships from local pirates.', 'The treaty negotiations were conducted under international maritime admiralty law.', 'The treaty expired naturally because paper and ink decayed in tropical humidity.']
    ),
    learning_objective: 'Evaluating historical demystification, moral clarity, and the exposure of gunboat diplomacy.',
    hint: 'How can a treaty be "voluntary" if gunboats are aimed at the harbor to enforce it?',
    irt_a: 1.75,
    irt_b: 1.2,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 10 English Literature Olympiad'
  }
];
