import { ScenarioDef, makeOptions } from './english_types';

export const englishBand3_4: ScenarioDef[] = [
  // ── Understanding (10 items) ──
  {
    scenario_code: 'ENG-34-UND-01',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Read the sentence: "Leo the puppy buried his favorite rubber bone under the old oak tree so his sister Maya would not chew it." Why did Leo bury the bone?',
    options: makeOptions('understanding',
      'He wanted to keep it safe from Maya.',
      ['He forgot where the tree was.', 'He disliked playing with rubber toys.', 'Maya instructed him to bury it.']
    ),
    learning_objective: 'Identifying character motivation and causal relationships in narrative text.',
    hint: 'Look for the reason right after the word "so" in the sentence.',
    irt_a: 1.1,
    irt_b: -1.7,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary English Stage 3 / Singapore Primary 3'
  },
  {
    scenario_code: 'ENG-34-UND-02',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Read: "Although it was pouring rain, Sarah put on her yellow raincoat and walked happily toward the giant puddle." How did Sarah feel about the rainy weather?',
    options: makeOptions('understanding',
      'She was joyful and excited to play in the rain.',
      ['She was frightened of getting her clothes wet.', 'She felt gloomy and wanted to stay indoors.', 'She was angry that her trip was cancelled.']
    ),
    learning_objective: 'Inferring character feelings and attitudes from actions and descriptive words.',
    hint: 'Notice the word "happily" and how Sarah walked toward the puddle.',
    irt_a: 1.15,
    irt_b: -1.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore MOE Primary 3 English'
  },
  {
    scenario_code: 'ENG-34-UND-03',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: '"Every winter, the bear retreats into a cozy cave and enters a deep sleep until spring flowers bloom." What is the main idea of this sentence?',
    options: makeOptions('understanding',
      'Bears hibernate in caves during the cold winter months.',
      ['Spring flowers grow inside dark caves.', 'Bears only wake up when other animals call them.', 'Winter is the best season for bears to hunt food.']
    ),
    learning_objective: 'Determining the main idea of a short informational sentence.',
    hint: 'Consider what the whole sentence is describing about the bear’s winter habits.',
    irt_a: 1.2,
    irt_b: -1.4,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 3 Reading Informational Text'
  },
  {
    scenario_code: 'ENG-34-UND-04',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: '"Toby dropped his ice cream cone on the sidewalk. His lower lip quivered, and tears welled up in his eyes." How does Toby feel?',
    options: makeOptions('understanding',
      'Disappointed and sad about losing his treat.',
      ['Surprised by how warm the sidewalk was.', 'Proud of sharing his ice cream with ants.', 'Bored and ready to go home.']
    ),
    learning_objective: 'Inferring emotional states from physical character cues.',
    hint: 'What do a quivering lip and tears usually show?',
    irt_a: 1.1,
    irt_b: -1.6,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 4 Literary Experience'
  },
  {
    scenario_code: 'ENG-34-UND-05',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: '"The little red hen asked her barnyard friends to help plant wheat seeds, but the duck and cat were too busy napping under the porch." What does this tell us about the duck and cat?',
    options: makeOptions('understanding',
      'They were unwilling to help with farm chores.',
      ['They were skilled wheat farmers.', 'They were afraid of small seeds.', 'They wanted to plant corn instead.']
    ),
    learning_objective: 'Analyzing character traits and behaviors in fables.',
    hint: 'Notice that they chose to nap instead of helping.',
    irt_a: 1.2,
    irt_b: -1.3,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 4'
  },
  {
    scenario_code: 'ENG-34-UND-06',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: '"The grandfather clock in the hallway stood like a tall wooden soldier guarding the quiet house." What comparison is being made here?',
    options: makeOptions('understanding',
      'The steady, upright clock is compared to a standing soldier.',
      ['A real soldier is hiding inside the wooden clock.', 'The house is actively being attacked by an army.', 'The grandfather prefers soldiers over clocks.']
    ),
    learning_objective: 'Interpreting simple similes and figurative imagery.',
    hint: 'Look for the word "like" which connects the clock and the soldier.',
    irt_a: 1.3,
    irt_b: -0.9,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 4 English Literature'
  },
  {
    scenario_code: 'ENG-34-UND-07',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: '"The desert chameleon blended so perfectly into the sand that the hawk flew right past without noticing." Why was the hawk unable to spot the chameleon?',
    options: makeOptions('understanding',
      'The chameleon used camouflage to match the color of the ground.',
      ['The hawk was flying backward.', 'The sand was too bright for any bird to see.', 'The chameleon ran into an underground tunnel.']
    ),
    learning_objective: 'Understanding cause and effect in descriptive informational passages.',
    hint: 'Focus on how blending into the sand protects the chameleon.',
    irt_a: 1.25,
    irt_b: -0.8,
    irt_c: 0.25,
    international_benchmark: 'US NGSS / Common Core Grade 4'
  },
  {
    scenario_code: 'ENG-34-UND-08',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: '"After three hours of hiking up the rocky trail, Anya finally saw the mountain peak gleaming in the afternoon sun. She took a deep breath and smiled." What is the theme of this moment?',
    options: makeOptions('understanding',
      'Effort and perseverance leading to a rewarding achievement.',
      ['The dangers of hiking without proper hiking shoes.', 'Why mountains are colder than valley plains.', 'How sunlight can damage your vision.']
    ),
    learning_objective: 'Deriving overarching theme from narrative resolution.',
    hint: 'Consider the effort Anya put in and how she felt when she reached her goal.',
    irt_a: 1.35,
    irt_b: -0.7,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 4 Core Reading'
  },
  {
    scenario_code: 'ENG-34-UND-09',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: '"The sudden silence in the aviary was louder than any squawk; every bird froze as a shadow glided overhead." Why does the author call the silence "louder than any squawk"?',
    options: makeOptions('understanding',
      'To emphasize how dramatic, alarming, and noticeable the quiet was.',
      ['Because the birds were screaming in high-pitched frequencies.', 'To prove that silence creates physical sound waves.', 'Because the roof of the aviary collapsed.']
    ),
    learning_objective: 'Analyzing literary paradox and authorial emphasis in Grade 3-4 text.',
    hint: 'When everything goes dead silent instantly, what does that sudden change feel like?',
    irt_a: 1.5,
    irt_b: -0.4,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary English Olympiad / SASMO Foundation'
  },
  {
    scenario_code: 'ENG-34-UND-10',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: '"Grandma\'s kitchen was always a busy workshop of simmering pots, flying flour, and stories passed down through generations." What does the word "workshop" suggest about the kitchen?',
    options: makeOptions('understanding',
      'It was an active, creative place where food and traditions were lovingly crafted.',
      ['It was used for repairing broken wooden chairs and tools.', 'It was an untidy and hazardous factory environment.', 'It was strictly reserved for professional cooks.']
    ),
    learning_objective: 'Interpreting metaphorical language and connotative meaning.',
    hint: 'Think about what happens in a workshop—things are made with care and effort.',
    irt_a: 1.45,
    irt_b: -0.3,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Checkpoint English'
  },

  // ── Locating Information (10 items) ──
  {
    scenario_code: 'ENG-34-LOC-01',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Notice: "School Library Schedule: Monday–Thursday: 8:00 AM – 3:30 PM. Friday: Closed for shelf organization." On which day is the library closed for shelf organization?',
    options: makeOptions('locatingInformation',
      'Friday',
      ['Monday', 'Wednesday', 'Thursday']
    ),
    learning_objective: 'Direct retrieval of specific facts from simple schedules.',
    hint: 'Scan the notice for the word "Closed" and look at the day listed right before it.',
    irt_a: 1.2,
    irt_b: -1.8,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 4 Information Retrieval'
  },
  {
    scenario_code: 'ENG-34-LOC-02',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Recipe Card: "Honey Berry Parfait: 1 cup Greek yogurt, 0.5 cup rolled oats, 2 tablespoons wild honey, 1 sliced ripe kiwi. Chill in the refrigerator for 15 minutes before serving." How much wild honey is needed?',
    options: makeOptions('locatingInformation',
      '2 tablespoons',
      ['1 cup', '0.5 cup', '15 minutes']
    ),
    learning_objective: 'Locating precise measurements and ingredients in functional procedural text.',
    hint: 'Locate the ingredient "wild honey" and read the amount specified.',
    irt_a: 1.25,
    irt_b: -1.7,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 3 English Functional Reading'
  },
  {
    scenario_code: 'ENG-34-LOC-03',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Museum Flyer: "Dinosaur Discovery Hall: Level 1. Space & Rockets Gallery: Level 3. Butterfly Pavilion: Rooftop Garden (Level 4)." On which level can visitors find the Space & Rockets Gallery?',
    options: makeOptions('locatingInformation',
      'Level 3',
      ['Level 1', 'Level 2', 'Level 4']
    ),
    learning_objective: 'Scanning informational brochures for specific location details.',
    hint: 'Search directly for the words "Space & Rockets Gallery".',
    irt_a: 1.3,
    irt_b: -1.6,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 3'
  },
  {
    scenario_code: 'ENG-34-LOC-04',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Weather Report: "Sunrise will occur at 6:15 AM. Highest daytime temperature will reach 28°C with moderate breezes from the northeast." What is the expected peak temperature?',
    options: makeOptions('locatingInformation',
      '28°C',
      ['6:15 AM', '15°C', '35°C']
    ),
    learning_objective: 'Retrieving numerical data from short informational reports.',
    hint: 'Find the section mentioning temperature.',
    irt_a: 1.2,
    irt_b: -1.5,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 3 Reading'
  },
  {
    scenario_code: 'ENG-34-LOC-05',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Pet Care Guide: "Hamsters must be given fresh water every morning. Clean their wood shaving bedding once each week, and provide fresh carrot slices twice a week." How often should hamster bedding be cleaned?',
    options: makeOptions('locatingInformation',
      'Once each week',
      ['Every morning', 'Twice a week', 'Once a month']
    ),
    learning_objective: 'Distinguishing between multiple time frequencies in a procedural passage.',
    hint: 'Pay close attention to what corresponds specifically to "bedding".',
    irt_a: 1.35,
    irt_b: -1.4,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 4 Information Tasks'
  },
  {
    scenario_code: 'ENG-34-LOC-06',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: 'School Bus Rules: "Students must remain seated until the bus halts completely. Backpacks must be placed beneath your seat or on your lap. Eating peanuts is strictly forbidden." Where should backpacks be stored?',
    options: makeOptions('locatingInformation',
      'Beneath the seat or on the student\'s lap',
      ['In the aisle between seats', 'In the overhead luggage rack', 'Next to the bus driver']
    ),
    learning_objective: 'Extracting specific rules and storage instructions from safety guidelines.',
    hint: 'Look for the sentence starting with "Backpacks".',
    irt_a: 1.3,
    irt_b: -1.0,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 4 English'
  },
  {
    scenario_code: 'ENG-34-LOC-07',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: 'Camp Itinerary: "08:00 Birdwatching along Maple Creek; 10:30 Kayak paddling practice; 12:30 Outdoor campfire lunch; 14:00 Orienteering navigation game." What activity takes place right before lunch?',
    options: makeOptions('locatingInformation',
      'Kayak paddling practice',
      ['Birdwatching along Maple Creek', 'Orienteering navigation game', 'Campfire cleanup']
    ),
    learning_objective: 'Interpreting chronological order in daily itineraries.',
    hint: 'Look at the activity scheduled at 10:30, right before the 12:30 lunch.',
    irt_a: 1.4,
    irt_b: -0.9,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 4'
  },
  {
    scenario_code: 'ENG-34-LOC-08',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: 'Plant Factfile: "The Venus Flytrap is native only to the coastal bogs of North and South Carolina. Its leaves close in roughly 0.1 seconds when trigger hairs are brushed." In how much time do the leaves snap shut?',
    options: makeOptions('locatingInformation',
      'Roughly 0.1 seconds',
      ['10 seconds', '1 minute', '30 seconds']
    ),
    learning_objective: 'Locating exact numerical scientific facts in descriptive prose.',
    hint: 'Scan for the number followed by the time unit "seconds".',
    irt_a: 1.35,
    irt_b: -0.8,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 4'
  },
  {
    scenario_code: 'ENG-34-LOC-09',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: 'Historical Log: "Captain Miller documented that the schooner arrived at Port Jackson on October 14, carrying 120 barrels of olive oil, 45 crates of dried figs, and three boxes of brass navigation sextants." How many crates of dried figs were recorded?',
    options: makeOptions('locatingInformation',
      '45 crates',
      ['120 barrels', '3 boxes', '14 crates']
    ),
    learning_objective: 'Scanning dense inventory lists for precise item-quantity pairings.',
    hint: 'Pair each number with its exact cargo description.',
    irt_a: 1.5,
    irt_b: -0.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary English Olympiad'
  },
  {
    scenario_code: 'ENG-34-LOC-10',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: 'Wildlife Bulletin: "The Arctic tern migrates from Greenland to Antarctica and back each year, covering nearly 71,000 kilometers annually—the longest recorded journey of any animal on Earth." Between which two geographic regions does this bird travel?',
    options: makeOptions('locatingInformation',
      'Greenland and Antarctica',
      ['Canada and Australia', 'Alaska and South America', 'Norway and South Africa']
    ),
    learning_objective: 'Locating origin and destination entities in geographic informational text.',
    hint: 'Look for the "from ... to ..." phrase in the passage.',
    irt_a: 1.45,
    irt_b: -0.4,
    irt_c: 0.25,
    international_benchmark: 'ICSE Grade 4 English Literature & Language'
  },

  // ── Synthesis (10 items) ──
  {
    scenario_code: 'ENG-34-SYN-01',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Fact 1: "Green plants require sunlight to create food through photosynthesis." Fact 2: "Rohan placed his bean sprout inside a dark wardrobe for two weeks, watering it every day." What will happen to Rohan\'s plant?',
    options: makeOptions('synthesis',
      'The bean sprout will turn pale and fail to grow healthy leaves because it lacked sunlight.',
      ['The plant will grow twice as fast because it had plenty of water.', 'The plant will produce dark purple flowers inside the wardrobe.', 'The plant will transform into a mushroom.']
    ),
    learning_objective: 'Synthesizing two pieces of factual evidence to predict a scientific outcome.',
    hint: 'Combine the requirement in Fact 1 with what was missing in Fact 2.',
    irt_a: 1.25,
    irt_b: -1.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 3 Science & English Integration'
  },
  {
    scenario_code: 'ENG-34-SYN-02',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Notice A: "The swimming pool closes whenever lightning flashes within 5 miles." Notice B: "At 2:00 PM, thunder rumbled and lightning struck a radio tower 2 miles from the pool." What action must the lifeguard take?',
    options: makeOptions('synthesis',
      'Order all swimmers out of the pool and close the facility immediately.',
      ['Allow swimmers to stay in the water if they wear goggles.', 'Turn on the pool heaters to protect the swimmers.', 'Wait for two hours before making any announcements.']
    ),
    learning_objective: 'Integrating a safety rule with a situational occurrence.',
    hint: 'Is 2 miles within the 5-mile safety radius mentioned in Notice A?',
    irt_a: 1.3,
    irt_b: -1.2,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 3 English'
  },
  {
    scenario_code: 'ENG-34-SYN-03',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Story 1: "Liam loved playing soccer, but he practiced alone in his backyard every evening." Story 2: "When Liam joined the town youth team, he struggled to pass the ball to open teammates." What skill does Liam need to develop?',
    options: makeOptions('synthesis',
      'Teamwork and communicating with other players during a game.',
      ['Kicking the ball harder toward the goalposts.', 'Buying more expensive soccer boots.', 'Practicing soccer only once a month.']
    ),
    learning_objective: 'Synthesizing character backstory with a social challenge.',
    hint: 'Consider the difference between practicing alone and playing on a team.',
    irt_a: 1.2,
    irt_b: -1.1,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 3 Reading'
  },
  {
    scenario_code: 'ENG-34-SYN-04',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Text A: "Bees carry pollen from flower to flower, helping apple trees produce fruit." Text B: "A sudden cold freeze killed the local bee colony in early spring." What will most likely happen to the orchard\'s apple harvest in autumn?',
    options: makeOptions('synthesis',
      'The orchard will produce significantly fewer apples because pollination was disrupted.',
      ['The apple trees will produce giant red apples immediately.', 'The orchard will start growing oranges instead.', 'The cold freeze will make the apples sweeter than usual.']
    ),
    learning_objective: 'Deducing cause-and-effect across biological ecological texts.',
    hint: 'If bees help trees make fruit, what happens when there are no bees?',
    irt_a: 1.35,
    irt_b: -1.0,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 4 Synthesis'
  },
  {
    scenario_code: 'ENG-34-SYN-05',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: 'Book Log: "Maya read 15 pages on Monday and 25 pages on Tuesday. Her brother Noah read 10 pages each day from Monday through Wednesday." Who read more total pages by Wednesday evening?',
    options: makeOptions('synthesis',
      'Maya read 40 pages while Noah read 30 pages, so Maya read more.',
      ['Noah read more because he read on three separate days.', 'Both read the exact same number of pages.', 'Noah read 50 pages while Maya read 35 pages.']
    ),
    learning_objective: 'Combining multi-sentence quantitative statements into a comparative conclusion.',
    hint: 'Add Maya\'s pages (15 + 25) and compare to Noah\'s pages (10 + 10 + 10).',
    irt_a: 1.4,
    irt_b: -0.7,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 4 Mathematics & English'
  },
  {
    scenario_code: 'ENG-34-SYN-06',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: 'Source 1: "Earthworms tunnel through soil, creating channels that allow oxygen and rainwater to reach plant roots." Source 2: "Gardeners often add compost and encourage worms in their vegetable patches." Why do gardeners welcome earthworms?',
    options: makeOptions('synthesis',
      'Because earthworms naturally aerate the soil and support healthy root growth.',
      ['Because worms frighten away birds and rabbits.', 'Because worms eat vegetable weeds before they sprout.', 'Because worms make the soil completely dry.']
    ),
    learning_objective: 'Synthesizing ecological function with human agricultural practice.',
    hint: 'Connect the channels earthworms dig with what plant roots need to thrive.',
    irt_a: 1.35,
    irt_b: -0.6,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Checkpoint Stage 4'
  },
  {
    scenario_code: 'ENG-34-SYN-07',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: 'Passage 1: "The town bridge was built of timber planks in 1850." Passage 2: "Modern heavy cargo trucks weigh five times more than horse-drawn wagons from 1850." Passage 3: "The town council recently banned cargo trucks from crossing the bridge." Why did the council enact this ban?',
    options: makeOptions('synthesis',
      'The historic wooden bridge was not designed to bear the heavy weight of modern trucks.',
      ['The council prefers horse-drawn wagons for daily transport.', 'The trucks were too loud for fish swimming beneath the bridge.', 'Timber planks become stronger when heavy trucks drive over them.']
    ),
    learning_objective: 'Integrating historical material constraints with modern civic regulations.',
    hint: 'Connect the weight of modern trucks with the age and material of the bridge.',
    irt_a: 1.45,
    irt_b: -0.5,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 4 Informational Text'
  },
  {
    scenario_code: 'ENG-34-SYN-08',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: 'Report A: "Emperor penguins huddle tightly in circles containing hundreds of birds during blizzards." Report B: "Thermal sensors show that the center of an emperor penguin huddle reaches 37°C while the outer air is -40°C." Report C: "Penguins continuously take turns rotating from the freezing outer rim to the warm core." What is the adaptive purpose of this rotation?',
    options: makeOptions('synthesis',
      'It ensures that all members of the colony share equitable access to warmth and survive the storm.',
      ['It allows the strongest penguins to stay permanently at the center.', 'It confuses predatory leopard seals swimming underneath the ice.', 'It helps the penguins practice marching in military formations.']
    ),
    learning_objective: 'Synthesizing biological observation with thermal data and behavioral adaptation.',
    hint: 'What would happen to the penguins stuck on the outside if they never swapped places?',
    irt_a: 1.55,
    irt_b: -0.2,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary English Olympiad / SASMO'
  },
  {
    scenario_code: 'ENG-34-SYN-09',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: 'Text 1: "Solar cookers use curved shiny mirrors to concentrate sunlight onto a dark cooking pot." Text 2: "In arid regions with scarce firewood, solar cookers prevent families from having to cut down scarce desert shrubs." What environmental benefit results from using solar cookers in arid areas?',
    options: makeOptions('synthesis',
      'Conserving fragile desert vegetation and curbing local deforestation.',
      ['Increasing the amount of smoke and soot in household kitchens.', 'Making desert shrubs grow twice as tall.', 'Eliminating the need for drinking water in desert villages.']
    ),
    learning_objective: 'Synthesizing technological mechanisms with ecological conservation outcomes.',
    hint: 'Think about what happens to the desert trees when people do not need firewood.',
    irt_a: 1.5,
    irt_b: -0.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 4 Advanced'
  },
  {
    scenario_code: 'ENG-34-SYN-10',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: 'Tale 1: "The swift hare boasted that no animal could ever match his speed." Tale 2: "The slow tortoise committed to walking without pausing a single second." Tale 3: "Overconfident in his lead, the hare fell asleep under a tree while the tortoise steadily crossed the finish line." What core life lesson emerges from combining these tales?',
    options: makeOptions('synthesis',
      'Consistent diligence and modesty can triumph over arrogant, unapplied natural talent.',
      ['Sleeping during the daytime is always healthy for athletes.', 'Fast runners should never participate in friendly contests.', 'Tortoises are biologically swifter than resting hares.']
    ),
    learning_objective: 'Synthesizing narrative arcs into an overarching moral axiom.',
    hint: 'Compare the hare\'s attitude with the tortoise\'s steady effort.',
    irt_a: 1.6,
    irt_b: 0.0,
    irt_c: 0.25,
    international_benchmark: 'ICSE Grade 4 English Literature'
  },

  // ── Evaluating & Reflecting (10 items) ──
  {
    scenario_code: 'ENG-34-EVL-01',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: '"Drink ZapJuice! It gives you instant superhero wings and laser speed!" What is the main intention of this advertisement?',
    options: makeOptions('evaluatingReflecting',
      'To persuade children to buy the drink using playful exaggeration.',
      ['To warn consumers about flying safety hazards.', 'To scientifically explain how bird wings grow.', 'To give accurate nutritional data about vitamins.']
    ),
    learning_objective: 'Identifying the persuasive purpose and hyperbole in commercial advertisements.',
    hint: 'Can a fruit juice really grow wings on your back?',
    irt_a: 1.2,
    irt_b: -1.4,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 4 Critical Reading'
  },
  {
    scenario_code: 'ENG-34-EVL-02',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'Poster: "Help Keep Our Playground Clean! Toss wrappers into the recycling bins." What tone does this poster use?',
    options: makeOptions('evaluatingReflecting',
      'Encouraging and civic-minded.',
      ['Furious and threatening.', 'Humorous and sarcastic.', 'Sorrowful and tearful.']
    ),
    learning_objective: 'Recognizing community tone and civic voice in public notices.',
    hint: 'Notice the friendly words "Help Keep Our Playground Clean!".',
    irt_a: 1.15,
    irt_b: -1.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 3 English'
  },
  {
    scenario_code: 'ENG-34-EVL-03',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: '"The stormy wind howled like an angry wolf rattling the window shutters." Why did the author describe the wind as an "angry wolf"?',
    options: makeOptions('evaluatingReflecting',
      'To make the storm feel fierce, noisy, and frightening to the reader.',
      ['To inform the reader that a real wolf was outside the house.', 'To explain that wolves enjoy blowing air on shutters.', 'To prove that window shutters are built of wolf fur.']
    ),
    learning_objective: 'Evaluating author\'s craft and the impact of figurative language on mood.',
    hint: 'What feeling does an "angry wolf" howling create inside a cozy room?',
    irt_a: 1.25,
    irt_b: -1.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 3'
  },
  {
    scenario_code: 'ENG-34-EVL-04',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'standard',
    prompt: 'A student writes: "Cats are 100% better than dogs because dogs are way too energetic and cats love to nap peacefully." Is this statement a fact or an opinion?',
    options: makeOptions('evaluatingReflecting',
      'It is an opinion because personal preferences about pets differ from person to person.',
      ['It is a verified scientific fact proved by veterinarians.', 'It is a mathematical calculation about animal speed.', 'It is a law passed by the city council.']
    ),
    learning_objective: 'Distinguishing between personal opinion and empirical fact.',
    hint: 'Can everyone agree on whether energetic dogs or quiet cats are "better"?',
    irt_a: 1.3,
    irt_b: -1.0,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 3 Reading'
  },
  {
    scenario_code: 'ENG-34-EVL-05',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: '"Don\'t be the only kid on your street without the UltraGlide Scooter! Everyone is riding one!" Which advertising technique is being used here?',
    options: makeOptions('evaluatingReflecting',
      'Bandwagon appeal: making the reader feel left out if they do not join the group.',
      ['Expert scientific testimony from engineers.', 'Detailed statistical breakdown of wheel bearings.', 'Historical evidence from the 19th century.']
    ),
    learning_objective: 'Deconstructing persuasive peer-pressure and bandwagon rhetoric.',
    hint: 'Notice phrases like "Don\'t be the only kid" and "Everyone is riding one".',
    irt_a: 1.35,
    irt_b: -0.7,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 4 English'
  },
  {
    scenario_code: 'ENG-34-EVL-06',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: 'Two reviews of a children\'s book: Reviewer 1 writes: "The colorful illustrations are dazzling and the story is hilarious!" Reviewer 2 writes: "The book is printed on glossy paper and contains 32 pages." Which review expresses an evaluative judgment?',
    options: makeOptions('evaluatingReflecting',
      'Reviewer 1, because words like "dazzling" and "hilarious" express subjective appreciation.',
      ['Reviewer 2, because counting pages requires deep critical thinking.', 'Both reviews are strictly objective scientific measurements.', 'Neither review provides any information about the book.']
    ),
    learning_objective: 'Evaluating subjective appraisal versus neutral descriptive reporting.',
    hint: 'Look for descriptive words that share personal taste rather than physical specs.',
    irt_a: 1.4,
    irt_b: -0.6,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 4 Checkpoint'
  },
  {
    scenario_code: 'ENG-34-EVL-07',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'advanced',
    prompt: 'In a story about an injured bird, the author finishes with: "As the sparrow took flight into the blue sky, Maya felt her own worries lift away with its wings." How does the author connect the bird\'s flight with Maya\'s feelings?',
    options: makeOptions('evaluatingReflecting',
      'The physical release of the healed bird symbolizes Maya\'s emotional relief and freedom.',
      ['Maya physically flew through the air alongside the sparrow.', 'The bird taught Maya how to avoid doing homework.', 'The author is explaining how bird feathers deflect wind.']
    ),
    learning_objective: 'Reflecting on symbolic parallels between external actions and internal emotional states.',
    hint: 'What does watching something fly away feel like when you have heavy worries?',
    irt_a: 1.4,
    irt_b: -0.5,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 4 Reflection'
  },
  {
    scenario_code: 'ENG-34-EVL-08',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: '"The mayor proclaimed that building a four-lane highway through the municipal wildflower park would bring unprecedented prosperity, conveniently neglecting to mention that three hundred century-old oaks would be felled." What stance does the author hold toward the mayor\'s proclamation?',
    options: makeOptions('evaluatingReflecting',
      'Critical and skeptical, exposing the hidden environmental cost the mayor ignored.',
      ['Enthusiastic and celebratory regarding highway construction.', 'Completely indifferent to both the park and the highway.', 'Praising the mayor\'s transparent honesty.']
    ),
    learning_objective: 'Detecting authorial irony, bias, and critical stance in editorial reporting.',
    hint: 'Notice the phrase "conveniently neglecting to mention".',
    irt_a: 1.55,
    irt_b: -0.2,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary English Olympiad'
  },
  {
    scenario_code: 'ENG-34-EVL-09',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: 'An author describes two brothers: "Julian polished his silver medals until they mirrored his vanity; Arthur slipped his quietly into a desk drawer and headed outside to coach the younger children." How does the author subtly guide the reader\'s moral judgment?',
    options: makeOptions('evaluatingReflecting',
      'By contrasting Julian\'s self-absorbed pride with Arthur\'s humble generosity.',
      ['By demonstrating that silver is a superior metal to gold.', 'By proving that Julian is an ineffective athlete.', 'By arguing that children should not be coached outdoors.']
    ),
    learning_objective: 'Analyzing how character juxtaposition shapes reader empathy and ethical judgment.',
    hint: 'Look at what each brother does with his medals.',
    irt_a: 1.5,
    irt_b: -0.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 4 Advanced'
  },
  {
    scenario_code: 'ENG-34-EVL-10',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '3-4',
    difficulty: 'olympiad',
    prompt: '"To label the ancient oak a simple tree is to call the ocean a puddle; it was an entire bustling city for countless squirrels, owls, and beetles." What rhetorical device is the author using to emphasize the tree\'s ecological importance?',
    options: makeOptions('evaluatingReflecting',
      'Analogy and contrast to highlight how vast and vital the tree\'s miniature ecosystem is.',
      ['Literal description proving that squirrels hold municipal elections.', 'Statistical sampling of ocean water salinity.', 'A chronological historical timeline of timber logging.']
    ),
    learning_objective: 'Evaluating figurative analogies and scale shifts in environmental prose.',
    hint: 'Why does the author compare calling the tree "just a tree" to calling the ocean "a puddle"?',
    irt_a: 1.6,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'ICSE Grade 4 English Language'
  }
];
