import { ScenarioDef, makeOptions } from './english_types';

export const englishBand5_6: ScenarioDef[] = [
  // ── Understanding (10 items) ──
  {
    scenario_code: 'ENG-56-UND-01',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: '"The fennec fox remains sequestered subterraneanly throughout the blistering daylight hours, emerging only when twilight cools the Sahara dunes." What behavioral adaptation is described in this passage?',
    options: makeOptions('understanding',
      'Nocturnal behavior engineered to conserve internal moisture and avoid intense daytime heat.',
      ['Hunting diurnal desert rodents that only sleep when darkness falls.', 'Impaired eyesight that functions exclusively in dim twilight illumination.', 'Seasonal migration toward coastal salt marshes during peak summer.']
    ),
    learning_objective: 'Interpreting ecological adaptations and descriptive vocabulary in informational prose.',
    hint: 'Consider why an animal would stay underground during daylight and come out at twilight.',
    irt_a: 1.15,
    irt_b: -0.7,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 5 English / MOE PSLE Preparation'
  },
  {
    scenario_code: 'ENG-56-UND-02',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: '"The apprentice blacksmith watched the glowing iron bar slowly fade from brilliant orange to a sullen charcoal gray, realizing his window to hammer the blade had closed." What does "window" mean in this sentence?',
    options: makeOptions('understanding',
      'A limited opportunity or timeframe to shape the metal while it remained sufficiently malleable.',
      ['A glass pane set in the forge wall to vent toxic coal smoke.', 'A carved aperture through which the master smith evaluated work.', 'A measurement of the physical length of the cooling anvil.']
    ),
    learning_objective: 'Deducing contextual and figurative word meanings from narrative context.',
    hint: 'Think about what closes when metal cools down and becomes too hard to strike.',
    irt_a: 1.2,
    irt_b: -0.6,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 5 Checkpoint'
  },
  {
    scenario_code: 'ENG-56-UND-03',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: '"The old botanist spoke of the rainforest canopy not as a passive ceiling of leaves, but as a dynamic emerald battlefield where vines and saplings wrestled incessantly for every ray of sunlight." What central impression does this passage convey?',
    options: makeOptions('understanding',
      'Intense, ongoing competition among plant species for vital solar energy.',
      ['The quiet serenity and complete harmony of an untouched tropical ecosystem.', 'The damage caused by human lumber companies felling ancient trees.', 'The poisonous nature of creeping vines on the forest floor.']
    ),
    learning_objective: 'Analyzing metaphor and authorial conception of ecological dynamics.',
    hint: 'Notice the words "battlefield", "wrestled", and "competition for sunlight".',
    irt_a: 1.25,
    irt_b: -0.5,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 5 Informational Text'
  },
  {
    scenario_code: 'ENG-56-UND-04',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: '"Elena stood at the crossroads. To the left lay the well-worn cobblestones of her village; to the right, an overgrown path vanished into the mist. She checked her compass, adjusted her rucksack, and stepped firmly to the right." What does Elena\'s decision reveal about her character?',
    options: makeOptions('understanding',
      'Courage, self-reliance, and a deliberate willingness to embrace uncertain adventures.',
      ['Foolishness and an inability to read a standard magnetic compass.', 'A deep hatred for cobblestones and village life.', 'Regret over leaving behind her childhood friends.']
    ),
    learning_objective: 'Inferring character archetypes and traits from symbolic choices.',
    hint: 'She took the unknown overgrown path deliberately after checking her tools.',
    irt_a: 1.3,
    irt_b: -0.4,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 5 Reading Literary Experience'
  },
  {
    scenario_code: 'ENG-56-UND-05',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: '"In honeybee colonies, the waggle dance is not random twitching; it is a sophisticated spatial compass that encodes the precise angle relative to the sun and the distance to nectar sources." What is the main idea of this excerpt?',
    options: makeOptions('understanding',
      'Honeybee waggle dances serve as an intricate symbolic system for communicating food locations.',
      ['Bees dance purely to celebrate the arrival of springtime flowers.', 'The sun\'s ultraviolet radiation damages the nervous system of worker bees.', 'Honeybees rely entirely on scent trails rather than visual communication.']
    ),
    learning_objective: 'Summarizing key scientific concepts and functional animal behavior.',
    hint: 'Focus on what the waggle dance communicates: angle and distance to food.',
    irt_a: 1.2,
    irt_b: -0.5,
    irt_c: 0.25,
    international_benchmark: 'CBSE / ICSE Class 5 English'
  },
  {
    scenario_code: 'ENG-56-UND-06',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: '"The museum conservator scrutinized the painting under ultraviolet light, discovering that beneath the tranquil landscape lay an agitated, unfinished self-portrait of the artist." What does this revelation imply about the artist\'s process?',
    options: makeOptions('understanding',
      'The artist reused canvas, deliberately concealing an earlier intense personal work under a calm exterior.',
      ['The painting had been created by two rival artists fighting over one easel.', 'Ultraviolet rays chemically altered the colors of the original oil paint.', 'The artist forgot how to paint landscapes and switched to portraits.']
    ),
    learning_objective: 'Inferring hidden artistic intentionality from physical forensic evidence.',
    hint: 'Why would someone paint a peaceful scene right over an agitated self-portrait?',
    irt_a: 1.35,
    irt_b: -0.2,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 6 PSLE Foundation'
  },
  {
    scenario_code: 'ENG-56-UND-07',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: '"The silence that fell over the debate hall was not passive indifference; it was the tense, breathless pause of a jury weighing an irrevocable verdict." What does this comparison convey about the audience?',
    options: makeOptions('understanding',
      'They were deeply engaged, captivated, and conscious of the heavy consequence of the argument.',
      ['They were exhausted and preparing to leave before the speaker finished.', 'They were legally obligated to deliver a criminal court sentence.', 'They were confused by the technical jargon used by the speaker.']
    ),
    learning_objective: 'Analyzing psychological tension and atmosphere created through metaphor.',
    hint: 'Notice the contrast: not "passive indifference", but weighing an "irrevocable verdict".',
    irt_a: 1.4,
    irt_b: 0.0,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary 1 Checkpoint Stage 6'
  },
  {
    scenario_code: 'ENG-56-UND-08',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: '"To Marcus, the laboratory was less a sterile room of test tubes and more an alchemist\'s sanctuary, where common minerals were coaxed into shedding their mundane secrets." What does the author suggest about Marcus\'s perspective on science?',
    options: makeOptions('understanding',
      'He views scientific research as an imaginative, almost magical pursuit of fundamental truth.',
      ['He rejects modern chemistry in favor of fraudulent medieval superstitions.', 'He finds laboratory safety protocols tedious and counterproductive.', 'He is primarily interested in transmuting lead into marketable gold jewelry.']
    ),
    learning_objective: 'Deconstructing character worldview and intellectual temperament.',
    hint: 'Notice terms like "sanctuary", "coaxed", and "shedding mundane secrets".',
    irt_a: 1.35,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 6 Literature'
  },
  {
    scenario_code: 'ENG-56-UND-09',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: '"The ancient aqueduct straddling the valley stood as a monument not merely to Roman hydraulic engineering, but to an unyielding refusal to let topography dictate civic ambition." What philosophical assertion underlies this statement?',
    options: makeOptions('understanding',
      'Human determination and civil engineering can overcome severe natural geographical barriers to serve society.',
      ['Roman builders prioritized ornamental stone architecture above practical water delivery.', 'Natural valleys are inherently hostile environments that must be demolished.', 'Aqueducts are ecologically destructive monuments that disrupt river currents.']
    ),
    learning_objective: 'Interpreting philosophical subtext in historical architecture commentary.',
    hint: 'Notice: refusal to let "topography dictate civic ambition".',
    irt_a: 1.5,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary English Olympiad / PSLE High Distinction'
  },
  {
    scenario_code: 'ENG-56-UND-10',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: '"The critic noted that while the young pianist possessed flawless mechanical dexterity, her performance lacked the tender vulnerability of an artist who has known genuine grief." What shortcoming does the critic pinpoint?',
    options: makeOptions('understanding',
      'Emotional depth and expressive authenticity, despite having perfect technical finger accuracy.',
      ['Inaccurate timing and frequent missed notes in complex musical cadenzas.', 'Inadequate physical hand stamina during extended concerto movements.', 'Poor choice of classical repertoire for an international audience.']
    ),
    learning_objective: 'Differentiating between technical proficiency and expressive emotional artistry.',
    hint: 'Contrast "flawless mechanical dexterity" with "lacked tender vulnerability".',
    irt_a: 1.55,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Checkpoint Stage 6 Olympiad Stream'
  },

  // ── Locating Information (10 items) ──
  {
    scenario_code: 'ENG-56-LOC-01',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Robotics Expo Guide: "Pavilion Alpha (Hall 1): Autonomous Drones; Pavilion Beta (Hall 3): Surgical Nanobots; Pavilion Gamma (Hall 4): Biomimetic Prosthetics. Keynote Address occurs in the Central Amphitheatre at 11:15 AM." Where can a visitor view surgical nanobots?',
    options: makeOptions('locatingInformation',
      'Pavilion Beta in Hall 3',
      ['Pavilion Alpha in Hall 1', 'Pavilion Gamma in Hall 4', 'Central Amphitheatre']
    ),
    learning_objective: 'Scanning technical conference guides for precise location identifiers.',
    hint: 'Match "Surgical Nanobots" with its exact Pavilion and Hall designation.',
    irt_a: 1.2,
    irt_b: -0.8,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 5 Factual Scanning'
  },
  {
    scenario_code: 'ENG-56-LOC-02',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Space Probe Telemetry: "Probe Voyager-Prime crossed the heliopause at an orbital velocity of 17.2 km/s. Onboard hydrazine fuel reserves stand at 14.8 liters, sufficient to maintain antenna orientation toward Earth until November 2031." What is the remaining fuel volume?',
    options: makeOptions('locatingInformation',
      '14.8 liters',
      ['17.2 km/s', '2031 liters', '50 liters']
    ),
    learning_objective: 'Extracting specific scientific parameters and quantities from technical telemetry.',
    hint: 'Scan for the phrase "fuel reserves stand at".',
    irt_a: 1.25,
    irt_b: -0.7,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 5 English'
  },
  {
    scenario_code: 'ENG-56-LOC-03',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Archaeological Dig Bulletin: "Trench C revealed three distinct ceramic shards from the late Bronze Age, whereas Trench A contained exclusively iron spearheads dated to 650 BCE. Trench B has been suspended due to water seepage." Which trench yielded late Bronze Age ceramics?',
    options: makeOptions('locatingInformation',
      'Trench C',
      ['Trench A', 'Trench B', 'Trench D']
    ),
    learning_objective: 'Matching artifact types to spatial trench identifiers in field logs.',
    hint: 'Find the sentence describing "ceramic shards from the late Bronze Age".',
    irt_a: 1.3,
    irt_b: -0.6,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 5'
  },
  {
    scenario_code: 'ENG-56-LOC-04',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Clean Energy Report: "While onshore wind turbines operate at an average capacity factor of 35%, offshore installations reach up to 52% owing to consistent maritime gale velocities. Solar photovoltaics in the same region average 21%." What is the capacity factor for offshore wind installations?',
    options: makeOptions('locatingInformation',
      'Up to 52%',
      ['35%', '21%', '100%']
    ),
    learning_objective: 'Retrieving precise comparative percentages across energy sectors.',
    hint: 'Distinguish between "onshore", "offshore", and "solar".',
    irt_a: 1.25,
    irt_b: -0.5,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 5 Informational Text'
  },
  {
    scenario_code: 'ENG-56-LOC-05',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'First Aid Protocol: "In case of thermal burns: cool the affected area immediately under clean, running lukewarm water for at least 20 minutes. Do not apply ice, butter, or adhesive bandages directly to blistered skin." For how long should lukewarm water be applied?',
    options: makeOptions('locatingInformation',
      'At least 20 minutes',
      ['5 minutes', '2 hours', 'Until ice is applied']
    ),
    learning_objective: 'Locating mandatory procedural time thresholds in emergency protocols.',
    hint: 'Scan for the time duration associated with "running lukewarm water".',
    irt_a: 1.35,
    irt_b: -0.4,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 6 English'
  },
  {
    scenario_code: 'ENG-56-LOC-06',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: 'Marine Biology Field Log: "Specimen 402, a giant Pacific octopus, demonstrated tactile problem-solving by opening a childproof medicine jar in 42 seconds. Specimen 405 completed the maze navigation task in 118 seconds after three preliminary orientation runs." How quickly did Specimen 402 open the jar?',
    options: makeOptions('locatingInformation',
      '42 seconds',
      ['118 seconds', '3 minutes', '405 seconds']
    ),
    learning_objective: 'Disentangling multiple numbered specimen IDs and distinct behavioral test times.',
    hint: 'Look only at Specimen 402 and the task of opening the jar.',
    irt_a: 1.4,
    irt_b: -0.2,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary 1 Stage 6'
  },
  {
    scenario_code: 'ENG-56-LOC-07',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: 'Aviation Handbook: "Maximum certified ceiling for Model Skyhawk-IV is 14,000 feet Mean Sea Level (MSL). Oxygen masks must be donned by all occupants if cabin pressure exceeds an altitude equivalent of 10,000 feet for more than 30 consecutive minutes." Under what condition must oxygen masks be donned?',
    options: makeOptions('locatingInformation',
      'When cabin pressure exceeds a 10,000-foot equivalent for over 30 consecutive minutes.',
      ['Whenever the aircraft climbs above 5,000 feet.', 'Only upon landing at airports higher than 14,000 feet MSL.', 'Immediately upon starting the engines before takeoff.']
    ),
    learning_objective: 'Retrieving multi-conditional regulatory thresholds from technical guidelines.',
    hint: 'Check both the altitude threshold and the time requirement.',
    irt_a: 1.4,
    irt_b: 0.0,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 6 Informational'
  },
  {
    scenario_code: 'ENG-56-LOC-08',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: 'Deep-Sea Research Dispatch: "At the Mariana Trench (Challenger Deep, 10,928 meters), hydrostatic pressure reaches approximately 1,086 bar—over 1,000 times atmospheric pressure at sea level. Despite this, xenophyophores, giant single-celled protozoans measuring up to 20 centimeters, thrive in the abyssal sediment." What is the maximum recorded size of xenophyophores mentioned?',
    options: makeOptions('locatingInformation',
      'Up to 20 centimeters',
      ['10,928 meters', '1,086 bar', '1 millimeter']
    ),
    learning_objective: 'Scanning high-density scientific abstracts for organism physical dimensions.',
    hint: 'Focus on the organism "xenophyophores" and the dimension unit "centimeters".',
    irt_a: 1.45,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary English Olympiad'
  },
  {
    scenario_code: 'ENG-56-LOC-09',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: 'Archival Treaty Summary: "Under Article VII of the 1894 Maritime Accord, coastal states retained exclusive salvage rights up to 12 nautical miles from the low-water baseline, provided formal diplomatic notice of recovery operations was submitted within 72 hours of vessel grounding." Within what timeframe must recovery notice be filed?',
    options: makeOptions('locatingInformation',
      'Within 72 hours of vessel grounding',
      ['Within 12 days of salvage conclusion', 'Within 1894 hours of treaty ratification', 'Immediately upon entering the 12-mile baseline']
    ),
    learning_objective: 'Isolating specific compliance windows within dense legal prose.',
    hint: 'Find the time constraint tied to "diplomatic notice of recovery operations".',
    irt_a: 1.5,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary Checkpoint High Distinction'
  },
  {
    scenario_code: 'ENG-56-LOC-10',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: 'Bioacoustics Field Study: "Recordings in the Svalbard archipelago confirmed that male bowhead whales emit complex acoustic songs spanning frequencies from 20 Hz to 5 kHz, repeating cyclical themes every 45 to 90 seconds throughout continuous polar darkness." What is the upper acoustic frequency emitted by these bowhead whales?',
    options: makeOptions('locatingInformation',
      '5 kHz (5,000 Hz)',
      ['20 Hz', '90 seconds', '45 Hz']
    ),
    learning_objective: 'Extracting upper bounds in frequency ranges from marine acoustics literature.',
    hint: 'Look at the range "from 20 Hz to ...".',
    irt_a: 1.55,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 6 English Language Examination'
  },

  // ── Synthesis (10 items) ──
  {
    scenario_code: 'ENG-56-SYN-01',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Article 1: "Mangrove root systems dissipate ocean storm wave energy and trap coastal sediment." Article 2: "Communities situated behind intact coastal mangrove forests suffered 70% less structural inundation damage during Cyclone Vayu than communities with cleared shorelines." What synthesis unites both articles?',
    options: makeOptions('synthesis',
      'Preserving natural mangrove buffers directly protects human settlements from destructive cyclonic waves.',
      ['Mangroves only thrive in areas subject to catastrophic hurricane strikes.', 'Coastal villages should replace mangrove forests with concrete seawalls.', 'Storm waves carry sediment away from mangrove estuaries into deep ocean trenches.']
    ),
    learning_objective: 'Synthesizing ecological data with civic disaster mitigation outcomes.',
    hint: 'Connect the wave-dissipating property of roots to the 70% reduction in storm damage.',
    irt_a: 1.25,
    irt_b: -0.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 5 Science & English'
  },
  {
    scenario_code: 'ENG-56-SYN-02',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Text Alpha: "Ancient Caravans crossing the hyper-arid Rub\' al Khali depended on clusters of wild date palms as survival landmarks." Text Beta: "Hydrologists note that date palms can only germinate where subterranean aquifers lie within three meters of the desert surface." What deduction follows from cross-referencing these texts?',
    options: makeOptions('synthesis',
      'Caravans relied on date palms because their presence signaled accessible freshwater underground.',
      ['Date palms survive without any groundwater by absorbing ambient humidity.', 'Caravans avoided date palm groves due to the risk of quicksand.', 'Ancient travelers planted date palms to absorb excess desert floodwaters.']
    ),
    learning_objective: 'Combining botanical hydrology with historical navigation practices.',
    hint: 'Why would desert travelers look for a plant that only grows where water is close to the surface?',
    irt_a: 1.3,
    irt_b: -0.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 5 Synthesis'
  },
  {
    scenario_code: 'ENG-56-SYN-03',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Source X: "Electric vehicle batteries require lithium, nickel, and cobalt, minerals mined in environmentally delicate ecosystems." Source Y: "Switching from internal combustion engines to electric transportation slashes operational tailpipe carbon emissions by up to 80%." How can these perspectives be integrated?',
    options: makeOptions('synthesis',
      'Electric vehicles significantly reduce atmospheric emissions, though mineral extraction poses localized ecological challenges that require responsible lifecycle management.',
      ['Electric vehicles produce zero net environmental impact across their entire lifecycle.', 'Internal combustion engines are ecologically superior because mining is completely unnecessary.', 'Battery recycling eliminates all need for raw mineral extraction immediately.']
    ),
    learning_objective: 'Synthesizing nuanced trade-offs across industrial and environmental texts.',
    hint: 'Balance the clear reduction in carbon emissions with the environmental impact of mining.',
    irt_a: 1.35,
    irt_b: -0.3,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 5 Nonfiction Synthesis'
  },
  {
    scenario_code: 'ENG-56-SYN-04',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Report 1: "Regular physical exercise stimulates brain-derived neurotrophic factor (BDNF), a protein that accelerates the creation of new memory synapses." Report 2: "Students who engaged in 30 minutes of aerobic running before morning mathematics scored 18% higher on spatial memory tests." What comprehensive conclusion can be drawn?',
    options: makeOptions('synthesis',
      'Aerobic exercise promotes neural proteins that directly enhance cognitive retention and mathematical performance.',
      ['Running makes students too fatigued to complete long mathematical problem sets.', 'BDNF is only produced while students are seated in quiet classrooms.', 'Spatial memory has no connection to neurological brain functions.']
    ),
    learning_objective: 'Synthesizing biochemical mechanisms with real-world academic performance data.',
    hint: 'Connect BDNF (synapse creation) with the higher test scores in spatial memory.',
    irt_a: 1.3,
    irt_b: -0.2,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 5 Complex Synthesis'
  },
  {
    scenario_code: 'ENG-56-SYN-05',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: 'Passage A: "The library\'s archival budget decreased by 25% this year." Passage B: "Digital subscription fees for international research journals increased by 15%." Passage C: "The head librarian announced the cancellation of three physical print magazine contracts." What synthesized rationale explains the librarian\'s decision?',
    options: makeOptions('synthesis',
      'Faced with reduced funding and rising digital costs, the library had to trim print expenditures to balance its operating budget.',
      ['The librarian dislikes physical magazines and prefers audiobooks exclusively.', 'Digital journals were banned by the university board of directors.', 'The library received an anonymous cash donation that covered all subscription shortfalls.']
    ),
    learning_objective: 'Synthesizing budget constraints and cost escalations into an administrative deduction.',
    hint: 'Look at both the declining budget and the increasing costs.',
    irt_a: 1.4,
    irt_b: 0.0,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 6 PSLE Synthesis'
  },
  {
    scenario_code: 'ENG-56-SYN-06',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: 'Study 1: "Nighttime light pollution disrupts nocturnal birds that navigate using the natural positions of stars." Study 2: "Cities that implemented amber-spectrum downward-shielded streetlights observed a 60% drop in disoriented migratory bird collisions." What holistic strategy is supported by this evidence?',
    options: makeOptions('synthesis',
      'Targeted municipal lighting design can preserve celestial navigation cues and substantially protect migrating avian populations.',
      ['Cities should eliminate all public streetlights to completely restore pre-industrial darkness.', 'Nocturnal birds will eventually evolve biological radar to replace optical navigation.', 'Amber lighting is exclusively used to accelerate vehicular traffic speed on highways.']
    ),
    learning_objective: 'Synthesizing ecological disruption with civic technological interventions.',
    hint: 'How does downward-shielded amber lighting solve the problem of star disruption?',
    irt_a: 1.45,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary 1 Stage 6'
  },
  {
    scenario_code: 'ENG-56-SYN-07',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: 'Perspective 1: "Autonomous crop-spraying drones reduce overall pesticide runoff by 40% through micro-targeted droplet dispensing." Perspective 2: "High initial equipment costs currently prevent smallholder farms from acquiring drone hardware without cooperative subsidies." What synthesis best represents the current status of agricultural drone technology?',
    options: makeOptions('synthesis',
      'While agricultural drones offer proven ecological advantages in chemical reduction, financial barriers require policy interventions for equitable adoption.',
      ['Drone technology is economically viable only for home gardeners with single-acre plots.', 'Pesticide runoff increases when drones replace manual backpack sprayers.', 'Smallholder farmers unanimously reject robotic farming techniques on philosophical grounds.']
    ),
    learning_objective: 'Synthesizing ecological efficacy with economic feasibility constraints.',
    hint: 'Recognize both the environmental benefit and the equipment cost barrier.',
    irt_a: 1.4,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 6 Informational Synthesis'
  },
  {
    scenario_code: 'ENG-56-SYN-08',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: 'Historical Text: "The introduction of the Gutenberg movable type printing press in 1440 reduced book manufacturing costs by 80%." Cultural Text: "Between 1450 and 1500, literacy rates in Central European trading hubs rose from under 6% to over 28%." What cross-textual historical inference is most rigorously justified?',
    options: makeOptions('synthesis',
      'Technological automation in text production drastically lowered the economic barrier to written knowledge, fueling a rapid expansion in popular literacy.',
      ['The printing press was invented specifically to train merchant apprentices in bookkeeping arithmetic.', 'Literacy rates increased exclusively because mandatory schooling was instituted by feudal kings.', 'Hand-copied illuminated manuscripts were completely destroyed by guild revolts.']
    ),
    learning_objective: 'Synthesizing technological innovation with macro-sociological cultural transformation.',
    hint: 'How does making books 80% cheaper directly cause more people to learn how to read?',
    irt_a: 1.55,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary English Olympiad / PSLE Distinction'
  },
  {
    scenario_code: 'ENG-56-SYN-09',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: 'Medical Source A: "Antibiotic overuse in livestock agriculture creates selective evolutionary pressure, accelerating bacterial resistance strains." Medical Source B: "Hospitals report a 35% rise in multidrug-resistant bloodstream infections linked to agricultural pathogens." What imperative synthesis follows?',
    options: makeOptions('synthesis',
      'Curtailing routine non-therapeutic antibiotic use in food production is vital for preserving the efficacy of human clinical antimicrobials.',
      ['Antibiotics should be replaced with synthetic vitamins in human neonatal wards.', 'Bacterial resistance strains cannot transfer from farm environments into urban clinical settings.', 'Livestock animals are biologically immune to antibiotic-resistant pathogens.']
    ),
    learning_objective: 'Connecting agricultural epidemiological practices with public health crises.',
    hint: 'Connect animal antibiotic overuse to the surge in resistant human infections.',
    irt_a: 1.6,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Checkpoint Stage 6 Advanced'
  },
  {
    scenario_code: 'ENG-56-SYN-10',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: 'Theory 1: "The linguistic relativity hypothesis argues that the vocabulary and structure of a language shape how its speakers perceive time and spatial orientation." Case Study: "Speakers of Guugu Yimithirr, who describe spatial position strictly via cardinal points (north, south, east, west) rather than relative terms (left, right), possess extraordinary geographical navigation recall even in unfamiliar windowless rooms." How does the case study corroborate Theory 1?',
    options: makeOptions('synthesis',
      'It demonstrates that linguistic reliance on absolute cardinal markers reinforces subconscious internal spatial dead-reckoning.',
      ['It proves that speakers of cardinal languages cannot understand left-handed tools.', 'It disproves the theory by showing navigation is purely dependent on atmospheric pressure.', 'It suggests that windowless rooms cause psychological disorientation in all linguistic cohorts.']
    ),
    learning_objective: 'Synthesizing linguistic theory with empirical anthropological fieldwork.',
    hint: 'How does always speaking in "north/south" train your brain to always know where north is?',
    irt_a: 1.65,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 6 English Language Advanced'
  },

  // ── Evaluating & Reflecting (10 items) ──
  {
    scenario_code: 'ENG-56-EVL-01',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: '"No serious competitor would ever drink plain tap water when ElectroMax Sport can supercharge cellular hydration!" Which persuasive device does this advertising slogan deploy?',
    options: makeOptions('evaluatingReflecting',
      'An appeal to elite status and peer exclusion: implying that non-users are unserious athletes.',
      ['Audited clinical laboratory results from medical university trials.', 'A balanced, impartial comparison of electrolyte solubility.', 'A chronological historical survey of athletic hydration.']
    ),
    learning_objective: 'Evaluating rhetorical appeals to status and in-group exclusivity.',
    hint: 'Notice the phrase "No serious competitor would ever...".',
    irt_a: 1.2,
    irt_b: -0.6,
    irt_c: 0.25,
    international_benchmark: 'PIRLS Grade 5 Critical Literacy'
  },
  {
    scenario_code: 'ENG-56-EVL-02',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: '"The old steam locomotive sighed a plume of white smoke, trembling wearily as if dreading the steep ascent over the mountain pass." What literary device is the author using, and to what effect?',
    options: makeOptions('evaluatingReflecting',
      'Personification, to endow the mechanical engine with human feelings of fatigue and reluctance.',
      ['Literal description of a biological organism climbing a hill.', 'Scientific data documenting coal combustion pressure in iron boilers.', 'Hyperbolic exaggeration proving that steam engines possess beating hearts.']
    ),
    learning_objective: 'Analyzing the emotional resonance and purpose of personification in narrative prose.',
    hint: 'Words like "sighed", "trembling wearily", and "dreading" are human traits applied to a machine.',
    irt_a: 1.25,
    irt_b: -0.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 5 English Literature'
  },
  {
    scenario_code: 'ENG-56-EVL-03',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'Two accounts of a school bake sale: Account A (Student Council Treasurer): "We raised $450, exceeding our playground fundraising goal by 15%." Account B (School Neighbor): "The event caused heavy traffic congestion and litter on Maple Street." How do the authors\' roles influence their accounts?',
    options: makeOptions('evaluatingReflecting',
      'Each author selectively highlights aspects that align with their distinct priorities—financial success versus community convenience.',
      ['Account A is an outright fabrication because bake sales cannot generate profit.', 'Account B proves that school bake sales should be outlawed permanently.', 'Both accounts are identical in tone and provide the same statistical data.']
    ),
    learning_objective: 'Reflecting on authorial stance, perspective, and selective presentation of evidence.',
    hint: 'Consider what matters most to the treasurer compared to what matters to a neighbor on the street.',
    irt_a: 1.3,
    irt_b: -0.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Primary Stage 5 Checkpoint'
  },
  {
    scenario_code: 'ENG-56-EVL-04',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'standard',
    prompt: 'An editorial argues: "Bicycle lanes on Main Street are an absolute catastrophe; my drive to work took four extra minutes on Tuesday morning!" What logical weakness undermines this argument?',
    options: makeOptions('evaluatingReflecting',
      'Overgeneralization based on a single personal inconvenience, ignoring broader urban safety and mobility benefits.',
      ['The author cited audited municipal vehicular traffic census records.', 'Bicycles are legally prohibited from traveling on paved asphalt roads.', 'The argument relies on excessive peer-reviewed economic research.']
    ),
    learning_objective: 'Identifying anecdotal bias and hasty generalization in opinion writing.',
    hint: 'Can one person\'s 4-minute delay prove that bike lanes are an "absolute catastrophe"?',
    irt_a: 1.35,
    irt_b: -0.3,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 5 Critical Evaluation'
  },
  {
    scenario_code: 'ENG-56-EVL-05',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: '"The scientist acknowledged that while the laboratory synthesis yielded high purity, mass industrial scaling remained unproven." What does this statement reveal about the author\'s tone and credibility?',
    options: makeOptions('evaluatingReflecting',
      'It conveys intellectual honesty and scientific objectivity by openly acknowledging real-world limitations.',
      ['It demonstrates that the scientist is incompetent and lacks laboratory training.', 'It proves the chemical compound is completely useless for commercial medicine.', 'It reflects an attempt to deceive investors with inflated claims.']
    ),
    learning_objective: 'Evaluating academic transparency, nuance, and author credibility.',
    hint: 'A credible scientist admits limitations rather than exaggerating perfection.',
    irt_a: 1.4,
    irt_b: 0.0,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary 6 PSLE Higher Order'
  },
  {
    scenario_code: 'ENG-56-EVL-06',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: '"The wildlife photographer spent fourteen freezing days in a snowblind without seeing a snow leopard, yet wrote: \'The mountain was not empty; it was patient.\'" How does this concluding sentence reflect the photographer\'s mindset?',
    options: makeOptions('evaluatingReflecting',
      'It illustrates deep reverence, humility, and philosophical acceptance of wild nature\'s elusive independence.',
      ['It expresses bitterness and anger toward elusive predators.', 'It indicates the photographer was hallucinating from extreme hypothermia.', 'It suggests the photographer intends to abandon wildlife photography.']
    ),
    learning_objective: 'Interpreting authorial reflection and philosophical depth in memoir prose.',
    hint: 'Notice how the author reframes "empty" into "patient".',
    irt_a: 1.45,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary 1 Stage 6 Literature'
  },
  {
    scenario_code: 'ENG-56-EVL-07',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'advanced',
    prompt: 'In an essay on space exploration, the author juxtaposes the billions spent on Mars orbiters with the millions of children lacking clean drinking water on Earth. What rhetorical objective is the author pursuing?',
    options: makeOptions('evaluatingReflecting',
      'Challenging the ethical allocation of societal resources and questioning global priorities.',
      ['Proving that Mars soil contains potable liquid groundwater.', 'Advocating for the total shutdown of all astronomical telescopes.', 'Arguing that rockets should be converted into municipal water tankers.']
    ),
    learning_objective: 'Deconstructing ethical juxtaposition and rhetorical inquiry in civic essays.',
    hint: 'Why place billions for Mars right beside millions of thirsty children?',
    irt_a: 1.4,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 6 Argumentative Reflection'
  },
  {
    scenario_code: 'ENG-56-EVL-08',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: '"The historian remarked: \'To write history solely from the victors\' proclamations is like reconstructing an entire forest from the diary of a single lumberjack.\'" What core methodological criticism is articulated through this analogy?',
    options: makeOptions('evaluatingReflecting',
      'Dominant institutional archives present a biased, incomplete narrative that erases the lived realities of the broader population.',
      ['Lumberjacks are unreliable observers of tree species.', 'Victors always tell the literal and complete truth in royal court chronicles.', 'Forest ecosystems cannot be studied using modern historical methods.']
    ),
    learning_objective: 'Critiquing historiographical bias and archival omission through metaphor.',
    hint: 'What does a lumberjack care about compared to the whole forest?',
    irt_a: 1.55,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Primary English Olympiad'
  },
  {
    scenario_code: 'ENG-56-EVL-09',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: '"The editorial described the software company\'s latest data collection policy as \'a benign modernization,\' masking the reality that user keystrokes were being monetized in real time." How does the author expose the corporation\'s euphemism?',
    options: makeOptions('evaluatingReflecting',
      'By contrasting the harmless, reassuring corporate label with the invasive reality of continuous data commercialization.',
      ['By demonstrating that software updates cause keyboard hardware malfunctions.', 'By endorsing the company\'s transparent data ethics.', 'By proving that keystroke logging speeds up word processing typing.']
    ),
    learning_objective: 'Deconstructing euphemistic corporate rhetoric and critical media literacy.',
    hint: 'Compare "benign modernization" with "user keystrokes monetized in real time".',
    irt_a: 1.6,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Checkpoint Stage 6 Advanced'
  },
  {
    scenario_code: 'ENG-56-EVL-10',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '5-6',
    difficulty: 'olympiad',
    prompt: '"When an author shifts suddenly from clinical third-person passive voice (\'the decision was executed\') to intimate first-person active voice (\'I signed the order\'), what emotional transformation is imposed upon the reader?"',
    options: makeOptions('evaluatingReflecting',
      'Bureaucratic detachment is shattered, confronting the reader with inescapable individual moral accountability.',
      ['The author signals that the preceding events were completely fictional.', 'The narrative transitions from historical nonfiction into verse poetry.', 'The author demonstrates that grammar rules do not apply to political memoirs.']
    ),
    learning_objective: 'Analyzing rhetorical voice transitions and the attribution of moral responsibility.',
    hint: 'How does going from "the decision was executed" to "I signed the order" feel different?',
    irt_a: 1.65,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 6 English Literature Olympiad'
  }
];
