import { ScenarioDef, makeOptions } from './english_types';

export const englishBand11_12: ScenarioDef[] = [
  // ── Understanding (10 items) ──
  {
    scenario_code: 'ENG-1112-UND-01',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: '"Post-structuralist historiography posits that archival documents do not merely reflect past reality; rather, they encode the institutional power structures that authorized and curated their preservation." What does this premise imply for historical inquiry?',
    options: makeOptions('understanding',
      'Researchers must critically interrogate what omissions, silences, and biases were structurally produced by the institutions safeguarding the records.',
      ['Archival preservation is an entirely objective, value-neutral technical curation process.', 'Historical texts written before the printing press contain zero verifiable chronological data.', 'State institutions actively destroyed all private correspondence to prioritize public proclamations.']
    ),
    learning_objective: 'Deconstructing post-structuralist historiographical epistemology and archival power dynamics.',
    hint: 'If archives encode power structures, what must historians ask about what was left out or preserved?',
    irt_a: 1.4,
    irt_b: 0.9,
    irt_c: 0.25,
    international_benchmark: 'IB Diploma Language A Literature / Cambridge A-Level'
  },
  {
    scenario_code: 'ENG-1112-UND-02',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: '"The philosopher argued that contemporary existential dread is not born from a scarcity of choices, but from the paralyzing vertigo of infinite, ungrounded possibilities in a secularized world lacking binding moral teleology." What is identified as the root of modern existential anxiety?',
    options: makeOptions('understanding',
      'The dizzying burden of absolute subjective freedom in the absence of preordained purpose or objective moral anchors.',
      ['The total absence of personal freedom under authoritarian political regimes.', 'A genetic neurochemical deficiency in serotonin receptors across Western populations.', 'Economic poverty resulting from pre-industrial agricultural subsistence.']
    ),
    learning_objective: 'Interpreting existential philosophy, teleological absence, and the vertigo of radical freedom.',
    hint: 'Notice: "paralyzing vertigo of infinite possibilities" in a world "lacking binding moral teleology".',
    irt_a: 1.45,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'AP English Literature & Composition'
  },
  {
    scenario_code: 'ENG-1112-UND-03',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: '"In semiotic analysis, the linguistic sign is fundamentally arbitrary; the signifier (the acoustic sound-image \'tree\') maintains no intrinsic, natural connection to the signified (the botanical organism)." What is the core assertion of Saussurean semiotics presented here?',
    options: makeOptions('understanding',
      'Language is a conventional, culturally mediated system of relational differences rather than a mimetic reflection of physical reality.',
      ['Spoken words possess mystical acoustic frequencies that physically alter plant growth.', 'Written dictionaries must be rewritten annually to reflect botanical classification updates.', 'Onomatopoeic words constitute the entire foundational lexicon of all human languages.']
    ),
    learning_objective: 'Understanding foundational structural linguistics and the arbitrariness of the sign.',
    hint: 'The connection between the word sound and the actual object is arbitrary and culturally agreed upon.',
    irt_a: 1.45,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'Singapore-Cambridge GCE A-Level H2 Literature'
  },
  {
    scenario_code: 'ENG-1112-UND-04',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: '"The architectural critic notes that the glass skyscraper\'s relentless specular transparency is profoundly deceptive: while professing democratic openness, its reflective skin repels scrutiny and hermetically seals the financial elite from the street below." What paradox is diagnosed here?',
    options: makeOptions('understanding',
      'Ostensible visual accessibility that actually functions as an exclusionary, fortified barrier against civic engagement.',
      ['Glass windows that allow excessive solar thermal gain into office cubicles.', 'The structural instability of steel trusses in earthquake zones.', 'A municipal regulation requiring all commercial buildings to install mirrored windows.']
    ),
    learning_objective: 'Deconstructing ideological paradoxes in contemporary architectural theory.',
    hint: 'Contrast the appearance of "democratic openness" with "hermetically sealing the elite".',
    irt_a: 1.5,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'CBSE Class 12 English Core'
  },
  {
    scenario_code: 'ENG-1112-UND-05',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: '"The psychoanalytic theorist observes that the uncanny (das Unheimliche) arises not from encountering the utterly alien, but from the sudden, terrifying resurgence of something intimately familiar that had been repressed." What defines the psychological trigger of the uncanny?',
    options: makeOptions('understanding',
      'The disquieting return of an estranged, repressed inner trauma masquerading as an external monstrosity.',
      ['The phobia of extraterrestrial spacecraft or foreign languages.', 'A rational physiological reaction to sudden optical darkness.', 'A cognitive failure to remember childhood telephone numbers.']
    ),
    learning_objective: 'Analyzing Freudian psychoanalytic theory regarding the uncanny in literature.',
    hint: 'Notice: not the "utterly alien", but the resurgence of something "intimately familiar that had been repressed".',
    irt_a: 1.5,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge International A-Level English Literature'
  },
  {
    scenario_code: 'ENG-1112-UND-06',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: '"Ecocritical theory deconstructs the binary between \'nature\' and \'civilization,\' arguing that the myth of a pristine, external wilderness abdicates human ecological accountability by imagining nature as a separate, self-healing sanctuary." What critique does this perspective level against traditional Romantic environmentalism?',
    options: makeOptions('understanding',
      'Idealizing nature as a detached, pure Eden obscures humanity\'s pervasive, inescapable entwinement within anthropogenically altered planetary networks.',
      ['Romantic poetry provides audited quantitative metrics for atmospheric carbon sequestration.', 'Industrial urban centers should be completely razed to restore untouched primeval wilderness.', 'Wildlife conservation is biologically impossible without commercial logging concessions.']
    ),
    learning_objective: 'Evaluating ecocritical deconstruction of the pristine wilderness myth.',
    hint: 'Think about how imagining nature as "separate and pure" lets humans off the hook for their daily impact.',
    irt_a: 1.55,
    irt_b: 1.3,
    irt_c: 0.25,
    international_benchmark: 'IB Diploma Literature Higher Level'
  },
  {
    scenario_code: 'ENG-1112-UND-07',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: '"The legal theorist contends that the doctrine of original intent in constitutional jurisprudence operates as an epistemic fiction, projecting modern ideological grievances backward onto dead framers who themselves disagreed on foundational principles." What fundamental flaw does this critique attribute to originalism?',
    options: makeOptions('understanding',
      'It anachronistically invents a non-existent historical consensus to legitimize contemporary judicial preferences with artificial historical sanctity.',
      ['The framers of the constitution were illiterate and left no written records.', 'Constitutional conventions were conducted exclusively in classical Greek.', 'Original intent doctrine is mandated by the United Nations Charter.']
    ),
    learning_objective: 'Deconstructing constitutional jurisprudence, originalism, and historiographical fiction.',
    hint: 'Why call original intent an "epistemic fiction"? Because the framers themselves disagreed!',
    irt_a: 1.6,
    irt_b: 1.4,
    irt_c: 0.25,
    international_benchmark: 'Singapore GCE A-Level General Paper'
  },
  {
    scenario_code: 'ENG-1112-UND-08',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: '"In modernist stream-of-consciousness narratives, the collapse of chronological syntactical order reflects an epistemological crisis: the conviction that external clock time is a sterile abstraction unable to capture the chaotic, polyphonic reality of subjective human consciousness." What thematic revelation drives this narrative technique?',
    options: makeOptions('understanding',
      'Linear chronology is an artificial construct; authentic human experience is an entangled, non-linear continuum of memory, perception, and sensation.',
      ['Modernist authors lacked knowledge of standard mechanical clock mechanisms.', 'Stream-of-consciousness was invented to reduce printing press typesetting costs.', 'Objective clock time accurately mirrors the neurological structure of the human brain.']
    ),
    learning_objective: 'Analyzing modernist epistemological crisis and temporal fluidity in stream-of-consciousness.',
    hint: 'Notice the contrast between "sterile external clock time" and "polyphonic subjective consciousness".',
    irt_a: 1.6,
    irt_b: 1.3,
    irt_c: 0.25,
    international_benchmark: 'AP English Literature / Cambridge A-Level'
  },
  {
    scenario_code: 'ENG-1112-UND-09',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: '"The critical theorist argues that algorithmic surveillance capitalism does not merely predict consumer behavior-it manufactures behavioral futures, modifying human volition through real-time feedback loops to guarantee profitability for proprietary prediction markets." What profound transformation of human agency is articulated?',
    options: makeOptions('understanding',
      'The degradation of free human self-determination into engineered behavioral compliance optimized for commercial extraction.',
      ['The voluntary participation of citizens in municipal democratic assemblies.', 'An improvement in digital keyboard typing accuracy through machine learning.', 'The total elimination of financial credit card fraud across e-commerce platforms.']
    ),
    learning_objective: 'Deconstructing Zuboffian surveillance capitalism and the expropriation of human behavioral agency.',
    hint: 'Notice: not merely predicting behavior, but "manufacturing behavioral futures" and "modifying volition".',
    irt_a: 1.7,
    irt_b: 1.6,
    irt_c: 0.25,
    international_benchmark: 'International English Olympiad / World Universities Debating Championship'
  },
  {
    scenario_code: 'ENG-1112-UND-10',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: '"Adorno and Horkheimer\'s critique of the \'culture industry\' posits that mass-produced commodified entertainment does not offer authentic liberation from the exhausting monotony of industrial labor; rather, it reproduces labor\'s mechanized discipline, conditioning consumers to passively accept the status quo in their leisure time." What paradoxical function of modern mass entertainment is unmasked?',
    options: makeOptions('understanding',
      'Far from providing genuine psychological freedom, commercial leisure actively inoculates workers with passive conformity and reinforces systemic alienation.',
      ['Mass entertainment inspires working-class populations to launch immediate political insurrections.', 'Commodified cinema requires excessive intellectual effort that exhausts consumer audiences.', 'Pre-industrial folk music was mass-manufactured in commercial recording studios.']
    ),
    learning_objective: 'Deconstructing Frankfurt School critical theory regarding the culture industry and passive ideological reproduction.',
    hint: 'How does mass entertainment keep people obedient even while they think they are relaxing?',
    irt_a: 1.75,
    irt_b: 1.7,
    irt_c: 0.25,
    international_benchmark: 'Cambridge A-Level Distinction / Oxbridge Entrance Examination'
  },

  // ── Locating Information (10 items) ──
  {
    scenario_code: 'ENG-1112-LOC-01',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'Constitutional Precedent Summary: "In Matter of Jurisdiction [2024] UKSC 12, the Supreme Court held that extraterritorial discovery orders are justiciable under Article 6(1) only when the subject entity maintains a substantial corporate nexus within the forum state, explicitly distinguishing the jurisdictional test established in Al-Skeini." According to this ruling, when do extraterritorial discovery orders become justiciable under Article 6(1)?',
    options: makeOptions('locatingInformation',
      'Strictly when the subject entity possesses a substantial corporate nexus within the forum state.',
      ['Whenever diplomatic immunity is formally waived by the executive branch.', 'Under identical jurisdictional criteria as those formulated in Al-Skeini.', 'Only in criminal prosecutions involving maritime salvage treaties.']
    ),
    learning_objective: 'Locating precise jurisdictional thresholds in high-level appellate judicial precedent.',
    hint: 'Find the condition right after "only when".',
    irt_a: 1.45,
    irt_b: 0.9,
    irt_c: 0.25,
    international_benchmark: 'Cambridge International A-Level Law & English'
  },
  {
    scenario_code: 'ENG-1112-LOC-02',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'Bioengineering Research Protocol: "To achieve CRISPR-Cas12a target trans-cleavage: guide RNA must contain a 20-nucleotide target-complementary spacer flanked by a 5\'-TTTV protospacer adjacent motif (PAM), with ribonucleoprotein incubation conducted in 10 mM Tris-HCl (pH 7.9) at 37°C for 45 minutes." What exact protospacer adjacent motif (PAM) sequence is specified?',
    options: makeOptions('locatingInformation',
      '5\'-TTTV',
      ['3\'-NGG', '20-nucleotide Tris-HCl', 'pH 7.9']
    ),
    learning_objective: 'Scanning high-density molecular bioengineering literature for specific genomic sequences.',
    hint: 'Scan for the acronym "PAM".',
    irt_a: 1.4,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'Singapore GCE A-Level H2 Biology & English'
  },
  {
    scenario_code: 'ENG-1112-LOC-03',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'International Trade Arbitration Award: "Under Article 37.4 of the UNCITRAL Rules, compound interest shall accrue at the 6-month SOFR rate plus a margin of 2.75%, capitalized semi-annually from the date of breach (October 14, 2021) until satisfaction of the award." What interest margin is added to the 6-month SOFR base rate?',
    options: makeOptions('locatingInformation',
      'A margin of 2.75%',
      ['6% compounded annually', '37.4%', 'Zero margin']
    ),
    learning_objective: 'Extracting precise financial penalty formulas from international commercial arbitration awards.',
    hint: 'Look for the phrase "plus a margin of".',
    irt_a: 1.45,
    irt_b: 0.9,
    irt_c: 0.25,
    international_benchmark: 'IB Diploma English A Language and Literature'
  },
  {
    scenario_code: 'ENG-1112-LOC-04',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'Treaty on Outer Space Demilitarization: "Article IV Clause 2: The establishment of military bases, installations, and fortifications, the testing of any type of weapons, and the conduct of military maneuvers on celestial bodies shall be forbidden, though the use of military personnel for scientific research or other peaceful purposes is not prohibited." Under what circumstance is military personnel permitted on celestial bodies?',
    options: makeOptions('locatingInformation',
      'For scientific research or other peaceful purposes.',
      ['For constructing planetary fortifications during geopolitical crises.', 'For testing defensive kinetic projectile weapons.', 'Under no circumstances whatsoever; all military personnel are barred.']
    ),
    learning_objective: 'Isolating express legal exceptions within restrictive international disarmament covenants.',
    hint: 'Find the clause starting with "though the use of military personnel for...".',
    irt_a: 1.5,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'AP English Language / Cambridge A-Level General Paper'
  },
  {
    scenario_code: 'ENG-1112-LOC-05',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'Climatological Paleocores Report: "Analysis of the EPICA Dome C Antarctic ice core reveals that during the Mid-Brunhes Event (430,000 BP), atmospheric CO₂ varied between 180 ppm in glacial maxima and 298 ppm during Marine Isotope Stage 11 (MIS 11), with delta-¹⁸O isotopic shifts indicating Antarctic polar temperatures 2.4°C above pre-industrial baselines." What peak CO₂ concentration was recorded during MIS 11?',
    options: makeOptions('locatingInformation',
      '298 ppm',
      ['180 ppm', '430,000 ppm', '2.4 ppm']
    ),
    learning_objective: 'Scanning multidimensional paleoclimatic datasets for specific stage-linked atmospheric metrics.',
    hint: 'Connect "Marine Isotope Stage 11" directly with its CO₂ ppm figure.',
    irt_a: 1.5,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'Singapore GCE A-Level H2 Geography & Literature'
  },
  {
    scenario_code: 'ENG-1112-LOC-06',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: 'Financial Derivatives Regulatory Standard (Basel IV): "Section 18.1: Counterparty Credit Risk (SA-CCR) dictates that the Alpha multiplier for calculating Exposure at Default (EAD) is fixed at 1.4, except for cleared transactions with Qualifying Central Counterparties (QCCPs) where an exemption factor applies only if default fund contributions are bankruptcy-remote." What is the fixed Alpha multiplier for calculating EAD under standard transactions?',
    options: makeOptions('locatingInformation',
      'Fixed at 1.4',
      ['18.1', 'Zero multiplier', '2.5']
    ),
    learning_objective: 'Extracting fixed calculation coefficients from multi-clause prudential banking regulations.',
    hint: 'Scan for "Alpha multiplier for calculating Exposure at Default (EAD) is fixed at".',
    irt_a: 1.55,
    irt_b: 1.2,
    irt_c: 0.25,
    international_benchmark: 'Cambridge International A-Level Business & Economics'
  },
  {
    scenario_code: 'ENG-1112-LOC-07',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: 'Astrophysical Gravitational Wave Observatory Log: "Event GW230814 registered a signal-to-noise ratio of 26.4 in the Livingston interferometer and 19.8 in Hanford, localized to a 90% credible sky area of 38 deg². Luminosity distance was inferred at 780 Mpc (z ≈ 0.16) with estimated primary progenitor mass of 31.4 solar masses." What was the inferred luminosity distance to event GW230814?',
    options: makeOptions('locatingInformation',
      '780 Mpc (z ≈ 0.16)',
      ['38 deg²', '26.4 Mpc', '31.4 Mpc']
    ),
    learning_objective: 'Extracting precise cosmological distances from gravitational wave detection catalogues.',
    hint: 'Look for "Luminosity distance was inferred at".',
    irt_a: 1.55,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'Singapore GCE A-Level H2 Physics & General Paper'
  },
  {
    scenario_code: 'ENG-1112-LOC-08',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: 'Pharmacogenomics Clinical Guidance: "For patients carrying the CYP2C19*2 or *3 loss-of-function alleles (poor metabolizers), standard clopidogrel antiplatelet therapy exhibits a 48% reduction in active thiol metabolite generation; clinical guidelines mandate transitioning to prasugrel (10 mg daily) or ticagrelor (90 mg twice daily), provided history of intracranial hemorrhage is absent." What dosage of ticagrelor is recommended as an alternative?',
    options: makeOptions('locatingInformation',
      '90 mg twice daily',
      ['10 mg daily', '48 mg once daily', '2 mg twice daily']
    ),
    learning_objective: 'Locating exact pharmaceutical alternative dosages across complex pharmacogenomic clinical guidelines.',
    hint: 'Pair "ticagrelor" with its exact dose and dosing frequency.',
    irt_a: 1.6,
    irt_b: 1.3,
    irt_c: 0.25,
    international_benchmark: 'US AP Biology / Advanced Reading Technical'
  },
  {
    scenario_code: 'ENG-1112-LOC-09',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: 'Maritime Boundary Adjudication: "The International Court of Justice determined that the provisional equidistance line must be adjusted seaward by 14.2 nautical miles along Azimuth 246° to account for the disproportionate coastal concavity of Bay Alpha, thereby ensuring that the ratio of coastal lengths (1:1.68) mirrors the allocated maritime space." What azimuth heading was designated for the 14.2-nautical-mile adjustment?',
    options: makeOptions('locatingInformation',
      'Azimuth 246°',
      ['Azimuth 168°', 'Azimuth 14.2°', 'Azimuth 90°']
    ),
    learning_objective: 'Isolating exact nautical bearings within multilateral international border dispute awards.',
    hint: 'Find the degree heading following "along Azimuth".',
    irt_a: 1.7,
    irt_b: 1.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad Senior Finals'
  },
  {
    scenario_code: 'ENG-1112-LOC-10',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: 'Quantum Cryptographic Architecture: "In the BB84 protocol implementation with decoy states, pulse intensity for signal states was calibrated at mu = 0.48 photons/pulse, decoy state nu1 at 0.12 photons/pulse, and vacuum state nu2 at 0.002 photons/pulse, achieving a secure key rate of 2.4 kbps over 140 km of low-loss optical fiber." What was the calibrated photon intensity for decoy state nu1?',
    options: makeOptions('locatingInformation',
      '0.12 photons/pulse',
      ['0.48 photons/pulse', '0.002 photons/pulse', '2.4 photons/pulse']
    ),
    learning_objective: 'Scanning complex quantum protocol parameter tables for specific sub-state calibration values.',
    hint: 'Look specifically for decoy state "nu1".',
    irt_a: 1.75,
    irt_b: 1.6,
    irt_c: 0.25,
    international_benchmark: 'Cambridge A-Level Distinction / IPhO English Integration'
  },

  // ── Synthesis (10 items) ──
  {
    scenario_code: 'ENG-1112-SYN-01',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'Epistemological Text X: "Empirical verificationism posits that truth assertions are meaningful strictly if they can be corroborated by isolated, sensory protocol statements." Epistemological Text Y: "Quine\'s holism demonstrates that our statements about the external world face the tribunal of sense experience not individually, but only as an interconnected corporate body of beliefs." How does Text Y challenge Text X?',
    options: makeOptions('synthesis',
      'By demonstrating that theoretical webs of belief cannot be parsed into isolated, independently verifiable observation statements.',
      ['By arguing that sensory observation plays zero functional role in scientific paradigm shifts.', 'By asserting that formal mathematical logic is inherently self-contradictory.', 'By affirming that protocol statements possess unassailable Cartesian certainty.']
    ),
    learning_objective: 'Synthesizing verificationist logical positivism with Quinean confirmation holism.',
    hint: 'Text Y argues that ideas face experience as a connected web, not in single isolated statements.',
    irt_a: 1.5,
    irt_b: 1.2,
    irt_c: 0.25,
    international_benchmark: 'IB Diploma Theory of Knowledge / Cambridge A-Level'
  },
  {
    scenario_code: 'ENG-1112-SYN-02',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'Comparative Poetics: "While Romantic naturalism constructed the wilderness as an uncorrupted, sublime cathedral, modern ecocritical theory deconstructs this binary, arguing that the myth of \'pure nature\' abdicates human ecological accountability in hybrid industrial anthropocenes." What conceptual shift is articulated?',
    options: makeOptions('synthesis',
      'A transition from idealizing nature as an external, pristine sanctuary to recognizing humanity\'s inescapable entwinement within anthropogenically altered ecosystems.',
      ['A total rejection of industrial manufacturing in favor of pre-industrial agrarian subsistence.', 'The validation of Romantic sublime theology as the sole effective basis for climate legislation.', 'A proof that literary criticism has zero intersection with ecological sciences.']
    ),
    learning_objective: 'Synthesizing Romantic aesthetic philosophy with contemporary Anthropocene ecocriticism.',
    hint: 'Look for the shift: from nature as an "external pure cathedral" to nature as "inescapably entangled with human impact".',
    irt_a: 1.55,
    irt_b: 1.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore GCE A-Level H2 Literature in English'
  },
  {
    scenario_code: 'ENG-1112-SYN-03',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'Neuroscience Monograph: "Functional MRI studies demonstrate that chronic socio-economic precarity floods the prefrontal cortex with cortisol, impairing executive cognitive control and working memory capacity." Public Policy Analysis: "Social welfare architectures that impose onerous administrative means-testing require immense cognitive bandwidth, causing vulnerable applicants to frequently miss compliance deadlines." What synthesized policy critique emerges?',
    options: makeOptions('synthesis',
      'Complex administrative compliance hurdles paradoxically tax the very cognitive executive bandwidth that chronic poverty biologically impairs, creating systemic traps of exclusion.',
      ['Welfare applicants possess innate biological deficits in mathematical logic that make paperwork impossible.', 'Eliminating cortisol from the bloodstream completely cures chronic socio-economic inequality.', 'Executive function has zero measurable bearing on bureaucratic form completion.']
    ),
    learning_objective: 'Synthesizing neuroendocrinology of chronic stress with structural public policy critique.',
    hint: 'How does stressful poverty reduce brain bandwidth, and how does heavy paperwork demand that very same bandwidth?',
    irt_a: 1.55,
    irt_b: 1.2,
    irt_c: 0.25,
    international_benchmark: 'AP English Language and Composition'
  },
  {
    scenario_code: 'ENG-1112-SYN-04',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'Biomedical Ethics Text: "The principle of non-maleficence mandates that physicians must never administer treatments whose anticipated harms exceed anticipated benefits." Public Health Epidemiology: "During catastrophic infectious pandemics, mass mandatory quarantine restricts individual civil liberties and inflicts psychological harm to prevent systemic hospital collapse." How are these principles synthesized in public health bioethics?',
    options: makeOptions('synthesis',
      'The ethical focus shifts from individual clinical non-maleficence to utilitarian population-level harm minimization and collective preservation.',
      ['Individual civil liberties must always supersede communal survival regardless of mortality rates.', 'Physicians are legally prohibited from practicing epidemiology during respiratory pandemics.', 'Infectious pandemics eliminate all need for bioethical deliberation.']
    ),
    learning_objective: 'Synthesizing clinical bioethical deontological principles with population utilitarian epidemiology.',
    hint: 'Notice the pivot from treating one single patient to protecting the whole community.',
    irt_a: 1.5,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'CBSE Class 12 English Core & Ethics'
  },
  {
    scenario_code: 'ENG-1112-SYN-05',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: 'Historical Text Alpha: "In the 18th century, Adam Smith argued that the division of labor maximizes industrial output through extreme task specialization." Critical Text Beta: "Karl Marx demonstrated that the radical division of labor alienates the worker from the finished product, the process of labor, their fellow workers, and their human creative essence (species-being)." What comprehensive dialectic encapsulates both perspectives?',
    options: makeOptions('synthesis',
      'Industrial division of labor produces unprecedented physical and material productivity, but does so at the psychological cost of existential labor alienation and worker deskilling.',
      ['Smith and Marx agreed that factory automation would eliminate the need for human employment by 1900.', 'Labor specialization enhances human spiritual happiness and eradicates workplace boredom.', 'Manual handicraft guilds produce higher industrial output than mechanized assembly lines.']
    ),
    learning_objective: 'Synthesizing classical political economy (Smith) with critical Marxist labor alienation theory.',
    hint: 'Balance the massive output gains of specialization with the psychological alienation of the worker.',
    irt_a: 1.6,
    irt_b: 1.4,
    irt_c: 0.25,
    international_benchmark: 'IB Diploma Literature & Philosophy Higher Level'
  },
  {
    scenario_code: 'ENG-1112-SYN-06',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: 'Ecological Economics Paper: "The Jevons Paradox establishes that technological improvements in resource efficiency, by reducing the effective cost of consumption, often lead to a net increase in total resource consumption rather than a decrease." Energy Policy Report: "LED lightbulbs use 85% less electricity than incandescent bulbs; however, aggregate municipal outdoor nighttime illumination grew by 60% following LED adoption." How does the lighting report instantiate the Jevons Paradox?',
    options: makeOptions('synthesis',
      'Efficiency gains made nighttime lighting so economically cheap that cities massively expanded illumination, offsetting expected energy conservation.',
      ['LED lightbulbs consume more wattage per hour than antique filament bulbs.', 'The paradox was disproven because overall electrical generation was completely halted.', 'Cities adopted LED lighting exclusively to improve astronomy conditions for urban observatories.']
    ),
    learning_objective: 'Synthesizing macroeconomic resource paradoxes with empirical energy consumption trends.',
    hint: 'Notice how making lighting 85% cheaper led people to install 60% more lights.',
    irt_a: 1.65,
    irt_b: 1.5,
    irt_c: 0.25,
    international_benchmark: 'Cambridge International A-Level Economics & English'
  },
  {
    scenario_code: 'ENG-1112-SYN-07',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: 'Semiotics of Architecture: "Panoptic spatial design utilizes central observation towers to cultivate internal self-policing; individuals behave as if perpetually watched, internalizing external surveillance." Digital Culture Analysis: "Contemporary social media participants continuously curate their speech, appearance, and opinions anticipating algorithmic rating and peer scrutiny." What sociological synthesis connects these domains?',
    options: makeOptions('synthesis',
      'The physical architectural panopticon has evolved into a digital, decentralized algorithmic panopticon, where citizens actively internalize and perform perpetual self-surveillance.',
      ['Physical prison towers are structurally identical to digital fiber-optic cables.', 'Social media platforms have eradicated all forms of social conformity and self-censorship.', 'Algorithmic curation operates entirely without the awareness or participation of users.']
    ),
    learning_objective: 'Synthesizing Foucault\'s panopticism with algorithmic social media self-policing.',
    hint: 'Look for how physical surveillance towers became psychological self-surveillance online.',
    irt_a: 1.65,
    irt_b: 1.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore GCE A-Level H2 General Paper'
  },
  {
    scenario_code: 'ENG-1112-SYN-08',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: 'Epigenetics Study: "Exposure to severe famine induces DNA methylation changes at the IGF2 locus that alter metabolic thrift, alterations that persist and remain biologically detectable in grandchildren two generations later." Sociology of Inequality: "Generational trauma and historical structural poverty produce persistent health disparities across marginalized communities that resist simple lifestyle interventions." What paradigm shift in social medicine is forged by this synthesis?',
    options: makeOptions('synthesis',
      'Historical socioeconomic trauma physically alters biological gene expression across generational lineages, establishing that structural injustice becomes biologically embodied.',
      ['Famine eradicated all genetic variations across human ancestral lineages.', 'Socioeconomic inequality is purely a cultural narrative with zero biological or medical correlates.', 'Epigenetic methylation can be reversed instantly through positive psychological affirmations.']
    ),
    learning_objective: 'Synthesizing transgenerational molecular epigenetics with sociological structural violence.',
    hint: 'How does trauma get written into DNA and passed down across two generations?',
    irt_a: 1.7,
    irt_b: 1.7,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad Senior Division Finals'
  },
  {
    scenario_code: 'ENG-1112-SYN-09',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: 'Linguistic Philosophy: "Wittgenstein\'s \'private language argument\' demonstrates that a language decipherable by only one individual is logically impossible, because language rules require communal verification to distinguish correct usage from mistaken impressions." Cognitive AI Debate: "Proponents of isolated synthetic machine consciousness claim that an isolated neural network can invent its own private semantic understanding in a vacuum." How does Wittgenstein\'s argument undermine the isolated AI claim?',
    options: makeOptions('synthesis',
      'True semantic meaning and rule-following inherently require social, intersubjective communal verification; an isolated system can generate mechanical outputs but cannot establish genuine linguistic meaning.',
      ['Wittgenstein proved that artificial neural networks cannot perform matrix multiplication.', 'Machines cannot process electrical currents without private linguistic dictionaries.', 'All linguistic rules are biological instincts encoded in mammalian DNA.']
    ),
    learning_objective: 'Synthesizing Wittgensteinian philosophy of language with contemporary cognitive AI theory.',
    hint: 'Can meaning exist for a solitary entity with no community to check if a rule is being followed?',
    irt_a: 1.75,
    irt_b: 1.8,
    irt_c: 0.25,
    international_benchmark: 'Oxford / Cambridge Undergraduate Admissions Test (ELAT / TSA)'
  },
  {
    scenario_code: 'ENG-1112-SYN-10',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: 'Post-Colonial Theory: "Frantz Fanon posits that colonization imposes an inferiority complex upon the colonized by forcing them to define their humanity through the linguistic and cultural mirror of the colonizer." Decolonial Pedagogy: "Educational reform in formerly colonized nations must transcend replacing foreign textbooks with local ones; it requires unlearning the epistemological hierarchy that devalues indigenous ways of knowing." What overarching decolonial synthesis is articulated?',
    options: makeOptions('synthesis',
      'Genuine decolonization is not merely a political transfer of state power, but a radical epistemological emancipation that dismantles internalized hierarchies of cultural and intellectual validity.',
      ['Decolonial pedagogy mandates the total burning of all printed historical archives.', 'Fanon argued that language has zero impact on psychological identity or cultural self-worth.', 'Replacing foreign textbooks with domestic translations instantly achieves complete decolonization.']
    ),
    learning_objective: 'Synthesizing Fanonian psycho-colonial theory with radical decolonial epistemological pedagogy.',
    hint: 'Notice: true decolonization requires dismantling the internalized hierarchy of what counts as knowledge.',
    irt_a: 1.8,
    irt_b: 1.8,
    irt_c: 0.25,
    international_benchmark: 'IB Diploma English A Literature High Distinction'
  },

  // ── Evaluating & Reflecting (10 items) ──
  {
    scenario_code: 'ENG-1112-EVL-01',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: '"The essayist employs an ironically understated, clinically sterile vocabulary to recount catastrophic wartime civilian displacement." What stylistic dissonance is generated, and to what deliberate ethical end?',
    options: makeOptions('evaluatingReflecting',
      'The jarring contrast between human devastation and bureaucratic sterility powerfully indicts the dehumanizing, technocratic detachment of modern warfare.',
      ['The sterile vocabulary proves the author lacked first-hand testimony of the events described.', 'The understated phrasing aims to minimize reader anxiety so the publication passes military censors.', 'It transforms the historical essay into an operational handbook for battlefield logistics.']
    ),
    learning_objective: 'Evaluating stylistic dissonance, understated irony, and rhetorical indictment in war literature.',
    hint: 'Why talk about devastation with cold, clinical words? To show how modern war treats people like cold numbers.',
    irt_a: 1.45,
    irt_b: 1.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge International A-Level Literature'
  },
  {
    scenario_code: 'ENG-1112-EVL-02',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: '"When the narrative perspective shifts abruptly from panoramic third-person omniscience into fractured, unreliable first-person interior monologue, what psychometric and interpretive disruption occurs for the reader?"',
    options: makeOptions('evaluatingReflecting',
      'The reader is abruptly stripped of objective authoritative certainty and forced to navigate subjective cognitive distortion and epistemic vulnerability.',
      ['The plot chronology halts permanently to insert an expository biographical footnote.', 'The linguistic register simplifies to accommodate juvenile demographic readers.', 'The author signals that the preceding narrative was entirely a dream sequence.']
    ),
    learning_objective: 'Analyzing interpretive destabilization through shifting narrative perspective and unreliable narration.',
    hint: 'Going from an all-knowing narrator to a fractured first-person mind strips away all objective certainty.',
    irt_a: 1.5,
    irt_b: 1.2,
    irt_c: 0.25,
    international_benchmark: 'IB Diploma Language A Literature'
  },
  {
    scenario_code: 'ENG-1112-EVL-03',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: 'In analyzing an editorial on biotechnology, a scholar observes: "The author frames human gene editing using religious idioms of \'playing God\' and \'violating sacred biological sanctity,\' while systematically ignoring empirical clinical safety trial data." What rhetorical strategy is exposed?',
    options: makeOptions('evaluatingReflecting',
      'Deploying metaphysical taboos and dogmatic emotional heuristics to preemptively close empirical scientific debate.',
      ['A rigorous mathematical proof of cellular enzymatic instability.', 'An objective presentation of peer-reviewed clinical cardiology trials.', 'A defense of secular pharmaceutical patent monopolies.']
    ),
    learning_objective: 'Deconstructing metaphysical taboos and dogmatic rhetoric in scientific bioethics debates.',
    hint: 'Notice how religious idioms ("playing God") are used to bypass actual clinical data.',
    irt_a: 1.5,
    irt_b: 1.2,
    irt_c: 0.25,
    international_benchmark: 'AP English Language and Composition'
  },
  {
    scenario_code: 'ENG-1112-EVL-04',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'standard',
    prompt: '"The historian concludes: \'The monarch did not build the grand palace to celebrate his sovereign security, but to mask his profound vulnerability; its monumental marble colonnades were an architectural scream defying his imminent obsolescence.\'" What psychological reinterpretation of monumentality is offered?',
    options: makeOptions('evaluatingReflecting',
      'Monumental grandeur as compensatory overcompensation: using excessive physical majesty to conceal fragile political precarity.',
      ['A literal engineering critique of marble quarry extraction techniques.', 'Praise for the monarch\'s enlightened economic patronage of stonecutters.', 'A proof that classical architecture guarantees geopolitical military dominance.']
    ),
    learning_objective: 'Interpreting architectural monumentality as compensatory psychological defensiveness.',
    hint: 'The palace was built not because he felt safe, but to hide that he was weak and doomed.',
    irt_a: 1.55,
    irt_b: 1.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore GCE A-Level H2 Literature'
  },
  {
    scenario_code: 'ENG-1112-EVL-05',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: '"In analyzing the corporate sustainability manifesto, the critic remarks: \'The manifesto dedicates forty pages to carbon offset tree-planting photo-essays, while confining its twenty-fold expansion of fossil-fuel deepwater exploration to a three-line footnote.\' How does the critic expose corporate greenwashing?"',
    options: makeOptions('evaluatingReflecting',
      'By demonstrating severe proportional asymmetry: elevating symbolic public relations gestures while burying catastrophic core extractive commitments.',
      ['By proving that tree-planting is biologically harmful to atmospheric oxygen levels.', 'By commending the company\'s transparent disclosure of exploratory drilling costs.', 'By verifying that footnote typography violates international copyright law.']
    ),
    learning_objective: 'Deconstructing greenwashing through structural rhetorical asymmetry and document analysis.',
    hint: '40 pages of tree photos vs a 3-line footnote for massive oil drilling: massive visual asymmetry.',
    irt_a: 1.6,
    irt_b: 1.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge International A-Level General Paper'
  },
  {
    scenario_code: 'ENG-1112-EVL-06',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: '"The post-colonial critic notes: \'The novelist adopts the elevated imperial register of Victorian English only to deliberately shatter its syntactical balance with indigenous Creole idioms and polyvocal cadences.\' What subversive aesthetic objective is accomplished?"',
    options: makeOptions('evaluatingReflecting',
      'Linguistic appropriation and decolonization: weaponizing the colonizer\'s prestigious tongue against itself to validate suppressed indigenous rhythms.',
      ['An inadvertent error caused by the author\'s imperfect grasp of standard English grammar.', 'A commercial concession to increase mass paperback sales in Victorian London.', 'A pedagogical manual designed to eradicate regional Caribbean dialects.']
    ),
    learning_objective: 'Analyzing post-colonial counter-discourse, linguistic subversion, and polyvocality.',
    hint: 'Why write in high Victorian style only to break it open with Creole idioms? To decolonize the language from within.',
    irt_a: 1.65,
    irt_b: 1.5,
    irt_c: 0.25,
    international_benchmark: 'IB Diploma English A Literature Higher Level'
  },
  {
    scenario_code: 'ENG-1112-EVL-07',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'advanced',
    prompt: '"When the legal philosopher characterizes contract law not as \'the neutral realization of private autonomy,\' but as \'the state-sanctioned formalization of pre-existing economic disparities,\' what foundational legal fiction is being dismantled?"',
    options: makeOptions('evaluatingReflecting',
      'The presumption that contracting parties possess equal bargaining power in market transactions.',
      ['The physical validity of written ink signatures on commercial paper.', 'The authority of appellate judges to interpret statutory municipal tax codes.', 'The historical connection between Roman contract law and modern maritime commerce.']
    ),
    learning_objective: 'Critiquing formal legal equality and the myth of equal bargaining power in contract theory.',
    hint: 'It takes down the idea that both sides entering a contract have equal freedom and power.',
    irt_a: 1.65,
    irt_b: 1.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore GCE A-Level H2 General Paper'
  },
  {
    scenario_code: 'ENG-1112-EVL-08',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: '"The dramatist constructs the play so that every character\'s impassioned ideological defense of their actions is shown to be an elaborate, self-deluding rationalization for base material self-interest. What overarching cynical worldview permeates the theatrical dramaturgy?"',
    options: makeOptions('evaluatingReflecting',
      'A corrosive hermeneutics of suspicion: positing that moral ideals are merely post-hoc intellectual disguises for primal animal egoism and resource acquisition.',
      ['A celebration of transcendent altruism and selfless human martyrdom.', 'A classical tragedy validating the absolute divine justice of mythological deities.', 'A pedagogical demonstration of classical rhetorical elocution techniques.']
    ),
    learning_objective: 'Analyzing the hermeneutics of suspicion and moral disillusionment in dramatic literature.',
    hint: 'If every moral speech is really just an excuse for selfish greed, what worldview is that?',
    irt_a: 1.75,
    irt_b: 1.7,
    irt_c: 0.25,
    international_benchmark: 'Oxford English Literature Admissions Test (ELAT)'
  },
  {
    scenario_code: 'ENG-1112-EVL-09',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: '"The essayist deconstructs modern wellness culture, asserting: \'By reframing systemic institutional burnout as a personal psychological failure solvable through commercial mindfulness apps, corporate capitalism commodifies the very exhaustion it produces.\' What profound ideological operation is diagnosed?"',
    options: makeOptions('evaluatingReflecting',
      'The depoliticization and privatization of structural exploitation, turning worker exhaustion into a lucrative secondary market for therapeutic consumerism.',
      ['A clinical trial proving that mindfulness meditation cures all autoimmune diseases.', 'An endorsement of corporate human resource wellness subsidies.', 'A technical critique of digital smartphone application code architecture.']
    ),
    learning_objective: 'Deconstructing the neoliberal commodification of wellness and structural depoliticization.',
    hint: 'Notice: taking systemic overwork and selling back apps to "fix your personal failure".',
    irt_a: 1.8,
    irt_b: 1.8,
    irt_c: 0.25,
    international_benchmark: 'Cambridge A-Level Distinction / Ivy League Diagnostic'
  },
  {
    scenario_code: 'ENG-1112-EVL-10',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '11-12',
    difficulty: 'olympiad',
    prompt: '"In reflecting on the Holocaust, philosopher Theodor Adorno famously proclaimed: \'To write poetry after Auschwitz is barbaric.\' What profound crisis of culture, representation, and aesthetics does this aphorism crystallize?"',
    options: makeOptions('evaluatingReflecting',
      'The devastating realization that traditional humanistic culture failed to prevent absolute industrial slaughter, rendering traditional aesthetic pleasure morally suspect and ethically compromised.',
      ['A legal prohibition banning the printing of rhymed verse in post-war Germany.', 'A claim that visual painting is superior to written literature in commemorating tragedy.', 'An assertion that the German language lacked sufficient vocabulary for poetic composition.']
    ),
    learning_objective: 'Evaluating Adorno\'s philosophical critique of culture and aesthetics in the shadow of historical catastrophe.',
    hint: 'How can culture claim to be elevated and beautiful when the very society that produced it created industrial slaughter?',
    irt_a: 1.85,
    irt_b: 1.9,
    irt_c: 0.25,
    international_benchmark: 'World Universities Debating Championship / High Honors Literature'
  }
];
