import { ScenarioDef, makeOptions } from './english_types';

export const englishBand7_8: ScenarioDef[] = [
  // ── Understanding (10 items) ──
  {
    scenario_code: 'ENG-78-UND-01',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: '"While the city council heralded the arterial bypass as an overdue economic catalyst, residents in the historic merchant quarter lamented the severance of centuries-old pedestrian conduits." What constitutes the foundational tension in this account?',
    options: makeOptions('understanding',
      'Modern vehicular efficiency and commercial expansion versus the preservation of communal cultural heritage and pedestrian life.',
      ['A budgetary disagreement between paving stone manufacturers and asphalt suppliers.', 'A dispute regarding municipal council election dates.', 'Disagreement among long-distance truck drivers over highway toll payment lanes.']
    ),
    learning_objective: 'Analyzing core thematic conflicts between modernization and historic preservation.',
    hint: 'Look at what the council wanted (bypass/economic catalyst) vs what residents mourned (pedestrian conduits).',
    irt_a: 1.25,
    irt_b: -0.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Lower Secondary Checkpoint Stage 8'
  },
  {
    scenario_code: 'ENG-78-UND-02',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: '"To dismiss the astrophysicist\'s initial sensor anomalies as instrumental noise was convenient, yet it postponed the confirmation of the exoplanet by nearly a decade." What does the author imply by describing the dismissal as "convenient"?',
    options: makeOptions('understanding',
      'It was an intellectually lazy and self-serving evasion of unexpected empirical complexity.',
      ['It was a logistically practical and highly rigorous scientific protocol.', 'It was cost-effective because computer storage drives were inexpensive.', 'It was coordinated to match university semester deadlines.']
    ),
    learning_objective: 'Interpreting critical subtext and authorial irony in academic narratives.',
    hint: 'Why would calling a scientific dismissal "convenient" be a criticism?',
    irt_a: 1.3,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'Singapore MOE Secondary 2 English'
  },
  {
    scenario_code: 'ENG-78-UND-03',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: '"The diplomat\'s statement was calibrated with such microscopic ambiguity that opposing factions each left the summit convinced their non-negotiable demands had been ratified." What does this reveal about the diplomat\'s strategy?',
    options: makeOptions('understanding',
      'Deliberate linguistic vagueness was utilized to achieve temporary consensus without resolving the underlying dispute.',
      ['The diplomat lacked sufficient grasp of the official conference working languages.', 'Both factions had agreed in advance to abandon all territorial claims.', 'The summit treaty was written in an undeciphered ancient cipher.']
    ),
    learning_objective: 'Deconstructing political rhetoric and strategic ambiguity.',
    hint: 'Notice that opposing sides each believed they won because of the "microscopic ambiguity".',
    irt_a: 1.35,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 8 English Language'
  },
  {
    scenario_code: 'ENG-78-UND-04',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: '"Despite the tempest howling outside and thrashing the coastal pines, our small stone hearth radiated an unyielding warmth, anchoring the room against the night." What atmosphere is created by this juxtaposition?',
    options: makeOptions('understanding',
      'A profound sanctuary of domestic security and resilience contrasted against external violent chaos.',
      ['A state of panic as the stone fireplace threatened to collapse under wind gusts.', 'An accurate meteorological log measuring ocean gale wind vectors.', 'Disappointment that firewood supplies were rapidly being depleted.']
    ),
    learning_objective: 'Analyzing atmospheric contrast and emotional resonance in descriptive fiction.',
    hint: 'Contrast the "tempest howling outside" with the "unyielding warmth, anchoring the room".',
    irt_a: 1.3,
    irt_b: 0.0,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 8 Reading Literature'
  },
  {
    scenario_code: 'ENG-78-UND-05',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: '"The novel\'s protagonist mistook cynical detachment for intellectual maturity, scorning empathy as a sentimental liability until isolation forced a re-evaluation." What core flaw defines the protagonist\'s trajectory?',
    options: makeOptions('understanding',
      'Equating emotional indifference with wisdom, which inevitably resulted in painful personal estrangement.',
      ['An inability to comprehend basic academic texts without tutoring.', 'A reckless ambition to acquire immense speculative fortune.', 'A clinical fear of traveling beyond his home city boundaries.']
    ),
    learning_objective: 'Evaluating character arc and psychological delusion in thematic fiction.',
    hint: 'Notice how the character viewed cynicism as "intellectual maturity" and empathy as a "liability".',
    irt_a: 1.35,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'CBSE Class 8 English Literature'
  },
  {
    scenario_code: 'ENG-78-UND-06',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: '"In describing the abandoned textile mill as a \'derelict leviathan rusting beside the stagnant canal,\' what impression does the author evoke regarding the decline of industrial manufacture?"',
    options: makeOptions('understanding',
      'The mill is depicted as an obsolete, decaying colossus whose once-immense power has become a stranded relic of the past.',
      ['The factory is actively operating modern robotic loom assembly lines.', 'A real prehistoric marine reptile was trapped in the municipal drainage system.', 'The canal water was diverted to irrigate nearby botanical gardens.']
    ),
    learning_objective: 'Analyzing evocative metaphors and symbolic industrial decay.',
    hint: 'What does comparing a mill to a "derelict leviathan" (a stranded giant monster) symbolize?',
    irt_a: 1.4,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Checkpoint Stage 8 Literature'
  },
  {
    scenario_code: 'ENG-78-UND-07',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: '"The architect insisted that true minimalism is not an austere absence of ornamentation, but the rigorous elimination of the superfluous until only pure structural necessity remains." How does this distinction redefine minimalism?',
    options: makeOptions('understanding',
      'As an intentional, disciplined distillation of purpose rather than a merely barren aesthetic trend.',
      ['As an inexpensive technique to reduce the wages of structural masonry workers.', 'As a mandate that all interior furniture must be manufactured from stainless steel.', 'As a decorative style that requires ornate plaster moldings.']
    ),
    learning_objective: 'Deconstructing conceptual definitions and philosophical nuances in design essays.',
    hint: 'Contrast "austere absence" with "rigorous elimination of the superfluous".',
    irt_a: 1.45,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 2 Express English'
  },
  {
    scenario_code: 'ENG-78-UND-08',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: '"The biographer refrains from hagiography; instead of casting the inventor as an infallible solitary genius, she chronicles his persistent intellectual indebtedness to overlooked laboratory assistants." What distinguishes this biography?',
    options: makeOptions('understanding',
      'It demystifies the myth of isolated genius by documenting collaborative contributions and human limitations.',
      ['It glorifies the inventor as an unassailable national hero beyond reproach.', 'It accuses the inventor of systematic scientific fraud and patent theft.', 'It focuses exclusively on the commercial marketing of the finished products.']
    ),
    learning_objective: 'Identifying historiographical stance and biographical demystification.',
    hint: 'Notice: "refrains from hagiography" (uncritical praise) and credits "overlooked assistants".',
    irt_a: 1.5,
    irt_b: 0.6,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 8 Informational Text'
  },
  {
    scenario_code: 'ENG-78-UND-09',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: '"The essayist argues that our modern obsession with continuous digital connectivity does not expand genuine communal intimacy; rather, it replaces deep, demanding interpersonal presence with frictionless, curated superficiality." What central diagnosis does the essayist offer?',
    options: makeOptions('understanding',
      'Digital hyper-connection cultivates an illusion of closeness that actively undermines substantive, authentic human vulnerability.',
      ['Computer networks should be dismantled to encourage postal letter correspondence.', 'Social media algorithms accurately measure psychological empathy among teenagers.', 'Frictionless communication has successfully eradicated global linguistic barriers.']
    ),
    learning_objective: 'Synthesizing sociological critique of contemporary digital epistemology.',
    hint: 'Contrast "frictionless, curated superficiality" with "demanding interpersonal presence".',
    irt_a: 1.6,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad / SASMO Junior'
  },
  {
    scenario_code: 'ENG-78-UND-10',
    subject: 'English Literacy',
    competency: 'understanding',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: '"When the narrator describes the ancient glacier as \'a slow, frozen tongue erasing the mountain\'s memory with every century of descent,\' what dual existential impression is conveyed?"',
    options: makeOptions('understanding',
      'The overwhelming geological timescale of nature alongside its inexorable power to pulverize historical landscapes.',
      ['The medical properties of sub-zero ice for preserving extinct mammoths.', 'The rapid acceleration of alpine tourism in ski resorts.', 'The acoustic properties of cracking ice shelf crevasses.']
    ),
    learning_objective: 'Interpreting sublime geological scale and poetic personification in literary essays.',
    hint: 'Think about a glacier moving across centuries, literally wiping away the terrain.',
    irt_a: 1.65,
    irt_b: 0.9,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary Checkpoint High Distinction'
  },

  // ── Locating Information (10 items) ──
  {
    scenario_code: 'ENG-78-LOC-01',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Space Mission Protocol: "During primary booster staging (T+142s), telemetry is routed to Ground Station Alice Springs. Failover telemetry automatically switches to Orbital Relay constellation Sigma only if primary latency exceeds 450 milliseconds for more than 1.2 seconds." Under what precise condition does failover engage?',
    options: makeOptions('locatingInformation',
      'Only when primary telemetry latency exceeds 450 ms for more than 1.2 seconds.',
      ['Immediately upon main engine ignition at T-0.', 'Whenever Ground Station Alice Springs undergoes scheduled antenna recalibration.', 'Only if booster staging occurs prior to T+100s.']
    ),
    learning_objective: 'Locating dual-condition technical thresholds in mission critical protocols.',
    hint: 'Look for both the latency measurement (450 ms) and duration threshold (1.2 s).',
    irt_a: 1.3,
    irt_b: -0.2,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary 1 Stage 7'
  },
  {
    scenario_code: 'ENG-78-LOC-02',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Civic Environmental Ordinance: "Section 12(B): Commercial entities generating over 50 kg of organic waste daily must contract with an authorized bio-methanation facility by June 30, 2027. Entities producing between 20 kg and 50 kg are granted an extension until December 31, 2028." What is the deadline for an entity generating 35 kg daily?',
    options: makeOptions('locatingInformation',
      'December 31, 2028',
      ['June 30, 2027', 'January 1, 2026', 'Immediate compliance upon receipt']
    ),
    learning_objective: 'Extracting categorized regulatory compliance deadlines based on numerical criteria.',
    hint: 'Determine which category 35 kg falls into: between 20 kg and 50 kg.',
    irt_a: 1.35,
    irt_b: 0.0,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 1 Express'
  },
  {
    scenario_code: 'ENG-78-LOC-03',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Scientific Laboratory Procedure: "To prevent thermal crystallization during titration: maintain reagent temperature strictly between 38°C and 42°C, introduce sodium citrate dropwise at a maximum rate of 0.5 mL/min, and agitate continuously at 250 RPM." What is the maximum permissible rate of sodium citrate addition?',
    options: makeOptions('locatingInformation',
      '0.5 mL/min',
      ['250 RPM', '38°C', '42 mL/min']
    ),
    learning_objective: 'Extracting exact chemical delivery rates from multi-parameter laboratory manuals.',
    hint: 'Search specifically for the reagent "sodium citrate" and its rate unit (mL/min).',
    irt_a: 1.35,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 7 Technical Text'
  },
  {
    scenario_code: 'ENG-78-LOC-04',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Historical Charter: "The Guild of Shipwrights ordained that apprentices must complete five full calendar years of drydock framing, execute one masterwork rib-joint unassisted, and pay forty silver shillings into the widows\' fund before obtaining freedom of trade." How many years of drydock framing were mandated?',
    options: makeOptions('locatingInformation',
      'Five full calendar years',
      ['Forty years', 'One year', 'Three calendar months']
    ),
    learning_objective: 'Isolating specific durational requirements in historical institutional statutes.',
    hint: 'Find the duration paired with "drydock framing".',
    irt_a: 1.3,
    irt_b: -0.1,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 7 English Language'
  },
  {
    scenario_code: 'ENG-78-LOC-05',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Volcanology Briefing: "The seismic array detected harmonic tremors at a focal depth of 6.4 km beneath Mount Merapi. Magmatic extrusion rates averaged 1.8 m³/s throughout August, rising to 3.5 m³/s following the tectonic swarm on September 3." What was the average extrusion rate throughout August?',
    options: makeOptions('locatingInformation',
      '1.8 m³/s',
      ['3.5 m³/s', '6.4 km', '9 m³/s']
    ),
    learning_objective: 'Scanning chronological geophysical reports for timeframe-specific rate metrics.',
    hint: 'Distinguish between the August rate and the post-September rate.',
    irt_a: 1.4,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary Stage 8 Informational'
  },
  {
    scenario_code: 'ENG-78-LOC-06',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: 'Cybersecurity Whitepaper: "Under protocol TLS-Alpha, asymmetric handshakes utilize elliptic-curve Diffie-Hellman with 384-bit key lengths; session keys are regenerated every 60 minutes or after every 2 gigabytes of encrypted payload transfer, whichever threshold is breached first." What are the two trigger conditions for session key regeneration?',
    options: makeOptions('locatingInformation',
      'Every 60 minutes elapsed OR after 2 gigabytes of payload transfer.',
      ['Every 384 seconds OR whenever key length drops below 128 bits.', 'Whenever a client disconnects from the VPN gateway.', 'Only upon an explicit brute-force intrusion notification.']
    ),
    learning_objective: 'Extracting dual-threshold trigger mechanisms from network security specifications.',
    hint: 'Notice the phrase: "whichever threshold is breached first".',
    irt_a: 1.45,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 2 Express Checkpoint'
  },
  {
    scenario_code: 'ENG-78-LOC-07',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: 'Pharmacological Monograph: "Bioavailability of Compound Z is 68% when ingested fasting, but decreases to 34% when co-administered with divalent cations such as magnesium or calcium. Peak plasma concentration (Cmax) is achieved at 1.5 hours post-dose." What factor halves Compound Z\'s bioavailability?',
    options: makeOptions('locatingInformation',
      'Co-administration with divalent cations like magnesium or calcium.',
      ['Ingestion in a strictly fasting state with pure distilled water.', 'Administering the compound at 1.5-hour intervals.', 'Elevating plasma concentration above 68%.']
    ),
    learning_objective: 'Identifying specific biochemical inhibitors and conditions in clinical literature.',
    hint: 'Compare 68% fasting to 34% when taken with certain minerals.',
    irt_a: 1.5,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 8 Informational Scanning'
  },
  {
    scenario_code: 'ENG-78-LOC-08',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: 'Antarctic Meteorological Dossier: "At Dome Concordia (Elevation 3,233 m), the lowest surface air temperature recorded was -84.6°C on September 3, 2017. Average katabatic wind speeds during the polar night reach 28 knots, with sustained gusts exceeding 65 knots during polar vortex incursions." What was the record low temperature?',
    options: makeOptions('locatingInformation',
      '-84.6°C',
      ['3,233 m', '-65°C', '28 knots']
    ),
    learning_objective: 'Isolating specific historical extremes within dense climatological records.',
    hint: 'Scan for the temperature unit (°C) and the word "lowest".',
    irt_a: 1.45,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'CBSE Class 8 Advanced English'
  },
  {
    scenario_code: 'ENG-78-LOC-09',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: 'Maritime Legal Judgment: "The Tribunal ruled that under Clause 14.3 of the Charterparty, demurrage accrues at $15,000 per running day pro rata, commencing exactly 12 hours after the Master tenders Notice of Readiness (NOR), unless port closure is formally declared by the Sovereign Authority." When does demurrage begin to accrue?',
    options: makeOptions('locatingInformation',
      'Exactly 12 hours after the Master tenders Notice of Readiness, absent sovereign port closure.',
      ['Immediately upon dropping anchor in the outer harbor roadstead.', 'Only after 15,000 running hours have elapsed since bill of lading issuance.', 'When the Sovereign Authority approves cargo customs manifestos.']
    ),
    learning_objective: 'Extracting precise contractual timelines and legal exception clauses.',
    hint: 'Locate the exact delay period following the NOR tender.',
    irt_a: 1.6,
    irt_b: 0.7,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad / SASMO Junior'
  },
  {
    scenario_code: 'ENG-78-LOC-10',
    subject: 'English Literacy',
    competency: 'locatingInformation',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: 'Genetic Sequencing Field Report: "Amplification of the cytochrome c oxidase subunit I (COI) barcode locus required an initial denaturation phase of 95°C for 3 minutes, followed by 35 cycles of 94°C (30s), 52°C (40s), and 72°C (1 min). What was the annealing temperature during the 35 cycles?',
    options: makeOptions('locatingInformation',
      '52°C',
      ['95°C', '94°C', '72°C']
    ),
    learning_objective: 'Scanning complex PCR cycling protocols for the intermediate annealing temperature.',
    hint: 'In standard 3-step PCR (denature, anneal, extend), annealing is the middle temperature.',
    irt_a: 1.65,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary Checkpoint Olympiad Division'
  },

  // ── Synthesis (10 items) ──
  {
    scenario_code: 'ENG-78-SYN-01',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Text 1: "Urban heat islands amplify nighttime temperatures by up to 6°C due to the thermal mass of concrete, brick, and asphalt." Text 2: "Cities that mandate extensive green living roofs and high-albedo reflective pavements record a 35% reduction in commercial HVAC cooling energy demand." What holistic conclusion connects these texts?',
    options: makeOptions('synthesis',
      'Passive architectural and material interventions in urban surfaces can effectively mitigate heat island intensity while slashing municipal energy consumption.',
      ['Air conditioning units are the sole structural cause of urban heat retention.', 'Asphalt must be replaced exclusively with deep subterranean drainage tunnels.', 'Nighttime temperatures have no measurable bearing on metropolitan energy consumption.']
    ),
    learning_objective: 'Synthesizing urban thermodynamic data with sustainable architectural policy.',
    hint: 'Connect the heat-absorbing concrete in Text 1 with the living roofs/albedo in Text 2.',
    irt_a: 1.35,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Lower Secondary Stage 8 Synthesis'
  },
  {
    scenario_code: 'ENG-78-SYN-02',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Study Alpha: "Microplastic particles under 50 micrometers are ingested by pelagic zooplankton." Study Beta: "Zooplankton form the primary trophic foundation for juvenile herring and mackerel, which are subsequently consumed by apex predatory tuna and humans." What overarching food-web deduction is established?',
    options: makeOptions('synthesis',
      'Microplastic pollution bioaccumulates and biomagnifies upward through trophic marine levels, ultimately threatening human nutritional chains.',
      ['Apex predatory tuna are biologically equipped to metabolize synthetic petroleum plastics into protein.', 'Zooplankton populations expand rapidly when feeding on industrial polyester fibers.', 'Microplastics remain permanently confined to seabed sediment layers without entering fauna.']
    ),
    learning_objective: 'Tracing ecological contamination across multiple trophic levels.',
    hint: 'Follow the chain: plastic -> zooplankton -> small fish -> tuna -> humans.',
    irt_a: 1.35,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 2 English & Science'
  },
  {
    scenario_code: 'ENG-78-SYN-03',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Economic Ledger: "Raw copper prices rose 45% due to supply chain mine strikes in the Andes." Industrial Bulletin: "Manufacturer Q shifted its residential electrical wiring lines from copper core to copper-clad aluminum alloy." What synthesized explanation accounts for Manufacturer Q\'s engineering transition?',
    options: makeOptions('synthesis',
      'Manufacturer Q redesigned product materials to substitute cheaper composite metals in response to soaring raw copper costs.',
      ['Aluminum is a superior electrical conductor compared to pure copper in all industrial environments.', 'Andean copper mines produce only aluminum alloy ore.', 'The government mandated that all copper must be preserved for sculpture monuments.']
    ),
    learning_objective: 'Synthesizing macroeconomic commodity spikes with industrial material substitution.',
    hint: 'Why would a manufacturer use copper-clad aluminum right when copper prices shoot up 45%?',
    irt_a: 1.4,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 8 Informational'
  },
  {
    scenario_code: 'ENG-78-SYN-04',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'Botanical Observation: "Epiphytic orchids possess specialized spongy roots (velamen) that absorb ambient water vapor directly from humid air." Climatological Data: "Cloud forest deforestation caused a 25% drop in local ambient relative humidity over five years." What will be the consequence for indigenous cloud forest orchids?',
    options: makeOptions('synthesis',
      'The orchids will suffer severe hydration stress and population decline because their aerial root mechanisms require high ambient humidity.',
      ['The orchids will immediately grow deep terrestrial taproots into the bedrock.', 'Orchid flowering cycles will accelerate because sunlight is increased.', 'The velamen tissue will transform into photosynthetic broad leaves.']
    ),
    learning_objective: 'Synthesizing physiological botanical mechanisms with microclimate degradation.',
    hint: 'If orchids get water from humidity, what happens when deforestation dries out the air?',
    irt_a: 1.4,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 8 English & Biology'
  },
  {
    scenario_code: 'ENG-78-SYN-05',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: 'Document 1: "The 1883 eruption of Krakatoa injected over 20 million tons of sulfur aerosols into the stratosphere." Document 2: "Global meteorological stations recorded an average planetary surface temperature drop of 1.2°C during 1884, alongside vivid crimson sunsets recorded by painters across Europe." What synthesis bridges these physical and artistic phenomena?',
    options: makeOptions('synthesis',
      'Stratospheric sulfate aerosols scattered solar radiation globally, causing both physical atmospheric cooling and optical scattering that altered sunset aesthetics worldwide.',
      ['Volcanic lava flows warmed European rivers and induced widespread psychological delirium among painters.', 'Crimson sunsets were caused by coal-burning factories in London rather than Krakatoa.', 'The temperature drop proved that volcanic eruptions halt planetary greenhouse gas cycles entirely.']
    ),
    learning_objective: 'Synthesizing volcanological aerosol dynamics with historical climatology and art history.',
    hint: 'How do sulfur aerosols in the high atmosphere cause both cooling and reddish skies?',
    irt_a: 1.45,
    irt_b: 0.4,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary Checkpoint Stage 8'
  },
  {
    scenario_code: 'ENG-78-SYN-06',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: 'Source A: "Acoustic noise from commercial maritime shipping overlaps with the low-frequency vocalization bandwidth of baleen whales (10 Hz to 200 Hz)." Source B: "Endocrinological assays of whale blubber demonstrate a 60% surge in stress hormone glucocorticoids in shipping corridors." What unified conclusion is established?',
    options: makeOptions('synthesis',
      'Anthropogenic maritime acoustic pollution directly masks vital whale communication, inducing chronic physiological stress.',
      ['Whales deliberately alter their migratory routes to escort commercial container vessels.', 'Glucocorticoid surges indicate that whales enjoy swimming alongside cargo ship propeller wakes.', 'Low-frequency shipping sounds improve whale echolocation acuity during oceanic hunting.']
    ),
    learning_objective: 'Synthesizing anthropogenic acoustic data with marine biological endocrinology.',
    hint: 'Connect frequency overlap (communication masking) with high stress hormones.',
    irt_a: 1.5,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 2 Express Synthesis'
  },
  {
    scenario_code: 'ENG-78-SYN-07',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: 'Theory: "The spacing effect demonstrates that distributed review sessions over time yield significantly superior long-term memory retention compared to massed cramming." Experiment: "Cohort A studied 10 hours in a single Saturday; Cohort B studied 2 hours every other day for 5 days. Tested 30 days later, Cohort B remembered 74% of the vocabulary, while Cohort A remembered 28%." How does the experimental data corroborate the theory?',
    options: makeOptions('synthesis',
      'It quantitatively proves that distributed spacing creates more durable synaptic memory traces than equivalent time spent in massed cramming.',
      ['It demonstrates that total studying time is the sole determinant of retention regardless of schedule.', 'It shows that vocabulary acquisition is biologically impossible over weekend study blocks.', 'It proves that Cohort A was composed of students with lower baseline cognitive capacity.']
    ),
    learning_objective: 'Synthesizing cognitive psychological theory with empirical quantitative retention tests.',
    hint: 'Compare equal study time (10 hours) distributed vs crammed.',
    irt_a: 1.5,
    irt_b: 0.6,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 8 Research Synthesis'
  },
  {
    scenario_code: 'ENG-78-SYN-08',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: 'Linguistic Text: "Old English (circa 800 CE) utilized complex inflectional grammatical cases and grammatical gender." Historical Text: "Following the 1066 Norman Conquest, Old French became the prestige language of royal administration, while Anglo-Saxon commoners and Scandinavian settlers interacted daily in multilingual trade marketplaces." What synthesized sociolinguistic mechanism explains the subsequent loss of complex inflections in Middle English?',
    options: makeOptions('synthesis',
      'Everyday pragmatic communication across diverse linguistic populations favored structural leveling and simplified morphological endings in favor of rigid word order.',
      ['The Norman kings passed strict penal codes making the use of Old English inflectional suffixes a capital offense.', 'Grammatical gender was abolished by ecclesiastical decree from the Archbishop of Canterbury.', 'Old English was preserved with zero structural modifications inside monastic scriptoria.']
    ),
    learning_objective: 'Synthesizing historical sociolinguistics, contact linguistics, and morphological leveling.',
    hint: 'When speakers of different languages must trade daily, what happens to complex word endings?',
    irt_a: 1.6,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad Junior'
  },
  {
    scenario_code: 'ENG-78-SYN-09',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: 'Agricultural Report: "Continuous mono-cropping of corn depletes bioavailable soil nitrogen by 30% annually." Microbiology Study: "Legumes establish symbiotic root nodules with Rhizobium bacteria, converting atmospheric dinitrogen into mineral ammonium." Traditional Agronomy: "Mesoamerican farmers planted maize alongside beans and squash in polycultural \'Three Sisters\' guilds." What scientific rationale validates the traditional Three Sisters guild?',
    options: makeOptions('synthesis',
      'The nitrogen-fixing legume beans naturally replenish the essential nitrogen exhausted by nutrient-hungry maize, sustaining long-term soil fertility.',
      ['Squash leaves absorb groundwater and pump it into the roots of surrounding cornstalks.', 'Maize produces atmospheric dinitrogen gas that kills root-dwelling Rhizobium bacteria.', 'Polycultural guilds are practiced purely for visual aesthetic harmony during festival harvest seasons.']
    ),
    learning_objective: 'Synthesizing biogeochemical nutrient cycles with historical indigenous agronomy.',
    hint: 'Connect corn\'s nitrogen depletion with bean nodules fixing nitrogen.',
    irt_a: 1.65,
    irt_b: 0.9,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary Checkpoint Olympiad Tier'
  },
  {
    scenario_code: 'ENG-78-SYN-10',
    subject: 'English Literacy',
    competency: 'synthesis',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: 'Physics Postulate: "Conservation of angular momentum dictates that as a rotating body\'s mass concentrates closer to its axis of rotation, its rotational velocity must increase." Astronomical Observation: "When a massive dying star collapses from a radius of 1,000,000 km into a dense neutron star with a radius of only 12 km, its spin period accelerates from months into milliseconds." How does the astronomical observation substantiate the physics postulate?',
    options: makeOptions('synthesis',
      'The dramatic reduction in radius contracts stellar moment of inertia, forcing extreme spin acceleration to conserve total angular momentum.',
      ['Neutron stars possess magnetic fields that physically drag nearby space-time into rotation.', 'Dying stars absorb rotational energy from colliding neighboring galaxies during supernova collapse.', 'The observation disproves the postulate because stellar mass is destroyed during gravitational collapse.']
    ),
    learning_objective: 'Synthesizing foundational physical conservation laws with astrophysics phenomena.',
    hint: 'Think of an ice skater pulling in their arms: smaller radius -> much faster spin.',
    irt_a: 1.7,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 8 Science & English Olympiad'
  },

  // ── Evaluating & Reflecting (10 items) ──
  {
    scenario_code: 'ENG-78-EVL-01',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: '"The historian repeatedly describes the medieval parchment manuscript as \'whispering forgotten heresies from beneath centuries of dust.\' What stylistic resonance is achieved by this personification?',
    options: makeOptions('evaluatingReflecting',
      'It endows the physical artifact with mysterious agency, historical intimacy, and suppressed ideological drama.',
      ['It provides literal acoustic decibel measurements of parchment vibration.', 'It proves that the manuscript was copied by multiple illiterate scribes.', 'It casts doubt on the archaeological authenticity of the parchment provenance.']
    ),
    learning_objective: 'Evaluating the aesthetic and dramatic functions of personification in historical prose.',
    hint: 'How does describing a book as "whispering forgotten heresies" make the reader feel?',
    irt_a: 1.3,
    irt_b: 0.1,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Lower Secondary Checkpoint Stage 8'
  },
  {
    scenario_code: 'ENG-78-EVL-02',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'A pharmaceutical advertisement claims: "9 out of 10 doctors surveyed recommend NeuroBoost for morning fatigue!" What critical question must a discerning reader ask to evaluate this claim?',
    options: makeOptions('evaluatingReflecting',
      'How many total doctors were surveyed, how were they selected, and was the survey funded by the manufacturer?',
      ['What color is the packaging of the NeuroBoost capsule box?', 'Can NeuroBoost be consumed with carbonated beverages?', 'Are the doctors legally licensed to operate motor vehicles?']
    ),
    learning_objective: 'Evaluating sample selection bias, statistical validity, and commercial conflicts of interest.',
    hint: 'If only 10 cherry-picked company doctors were asked, does 9 out of 10 mean anything?',
    irt_a: 1.35,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 8 Critical Evaluation'
  },
  {
    scenario_code: 'ENG-78-EVL-03',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: '"The senator began her speech on the national debt by recalling her grandfather\'s tiny general store and how he balanced his physical ledger book by candlelight every Saturday night." What rhetorical strategy is being employed here?',
    options: makeOptions('evaluatingReflecting',
      'An appeal to folk nostalgia and homespun common sense to simplify a complex macroeconomic issue into an emotionally relatable moral allegory.',
      ['A technical econometric breakdown of foreign bond interest yield curves.', 'An objective presentation of audited central bank currency reserves.', 'A formal refutation of commercial bankruptcy jurisprudence.']
    ),
    learning_objective: 'Deconstructing folksy nostalgic anecdotes as persuasive framing devices in politics.',
    hint: 'Why talk about a grandfather\'s tiny ledger book when debating a multi-trillion national debt?',
    irt_a: 1.4,
    irt_b: 0.3,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 2 Express English'
  },
  {
    scenario_code: 'ENG-78-EVL-04',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'standard',
    prompt: 'An author introduces a villain with: "His smile was impeccable, gleaming like polished porcelain, but it never reached the cold, calculating slate of his eyes." What psychological insight does this imagery implant in the reader?',
    options: makeOptions('evaluatingReflecting',
      'Duality and deceit: an outward veneer of charm concealing an underlying predatory and unfeeling disposition.',
      ['A clinical dental diagnosis of healthy tooth enamel.', 'A sympathetic portrayal of a character suffering from eye strain.', 'An objective appraisal of stone carving craftsmanship.']
    ),
    learning_objective: 'Analyzing facial imagery and emotional dissonance in character characterization.',
    hint: 'Contrast the gleaming smile with the cold, calculating eyes.',
    irt_a: 1.35,
    irt_b: 0.2,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 8 English Literature'
  },
  {
    scenario_code: 'ENG-78-EVL-05',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: '"The op-ed writer opens: \'Either we ban all artificial intelligence development immediately, or we surrender our humanity to silicon overlords.\' Which logical fallacy undermines this polemic?',
    options: makeOptions('evaluatingReflecting',
      'False dilemma (bifurcation): reducing a multifaceted regulatory issue into two extreme, mutually exclusive choices.',
      ['Ad hominem attack against individual software developers.', 'Circular reasoning that repeats the premise as the conclusion.', 'Post hoc ergo propter hoc causal confusion.']
    ),
    learning_objective: 'Identifying false dilemmas and black-and-white fallacies in argumentative discourse.',
    hint: 'Are those really the only two possible choices for AI?',
    irt_a: 1.45,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Secondary Stage 8 Argumentation'
  },
  {
    scenario_code: 'ENG-78-EVL-06',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: 'In reviewing a contemporary novel, a critic writes: "The author mistakes relentless misery for profound artistry, piling misfortune upon catastrophe without providing a shred of thematic illumination." What is the essence of this critique?',
    options: makeOptions('evaluatingReflecting',
      'Unrelieved gratuitous suffering does not equate to substantive philosophical or literary insight.',
      ['The novel has too few pages to properly develop its characters.', 'The author should have written a cheerful children\'s comedy instead.', 'The book contains grammatical syntax errors in its dialogue.']
    ),
    learning_objective: 'Evaluating literary criticism and the distinction between melodrama and artistic depth.',
    hint: 'What is the critic saying about piling on sadness without "thematic illumination"?',
    irt_a: 1.5,
    irt_b: 0.6,
    irt_c: 0.25,
    international_benchmark: 'Singapore Secondary 2 Express Literature'
  },
  {
    scenario_code: 'ENG-78-EVL-07',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'advanced',
    prompt: '"The travel essay concludes: \'We traveled ten thousand miles to photograph pristine wilderness, only to discover our own footprints permanently pressed into the tundra.\' What reflective realization does this closing sentence impart?"',
    options: makeOptions('evaluatingReflecting',
      'An ironic awareness of human ecological complicity: the very act of seeking untouched wilderness inevitably alters and intrudes upon it.',
      ['Regret over failing to wear proper thermal hiking boots.', 'A practical realization that tundra soil requires paving.', 'Anger that other tourists arrived at the summit first.']
    ),
    learning_objective: 'Reflecting on situational irony and human complicity in travel journalism.',
    hint: 'Notice the irony of going to see "untouched" land only to find you left your footprints on it.',
    irt_a: 1.5,
    irt_b: 0.5,
    irt_c: 0.25,
    international_benchmark: 'US Common Core Grade 8 Reflective Reading'
  },
  {
    scenario_code: 'ENG-78-EVL-08',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: '"The political speechwriter skillfully employed anaphora, opening six consecutive sentences with \'We shall not falter...\' What psychological momentum does this repetitive rhetorical cadence generate?"',
    options: makeOptions('evaluatingReflecting',
      'Cumulative emotional resolve and rhythmic inevitability, rallying collective resolve through rhythmic linguistic reinforcement.',
      ['Linguistic fatigue and confusion regarding grammatical sentence syntax.', 'Evidence that the speaker lacked sufficient varied vocabulary to compose prose.', 'An attempt to disguise factual inaccuracies in the accompanying statistical appendix.']
    ),
    learning_objective: 'Evaluating anaphora and rhythmic structural rhetoric in public oratory.',
    hint: 'What does repeating a strong phrase six times do to a listener\'s feelings?',
    irt_a: 1.6,
    irt_b: 0.8,
    irt_c: 0.25,
    international_benchmark: 'Singapore English Olympiad Junior'
  },
  {
    scenario_code: 'ENG-78-EVL-09',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: '"To call the corporation\'s mass laying off of three thousand factory workers \'a workforce right-sizing optimization\' is to sanitize economic devastation with the clinical dialect of corporate technocracy." What authorial stance is revealed by this indictment?',
    options: makeOptions('evaluatingReflecting',
      'Fierce moral indignation against dehumanizing corporate euphemisms that disguise human suffering.',
      ['Enthusiastic support for corporate managerial efficiency.', 'Indifference toward labor union contract negotiations.', 'A technical defense of executive stock option vesting structures.']
    ),
    learning_objective: 'Deconstructing technocratic euphemisms and analyzing authorial outrage.',
    hint: 'Notice words like "sanitize economic devastation" and "clinical dialect".',
    irt_a: 1.65,
    irt_b: 0.9,
    irt_c: 0.25,
    international_benchmark: 'Cambridge Checkpoint Stage 8 Distinction Tier'
  },
  {
    scenario_code: 'ENG-78-EVL-10',
    subject: 'English Literacy',
    competency: 'evaluatingReflecting',
    developmental_band: '7-8',
    difficulty: 'olympiad',
    prompt: '"When the satirist praises the dystopian government for \'magnanimously rationing electricity so citizens can rediscover the romance of darkness,\' what rhetorical mechanism is operating?"',
    options: makeOptions('evaluatingReflecting',
      'Sarcastic irony: professing admiration for an authoritarian failure to expose its absurdity and oppression.',
      ['Literal praise for municipal renewable energy conservation.', 'A scientific treatise on the circadian sleep benefits of complete darkness.', 'Historical nostalgia for medieval pre-electric societies.']
    ),
    learning_objective: 'Analyzing sustained satirical irony and authorial intent in dystopian literature.',
    hint: 'Is the author truly romanticizing an authoritarian blackout, or mocking it?',
    irt_a: 1.7,
    irt_b: 1.0,
    irt_c: 0.25,
    international_benchmark: 'ICSE Class 8 English Literature Advanced'
  }
];
